### ISSUE TITLE
Flattening the Genotype schema

### ISSUE THREAD

**Issue by akmorrow13** [bigdatagenomics/adam#1002]
We incur heavy overhead from queries which find genotypes in which their variants meet a certain criteria. If we were to flatten the genotype schema, query times could be reduced from 130 seconds to 8 seconds over a 70 kb range.

**Comment by heuermh** [comment]
Fixed by https://github.com/bigdatagenomics/bdg-formats/pull/77?

**Comment by akmorrow13** [comment]
Yes this was fixed by bigdatagenomics/bdg-formats#77.
