### ISSUE TITLE
Port single file BAM and header code to VCF

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1009]
I was looking over the VCF export code while working on #909 and noticed that we had a lot of cruft around setting the VCF headers. Also, we don't have code for writing out a single VCF file.

**Comment by heuermh** [comment]
We'll also need header + concat stuff for writing out a single IntervalList feature file.

**Comment by ryan-williams** [comment]
Recent activity on #676 discusses the need for this in BAMs as well.
