### ISSUE TITLE
Factor out *RDDFunctions classes

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1011]
We have many *RDDFunctions classes in org.bdgenomics.adam.rdd that should be factored out. I think that if we did this, we could eliminate most of the implicit conversions in `org.bdgenomics.adam.rdd.ADAMContext` too.

**Comment by heuermh** [comment]
Please elaborate a bit more.  I had some further clean up and moving stuff around in mind.

ADAMContext is a nasty bugger in terms of cyclic package dependencies and extensibility.  Perhaps it needs to be that way so that users only have to ```import ADAMContext._``` though.

**Comment by fnothaft** [comment]
I just opened #1015, which I think will shade more light on my thoughts. Specifically, I'd like to eliminate all the `*RDDFunctions` classes and their implicits by migrating the code into the classes that extend `GenomicRDD`s.

**Comment by fnothaft** [comment]
Punting to 0.21.0.

**Comment by heuermh** [comment]
Not sure I agree.  I don't see the utility in cutting a release halfway through a major refactoring.

**Comment by fnothaft** [comment]
That's a fair point. Then maybe we push 0.20.0 out to end of June?

**Comment by heuermh** [comment]
Yeah, let's try to do a round of triage and estimation while we're all together in person.

**Comment by fnothaft** [comment]
This will have big conflicts with #1081 and #964. I would like to merge this in first, since it is the vastly more complex PR, and to then rebase the other two on top.
