### ISSUE TITLE
Reenable Travis CI for pull request builds

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#1023]
We have a Travis CI configuration
https://github.com/bigdatagenomics/adam/blob/master/.travis.yml

and a repository on Travis (though inactive for two years)
https://travis-ci.org/bigdatagenomics/adam

I wonder if it might be possible to reenable Travis CI and disable Jenkins for pull request builds.  Jenkins would continue building nightly and could still respond to requests to build on demand (at least I hope that is possible).

**Comment by fnothaft** [comment]
-1. I don't think that supporting a second CI platform is a good use of engineering resources from our side. If we have issues we'd like to address (e.g., the Git force push issue, which @shaneknapp is working to resolve) then let's try to address them in Jenkins first.

**Comment by heuermh** [comment]
A workaround for the git force push issue is in place.
