### ISSUE TITLE
ADAM specific logging

### ISSUE THREAD

**Issue by jpdna** [bigdatagenomics/adam#1024]
Due to Spark 2.0 moving to `org.apache.spark.internal.Logging` which is private to Spark, we need to have our own `Logging` trait specific to ADAM.

I'd propose to do this by creating an
`org.bdgenomics.adam.Logging` trait and companion object modeled after:
https://github.com/apache/spark/blob/branch-1.6/core/src/main/scala/org/apache/spark/Logging.scala

If anyone has an alternative suggestion, please let me know.

**Comment by fnothaft** [comment]
I would rather open this upstream in `org.bdgenomics.utils.misc`.

**Comment by fnothaft** [comment]
Otherwise, I am +1.

**Comment by jpdna** [comment]
> I would rather open this upstream in org.bdgenomics.utils.misc.

makes sense, will do

**Comment by heuermh** [comment]
+1 to bgd-utils

**Comment by jpdna** [comment]
This logging stuff  is gonna be more of a pain then I thought....
I guess we now pay the price for not heeding the warning:
https://github.com/apache/spark/blob/branch-1.6/core/src/main/scala/org/apache/spark/Logging.scala#L32

I had initially  planned to make our ADAM version of logging by basically copy and paste code from the old externally accessible version of spark Logger at
https://github.com/apache/spark/blob/branch-1.6/core/src/main/scala/org/apache/spark/Logging.scala
into package `org.bdgenomics.utils.misc`

That almost works, but to make logging work with REPL `Logger` contains: 
https://github.com/apache/spark/blob/branch-1.6/core/src/main/scala/org/apache/spark/Logging.scala#L124
which uses `org.apache.spark.utils.Utils` which itself was already private to Spark in 1.6

So - to continue on this path we will also need to create an ADAM copy of all applicable parts of `org.apache.spark.util`
if  we are going to make ADAM logging continue to work in the same way.

I think this will be possible, but copying and pasting lots of code here smells bad.
Let me know if you see a better way - otherwise I will push on with copying logging related code from Spark to ADAM.

**Comment by heuermh** [comment]
What does this façade provide beyond that already provided by slf4j Logger?  As long as ours are consistently marked ```@transient``` I don't see much there.

**Comment by fnothaft** [comment]
I am a-OK with dropping REPL logger optimization (what does that even mean? it looks like it just switches the logging config if you are in the REPL) if it simplifies the logger.

**Comment by fnothaft** [comment]
Closed by https://github.com/bigdatagenomics/adam/commit/33841c071f5820a229e9143ee0686c176bc2ac40.
