### ISSUE TITLE
[build system] ADAM test builds pollute /tmp, leaving lots of cruft...

### ISSUE THREAD

**Issue by shaneknapp** [bigdatagenomics/adam#1038]
this is slowly filling up the disks on the jenkins workers.  for example, ssh in to any of the amp-jenkins-[01..08] machines and take a look in /tmp.

**Comment by heuermh** [comment]
Thanks for letting us know.  Writing to /tmp (via the JDK's temporary file mechanism) in unit tests has been intentional on my part.

**Comment by shaneknapp** [comment]
no problem...  and don't worry, i'm not just singling out you guys.  it's happening across many different product builds.

here's a ganglia graph of /tmp's disk usage on amp-jenkins-worker-01...  you can see that in mid-may, i cleaned it (the spike in available space) and it filled up rather quickly afterwards.

![tmp_nightmare](https://cloud.githubusercontent.com/assets/1606572/15484469/07a11586-20ef-11e6-88d9-e5ea910a4a4b.png)
