### ISSUE TITLE
Support VCF annotation ANN field in vcf2adam and adam2vcf

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#1044]
Schema were added to `bdg-formats` in https://github.com/bigdatagenomics/bdg-formats/pull/67.

**Comment by fnothaft** [comment]
Should be resolved by #1250.

**Comment by heuermh** [comment]
#1250 doesn't fully address this yet.

Mappings between the VCF INFO reserved key ANN and calls to `TranscriptEffectConverter.convertToTranscriptEffects` and `TranscriptEffectConverter.convertToVcfInfoAnnValue` need to be added to `VariantAnnotationConverter` as part of further refactoring.

**Comment by jpdna** [comment]
#1271 should address this correct?

**Comment by heuermh** [comment]
No, I haven't written the code yet. :)

Look for a new pull request that says it fixes this issue.

**Comment by heuermh** [comment]
Fixed by #1288
