### ISSUE TITLE
Add generic ReferenceRegion pushdown for parquet files

### ISSUE THREAD

**Issue by akmorrow13** [bigdatagenomics/adam#1047]
Would look like this:

```
val predicate: FilterPredicate = ((LongColumn("end") >= region.start) && (LongColumn("start") <= region.end) && (BinaryColumn("contigName") === Binary.fromString(region.referenceName)))
```

**Comment by heuermh** [comment]
+1

**Comment by akmorrow13** [comment]
Sitting on a personal branch: https://github.com/akmorrow13/mango/blob/middle-cache/mango-core/src/main/scala/org/bdgenomics/mango/util/ResourceUtils.scala#L32

Do we want to put this in a more central location @heuermh @fnothaft @devin-petersohn ?

**Comment by devin-petersohn** [comment]
In #1324, there has been some discussion between @fnothaft, @heuermh, and me around the possibility of using ReferenceRegion in Formats. Should we revisit this?

**Comment by fnothaft** [comment]
I'm triaging this to 0.24.0.
