### ISSUE TITLE
scala.MatchError RegExp  does not catch colons in value part properly

### ISSUE THREAD

**Issue by pauca** [bigdatagenomics/adam#1061]
line https://github.com/bigdatagenomics/adam/blob/b29d20480001be20e0be55e828a147b5f222ce42/adam-core/src/main/scala/org/bdgenomics/adam/util/AttributeUtils.scala#L31 
with 
`val attrRegex = RegExp("([^:]{2,4}):([AifZHB]):([cCiIsSf]{1},)?(.*)")`

does not handle properly alignmentrecords with attributes like
`OQ:Z:C55/15D:::::::.7GFFAFDA442.40F=AGHHE`
ie. have colons in the value part

some problematic reads are contained in gatk bundle file  CEUTrio.HiSeq.WGS.b37.NA12878.bam
```
scala> BamWriter.adamSAMSave( "output.bam", bam.sequences, bam.recordGroups , true, true ,false)
2016-06-30 17:01:41 ERROR Utils:95 - Aborting task
scala.MatchError: Z:C, (of class java.lang.String)
	at org.bdgenomics.adam.util.AttributeUtils$.createAttribute(AttributeUtils.scala:92)
	at org.bdgenomics.adam.util.AttributeUtils$.parseAttribute(AttributeUtils.scala:74)
	at org.bdgenomics.adam.util.AttributeUtils$$anonfun$parseAttributes$2.apply(AttributeUtils.scala:61)

```

**Comment by fnothaft** [comment]
Thanks for reporting this @pauca! We will look into this in the next week. We have some separate logic to extract the `OQ` field, and I think this isn't getting handled properly.
