### ISSUE TITLE
VariantCallingAnnotations is getting populated with INFO fields

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1063]
See https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantAnnotationConverter.scala#L112. Variant calling annotations should be populated from the per-sample GT "FORMAT" fields, not INFO fields.

**Comment by heuermh** [comment]
Fixed by #1288
