### ISSUE TITLE
Clean up packages

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1083]
Documentation and packaging cleanup for:

- [ ] `org.bdgenomics.adam.models`
- [x] `org.bdgenomics.adam.projections`
- [ ] `org.bdgenomics.adam.rich` see #1263
- [x] `org.bdgenomics.adam.serialization`
- [x] `org.bdgenomics.adam.util`
- [x] `org.bdgenomics.adam.rdd` classes not cleaned up in #1051

**Comment by heuermh** [comment]
I'd like to propose the following package name changes:
```
org.bdgenomics.adam.rdd.features --> org.bdgenomics.adam.feature
org.bdgenomics.adam.rdd.variation --> org.bdgenomics.adam.variant
```

**Comment by heuermh** [comment]
object `Timers` in package `org.bdgenomics.adam.instrumentation` could use some higher level doc, when to define one, how to use one, etc.

**Comment by fnothaft** [comment]
+1 @heuermh
