### ISSUE TITLE
Release ADAM version 0.21.0

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1088]
_Timeline:_ November 15, 2016
_Release goal:_ Documentation and code changes to support ADAM paper.

[0.21.0 Milestone](https://github.com/bigdatagenomics/adam/milestone/15)
[0.21.0 Project](https://github.com/bigdatagenomics/adam/projects/3)

**Comment by heuermh** [comment]
Possible new features:
Sequence, slice, and read schema
GA4GH protobuf schema
Phenotype schema, e.g. Phenopackets
Graph assembly schema
Pipe API for external bioinformatics applications
Snap, Freebayes, and SnpEff support via Pipe API

**Comment by heuermh** [comment]
Would it be ok to truncate the checkboxes from the issue description above and instead use the milestone for tagging issues and the project for triaging them?

**Comment by fnothaft** [comment]
> Would it be ok to truncate the checkboxes from the issue description above and instead use the milestone for tagging issues and the project for triaging them?

I assume `s/project/issue/g` in the above comment ("...and the issue for triaging...")? If so, yes, that sounds good to me; that's how we were tracking issues for releases prior to 0.20.0.

**Comment by heuermh** [comment]
I haven't had that much coffee yet, so I think I said the right thing.  :)

Doing the checkboxes in these issues was kind of redundant with tagging via Milestone tags, although grouping individual issues into themes might have been somewhat useful.

By project I mean this https://github.com/bigdatagenomics/adam/projects/3.  By triage I mean 1) tag issues with Milestones and 2) use the project trello-like cards for the what's done/what's not view and any other intermediate categorization (in progress, needs review, etc.), if that might be useful.

**Comment by fnothaft** [comment]
Oh, cool! Misunderstanding was on my side; I'd forgotten about the new projects feature. That SGTM!

**Comment by lbergelson** [comment]
What's the status of this?  Is there still going to be a release soon or will it be delayed for a while?

**Comment by fnothaft** [comment]
Hi @lbergelson! Sorry for the delay here. We had a couple of issues pull out by a week with the Thanksgiving holiday. @heuermh and I were sitting together today and working on the release; I think we'll close within the week.

**Comment by lbergelson** [comment]
No problem! Thanks for the update.  Holidays always slow everything down, even when you've already tried to account for it.

**Comment by heuermh** [comment]
All the 0.21.0 milestone issues and pull requests have been closed and merged, so I'll work on cutting the release this afternoon.  The only remaining task is to update the release notes, which for better or worse must still be edited and committed manually during release process (see #936).

**Comment by fnothaft** [comment]
Thank you, @heuermh!

**Comment by heuermh** [comment]
Fixed by commit 64917242228254e2a7849bb6fc10b0684e3e547c.  Rsync to Maven Central will take a few hours.

**Comment by heuermh** [comment]
Blog announcement pull request at https://github.com/bigdatagenomics/bigdatagenomics.github.io/pull/13.  After that is merged and the site updated, I'll post an announcement to adam-developers@ and via Twitter.
