### ISSUE TITLE
loadvcf: conflicting require statement

### ISSUE THREAD

**Issue by akmorrow13** [bigdatagenomics/adam#1094]
The requirement statement in loadVCF in ADAMContext line 634 is very misleading:

```
    // we can only replace the sequences header if the sequence info was missing on the vcf
    require(sdOpt.isEmpty || vcfSd.isEmpty,
      "Only one of the provided or VCF sequence dictionary can be specified.")
```

It says only one sequence dictionary is allowed to be specified but then it fails if only 1 sequence dictionary is empty. Is the or supposed to be an and?

**Comment by fnothaft** [comment]
The require statement is correct; it will only fire if both SequenceDictionaries are populated and the expression evaluates to false. Can you send me a dataset/command line offline that reproduces the bug?
