### ISSUE TITLE
VariantContextConverter never returns DatabaseVariantAnnotation

### ISSUE THREAD

**Issue by akmorrow13** [bigdatagenomics/adam#1097]
in VariantContextConverter function convert line 184:
`def convert(vc: HtsjdkVariantContext): Seq[ADAMVariantContext] `

always creates ADAMVariantContext without a DatabaseVariantAnnotation, even in the 1000genomes files with alleleFrequency fields.

**Comment by fnothaft** [comment]
That's going to be patched by https://github.com/bigdatagenomics/adam/pull/1078. If you need this right now with the ADAM 0.19.0 DatabaseVariantAnnotation schema, you may want to use some derivative upon https://github.com/bigdatagenomics/quinine/pull/36/commits/a5cb6b05b1e9b4802f8409002d9a81d3ce49f1b8. I'm going to close this as a dupe for now, but please reopen this if you think it should fall outside of #1078.
