### ISSUE TITLE
ReferenceRegion.apply(AlignmentRecord) should not NPE on unmapped reads

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1099]
This is a little one that's bugged me for a long time. We should have a `require` that checks whether the read is mapped and throws a more informative error message.

**Comment by heuermh** [comment]
Dupe of #821?

**Comment by fnothaft** [comment]
Nah, I would categorize #821 differently, since #821 is the join operation.

**Comment by fnothaft** [comment]
Also, #821 won't be resolved by the resolution to this. You'll still get an exception from calling `ReferenceRegion.apply` on an unmapped read, it'll just be a clearer exception.
