### ISSUE TITLE
Variant dbsnp rs id tracking in vcf2adam and ADAM2Vcf

### ISSUE THREAD

**Issue by jpdna** [bigdatagenomics/adam#1103]
Currently when running `vcf2adam` followed by `adam2vcf`  the ID column in the original VCF file, commonly a dbSNP rs_id, is lost.

Looking at bdg-formats, I now realize that there is no ID field in Variant, and I am not sure where ID would be stored if we wanted to preserve it.    One possibility is the `attributes` field of Variant Annotation.   I'd tend to suggest that the ID field is so basic and practically useful to many users that there should be a nullable field for it in Variant.   Or am I missing where ID is currently stored?

What do you think @heuermh and @fnothaft ?

**Comment by fnothaft** [comment]
Thanks for bringing this up. We had this in 0.7.1 --> https://github.com/bigdatagenomics/bdg-formats/blob/bdg-formats-0.7.0/src/main/resources/avro/bdg.avdl#L732 but lost it recently (e.g., https://github.com/bigdatagenomics/bdg-formats/blob/master/src/main/resources/avro/bdg.avdl#L961 is a boolean). I've opened https://github.com/bigdatagenomics/bdg-formats/issues/96.

**Comment by heuermh** [comment]
Fixed by #1131

**Comment by fnothaft** [comment]
Should be resolved by #1250.

**Comment by heuermh** [comment]
Actually, this one was fixed earlier than #1250 by #1131 but won't show up on master until #1135 is merged.

**Comment by heuermh** [comment]
Fixed by #1131.
