### ISSUE TITLE
K-mer.scala code

### ISSUE THREAD

**Issue by Pavan637** [bigdatagenomics/adam#1105]
K-mer.scala code given at https://github.com/bigdatagenomics/adam is giving me errors.
I ran that code in two ways "

> adam-shell -i kmer.scala

> scalac kmer.scala

I am getting following errors
$scalac kmer.scala
kmer.scala:5: error: expected class or object definition
val ac = new ADAMContext(sc)
^
kmer.scala:7: error: expected class or object definition
val reads = ac.loadAlignments(
^
kmer.scala:19: error: expected class or object definition
val kmers =
^
kmer.scala:26: error: expected class or object definition
kmers.take(10).foreach(println)
^
four errors found

And when i run on spark "adam-shell -i kmer.scala". I am getting following errors
<console>:19: error: object rdd is not a member of package org.bdgenomics.adam
       import org.bdgenomics.adam.rdd.ADAMContext
                                  ^
<console>:19: error: object rdd is not a member of package org.bdgenomics.adam
       import org.bdgenomics.adam.rdd.ADAMContext._
                                  ^
<console>:19: error: object projections is not a member of package org.bdgenomics.adam
       import org.bdgenomics.adam.projections.{ AlignmentRecordField, Projection }
                                  ^
<console>:21: error: not found: type ADAMContext
       val ac = new ADAMContext(sc)
                    ^
<console>:19: error: not found: value ac
       val reads = ac.loadAlignments(
                   ^
<console>:20: error: not found: value reads
         reads
         ^
<console>:1: error: illegal start of definition
           .flatMap(_.getSequence.sliding(21).map(k => (k, 1L)))
           ^
<console>:1: error: illegal start of definition
           .reduceByKey(_ + _)
           ^
<console>:1: error: illegal start of definition
           .map(_.swap)
           ^
<console>:1: error: illegal start of definition
           .sortByKey(ascending = false)
           ^
<console>:20: error: not found: value kmers
              kmers.take(10).foreach(println)
              ^
Kindly help me to solve the issues.

Regards
Pavan

**Comment by fnothaft** [comment]
Hi @Pavan637! What is the content of `kmers.scala`? Can you post it as a gist?

**Comment by Pavan637** [comment]
Here is the code from the link (https://github.com/bigdatagenomics/adam)

`import org.bdgenomics.adam.rdd.ADAMContext
import org.bdgenomics.adam.rdd.ADAMContext._
import org.bdgenomics.adam.projections.{AlignmentRecordField, Projection}

val ac = new ADAMContext(sc)
// Load alignments from disk
val reads = ac.loadAlignments(
  "/data/NA21144.chrom11.ILLUMINA.adam",
  projection = Some(
    Projection(
      AlignmentRecordField.sequence,
      AlignmentRecordField.readMapped,
      AlignmentRecordField.mapq
    )
  )
)

// Generate, count and sort 21-mers
val kmers =
  reads
    .flatMap(_.getSequence.sliding(21).map(k => (k, 1L)))
    .reduceByKey(_ + _)
    .map(_.swap)
    .sortByKey(ascending = false)

// Print the top 10 most common 21-mers
kmers.take(10).foreach(println)`

**Comment by fnothaft** [comment]
Hi @Pavan637! We changed our build recently, and accidentally broke `./bin/adam-shell`. I've just opened #1111 with a fix for this. Can you try this on your side?

**Comment by heuermh** [comment]
Thank you for reporting this, @Pavan637.

This issue was closed when I merged the pull request.  If the change does not work for you, please reopen this issue.
