### ISSUE TITLE
BroadcastRegionJoin is not a broadcast join

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1110]
Will resolve this in #1109. The BroadcastRegionJoin is implemented as a hash join, not a broadcast join.

**Comment by heuermh** [comment]
Was this resolved in #1109?

**Comment by fnothaft** [comment]
> Was this resolved in #1109?

Nope.

I'll get to that "soon". I was thinking to kick this to 0.21.0, not 0.20.0.

**Comment by heuermh** [comment]
That's fine.  Feel free to bump the milestone if you see fit.
