### ISSUE TITLE
Remove Gene and related models and parsing code

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#1129]
In addition to the changes proposed in #1118, remove Gene and related models and remove the parsing code in FeatureParser.

This could be added to the pull request linked above or split out into a separate pull request.

**Comment by heuermh** [comment]
Fixed by #1118

**Comment by heuermh** [comment]
@fnothaft after merging #1118 I don't see the changes from the commit in https://github.com/fnothaft/adam/pull/10.  E.g. `GeneRdd.scala`, `Features.reassignParentIds`, etc. are still there.

**Comment by fnothaft** [comment]
Oh no! I goofed there with a force push and accidentally blew fnothaft/#10 away after merging... Do you want to reopen your PR against here? If not, I can do it. Sorry about the goof!

**Comment by heuermh** [comment]
Yeah I think I can redo it against master.

**Comment by fnothaft** [comment]
Resolved by #1153, which was merged as https://github.com/bigdatagenomics/adam/commit/9eb0d60fe41dcdf99b7025d794032040fd9a8edc.
