### ISSUE TITLE
Map IntervalList format column four to feature name or attributes?

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#1152]
We are not sure if the name column should be mapped to `Feature.name` or to `Feature.attributes`.

Note discussion here
https://github.com/bigdatagenomics/adam/pull/1104/files#r77733324
https://github.com/bigdatagenomics/adam/pull/1104/files#r74367312

Ping @ryan-williams to comment.

**Comment by tdanford** [comment]
I vote: map it to `Feature.name`.  People can parse it out into attributes manually if they're abusing the name field to store key-value pairs.

**Comment by fnothaft** [comment]
Resolved by 53b8f48abe0b0536c39e155fb32de91a98c78876.
