### ISSUE TITLE
GFF3 formatted features written as single file must include gff-version pragma

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#1169]
"##gff-version 3.2.1

The GFF version follows the format of 3.#.# in this spec. This directive must be present, must be the topmost line of the file. The version number always begins with 3, the second and third numbers are optional and indicate a major revision and a minor revision respectively."

https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md

**Comment by fnothaft** [comment]
That's a nice, simple header to write.

TBH though, we could do a mapPartitionsWithIndex where we add that at the start of the first partition and then write it as text at the start of the first shard. Actually, when we write shards, we should probably put that at the start of each shard.

Does this apply for GFF2 as well?

**Comment by heuermh** [comment]
I think it only needs to be present when writing as single file.

I don't believe it applies for GFF2, only GFF3.

**Comment by fnothaft** [comment]
> I think it only needs to be present when writing as single file.

Wouldn't it make sense to add it when writing shards that aren't intended to be merged? Then each shard would be a valid GFF3.

> I don't believe it applies for GFF2, only GFF3.

SGTM!

**Comment by heuermh** [comment]
> Wouldn't it make sense to add it when writing shards that aren't intended to be merged? Then each shard would be a valid GFF3.

We don't do that for other things (IntervalList features, VCF files, BAM files, etc.), right?  I admit to only half understanding how we move headers around.

**Comment by fnothaft** [comment]
>> Wouldn't it make sense to add it when writing shards that aren't intended to be merged? Then each shard would be a valid GFF3.
>
> We don't do that for other things (IntervalList features, VCF files, BAM files, etc.), right? I admit to only half understanding how we move headers around.

We write the header on each shard for sharded SAM/BAM and VCF/BCF/BGZIP-VCF. We don't do that for IntervalList because support for even writing the header at all is pretty new. We should probably open a ticket and write it for each `IntervalList` shard.

**Comment by heuermh** [comment]
Ah I see.  In that case, yes, we should do that for IntervalList and GFF3 formats.

**Comment by fnothaft** [comment]
@heuermh can you take this for 0.23.0?

**Comment by fnothaft** [comment]
Ping @heuermh

**Comment by heuermh** [comment]
I'd say push to 0.24.0
