### ISSUE TITLE
FastqRecordConverter needs cleanup and tests

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1172]
We need to refactor `org.bdgenomics.adam.converters.FastqRecordConverter` as there's a lot of code duplication between the `AlignmentRecord` and `Fragment` code paths. Also, there apparently are no tests for this class, which is surprising!

**Comment by zyxue** [comment]
I would like to try to fix this issue, how do I get started?

**Comment by heuermh** [comment]
@zyxue unit tests would be a good place to start.   Once there is some test coverage, then start cleaning things up!

**Comment by zyxue** [comment]
Do I need spark to start the development?

**Comment by heuermh** [comment]
The maven build (and by extension, the build in IntelliJ) is self contained.  You will need Spark to run the `adam-submit` and `adam-shell` commands in the `bin` directory.

**Comment by zyxue** [comment]
Do you know why would the input be of type `(Void, Text)`, see this [line](https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/converters/FastqRecordConverter.scala#L61)? Where is `Void` from, why not just `Text`?
