### ISSUE TITLE
Split apart partition and join in ShuffleRegionJoin

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1175]
This would be useful for some stuff that I am doing: in `ShuffleRegionJoin.partitionAndJoin`, we partition and sort the input data and then we do a join. If we've already got the data sorted and want to do another join, it's unnecessary to do another sort and repartition first. We should make it optional to do that by splitting apart the two tasks.

**Comment by heuermh** [comment]
+1

**Comment by fnothaft** [comment]
This is done in #1324. For cleanliness, I am going to close this ticket in favor of #1216, which is the main shuffle join ticket.
