### ISSUE TITLE
What should our API at the command line look like?

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#1178]
With `transformFormats` in 8cec2c08f774b31dcc840acf33a83f7dd30eb0a2, we introduced a single CLI command that [helps both ways](https://www.youtube.com/watch?v=GthCIMDjUpU), in that it transforms from native formats to ADAM Parquet and vice versa.

Looking at our current list of commands, perhaps we should extend this pattern

```
adam2fasta
adam2fastq
adam2vcf
allelecount
anno2adam
count_contig_kmers
count_kmers
depth
fasta2adam
flagstat
flatten
fragments2reads
listdict
mergeShards
print
reads2coverage
reads2fragments
transform
transformFeatures
vcf2adam
view
wigfix2bed
```

Taking it to the extreme (where all the conversion operations fit under a single transform command) is going too far; I'm looking for a nice balance.

We could also take this opportunity to make sure all the commands and command line arguments are named consistently (e.g. camelCase vs. snake_case vs. whatever-you-call-it-with-dashes).

**Comment by fnothaft** [comment]
I think this has substantial overlap with #1327; I'm going to close in favor of the other ticket, as it is more actionable. @heuermh please reopen if you disagree.
