### ISSUE TITLE
Parse out common annotations stored in VCF format

### ISSUE THREAD

**Issue by arahuja** [bigdatagenomics/adam#118]
We have a few commonly distributed annotation databases stored (and publicly available) as VCF fomats. This will parse out the additional annotation specific fields for a particular format.

It will most be an addition to the VCF parsing and extending the INFO field parsing to pick up annotations specific fields.

**Comment by fnothaft** [comment]
Closed by https://github.com/bigdatagenomics/adam/pull/243.
