### ISSUE TITLE
How to get "SO coordinate" instead of "SO unsorted" ?

### ISSUE THREAD

**Issue by liamlee** [bigdatagenomics/adam#1182]
![image](https://cloud.githubusercontent.com/assets/781297/18832499/587795ec-841e-11e6-9af7-2f34e81b0cfb.png)

When I save data to sam file,I can only get "SO unsorted"  sort_tag in the result file.
Can anyone help me ?
Thx!

**Comment by heuermh** [comment]
Hello @liamlee!

Are you using release version 0.19.0 or git HEAD?  And then are you using the `transform` command, or calling `saveAsSam(...)` directly?

**Comment by liamlee** [comment]
@heuermh I compiled from master branch(scala_2.11) by myself,and I calling sortReadsByReferencePosition() to sort the record ,and then to call saveAsSam(...).

**Comment by heuermh** [comment]
Great, thank you for the clarification.  I'll look into it today!

**Comment by fnothaft** [comment]
Hi @liamlee !

To get `SO:coordinate`, you need to provide the `isSorted = true` optional parameter to `saveAsSam`.

**Comment by liamlee** [comment]
Hi @fnothaft 
I do set isSorted = true, I even tried to do this in the "convertToSam()" source code:
`val header = adamRecordConverter.createSAMHeader(sequences, recordGroups)
    if (isSorted) {
      header.setSortOrder(SAMFileHeader.SortOrder.coordinate)
    }
    **header.setSortOrder(SAMFileHeader.SortOrder.coordinate)**
`

But I still get "unsorted".

**Comment by fnothaft** [comment]
I've got a fix for this, will push in a sec.

**Comment by fnothaft** [comment]
Opened #1183 to resolve. I believe this is a bug (more so a usage issue?) in HTSJDK where some header writing paths don't properly write the sort order.

**Comment by heuermh** [comment]
#1183 worked for me and has been merged.  @liamlee can you confirm?

**Comment by liamlee** [comment]
Hi @heuermh 
It's works fine now.
Thank you very much!!!
