### ISSUE TITLE
Swapping out IntervalRDD under GenomicRDD's

### ISSUE THREAD

**Issue by akmorrow13** [bigdatagenomics/adam#1184]
Right now we can only support RDD's under the GenomicRDD wrapper. We should be able to swap this out for IntervalRDD's.

**Comment by heuermh** [comment]
Not sure what you mean.  Is this similar to #1173 or something else?

**Comment by akmorrow13** [comment]
Yes! I believe #1173 would do the trick. Should I delete this then?

**Comment by heuermh** [comment]
Sure, if you can better document your use case there.
