### ISSUE TITLE
Publish sources JAR with snapshots

### ISSUE THREAD

**Issue by ryan-williams** [bigdatagenomics/adam#1195]
It would be nice to be able to navigate around the source from within projects that are depending on `0.19.1-SNAPSHOT`.

**Comment by heuermh** [comment]
As far as I know, there isn't any way to activate a profile only for deploy, so we would need to enable building source jars all the time.  Fine with me, since we're already generating scaladocs at verify in the lifecycle, and that probably takes a lot longer than building source jars.

Or @fnothaft, do we run deploy with `-Pdistribution` from Jenkins?

**Comment by fnothaft** [comment]
We don't run the snapshot builds with `-Pdistribution`, but we should. I've changed that in Jenkins, and am [running a build](https://amplab.cs.berkeley.edu/jenkins/job/ADAM/2084/).

**Comment by heuermh** [comment]
Thanks, will see how that works.  There is perhaps some cleanup that could be done, e.g. the scala-maven-plugin configuration in the distribution profile is nearly identical to that in `<plugins>`, and if we're running scaladoc in verify we should also be running javadoc at the same phase.  I assume we do that to catch doc errors at build time?

**Comment by heuermh** [comment]
In the build logs I see the source jars being generated
```
[INFO] --- maven-source-plugin:2.4:jar-no-fork (attach-sources) @ adam-core-spark2_2.11
---
[INFO] Building jar:
/home/jenkins/workspace/ADAM/HADOOP_VERSION/2.3.0/
SCALAVER/2.11/SPARK_VERSION/2.0.0/label/centos/adam-core/
target/adam-core-spark2_2.11-0.19.1-SNAPSHOT-sources.jar
```
and I see the source jars (e.g. adam-core_2.10-0.19.1-20161005.153221-1380-sources.jar) in the Sonatype snapshot repository

https://oss.sonatype.org/content/repositories/snapshots/org/bdgenomics/adam/adam-core_2.10/0.19.1-SNAPSHOT/

**Comment by fnothaft** [comment]
Source jars are pushed: https://oss.sonatype.org/content/repositories/snapshots/org/bdgenomics/adam/adam-core_2.10/0.19.1-SNAPSHOT/adam-core_2.10-0.19.1-20161005.152049-1379-sources.jar

Closing!
