### ISSUE TITLE
Allow open-ended intervals in loadIndexedBam

### ISSUE THREAD

**Issue by ryan-williams** [bigdatagenomics/adam#1196]
Intervals' start and end has to be specified in a ReferenceRegion [before being passed to `loadIndexedBam`](https://github.com/bigdatagenomics/adam/blob/b903cfde5740186888998c2bce7e29b8ab310405/adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala#L479).

It would be nice to allow intervals of the form `[N,∞)` without resorting to making callers use `Long.MaxValue` or the like.

The right model would be a sort of `ReferenceRegion`-precursor, shaped like `(String, Long, Option[Long])`, that basically only exists ephemerally in the course of loading subsets of indexed BAMs.

Guacamole has some code that does basically this [here](https://github.com/hammerlab/guacamole/blob/master/src/main/scala/org/hammerlab/guacamole/loci/set/LociParser.scala#L57-L95), allowing open-ended intervals, whole contigs, and "all" and "none" keywords, then resolving things into concrete `ReferenceRegion`s once contig-lengths are available, after parsing a BAM header.

**Comment by heuermh** [comment]
I've suggested before using [Range](http://google.github.io/guava/releases/19.0/api/docs/com/google/common/collect/Range.html) from Guava, which handles bounded and unbounded ranges. It is well-designed and well-tested.

I abuse it for genomics here https://github.com/heuermh/dishevelled-bio/tree/master/range/src/main/java/org/dishevelled/bio/range
