### ISSUE TITLE
Sorting by reference index seems doesn't work or sorted by DESC order ?

### ISSUE THREAD

**Issue by liamlee** [bigdatagenomics/adam#1204]
I use method `sortReadsByReferencePositionAndIndex()` to sort my record and then save to sam/bam file, the results show like the pitch blow ,the order seems to be DESC ?

`val sortedRDD = alignmentRecordRDD.sortReadsByReferencePositionAndIndex()`
`val markRDD = sortedRDD.markDuplicates()`
`markRDD.saveAsSam(...)`

<img width="530" alt="qq20161011-0 2x" src="https://cloud.githubusercontent.com/assets/781297/19267247/5019c97e-8fe0-11e6-84d4-76ca95c94e86.png">

**Comment by liamlee** [comment]
Maybe I should do sort after markDuplicates()

**Comment by fnothaft** [comment]
Thanks for pinging this @liamlee! Duplicate marking will group reads by fragment, so you do need to run sort after duplicate marking.
