### ISSUE TITLE
Release script failed for 0.20.0 release

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#1211]
@jpdna @fnothaft 
```
$ ./scripts/release/release.sh 0.20.0 0.20.1-SNAPSHOT
...
Switched to a new branch 'maint_spark2_2.11-0.20.0'
./scripts/release/release.sh: line 72: ./scripts/move_to_spark2.sh: No such file or directory
```

It looks like the Spark 1.x Scala 2.10 and 2.11 releases were tagged and deployed to the Sonatype staging directory ok.

The maven release plugin doesn't let you cut a release with uncommitted changes, so I'll have to copy release.sh over to a new script to make changes there.

I'm currently on the maint_spark2_2.11-0.20.0 branch but with Spark 1.x dependencies, as the `move_to_spark_2.sh` script did not run.  I'm not sure yet what I'll need to do to fix this up and continue the release . . .
```
adam-upstream maint_spark2_2.11-0.20.0!
$ git status
On branch maint_spark2_2.11-0.20.0
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   adam-apis/pom.xml
	modified:   adam-assembly/pom.xml
	modified:   adam-cli/pom.xml
	modified:   adam-core/pom.xml
	modified:   distribution/pom.xml
	modified:   pom.xml

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	adam-0.20.0.pom
	adam-0.20.0.zip
	adam-apis/pom.xml.releaseBackup
	adam-assembly/pom.xml.releaseBackup
	adam-cli/pom.xml.releaseBackup
	adam-core/pom.xml.releaseBackup
	distribution/pom.xml.releaseBackup
	pom.xml.releaseBackup
	release.properties
```

**Comment by fnothaft** [comment]
Ah drat! The Spark 2 code is new to this release. My apologies for flubbing it; I'll PR a fix.

You could roll back the release, or just run it manually from here. Let me know if you'd like me to manually release the Spark 2 artifacts...

**Comment by heuermh** [comment]
I would like to continue manually, I just need to get the working directory in the right state first.

**Comment by heuermh** [comment]
... think I got it, release:prepare went ok, running release:perform meow . . .

**Comment by heuermh** [comment]
Artifacts are staged to **orgbdgenomics-1048**, log into https://oss.sonatype.org to verify.

**Comment by heuermh** [comment]
Signatures and distribution tarballs look ok to me.
I'll close the staging repository and enable sync to Maven Central at 6:00 pm CST unless I hear otherwise.
