### ISSUE TITLE
Release 0.20.0 artifacts failed Sonatype Nexus validation

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#1212]
The `adam-assembly` module does not produce javadoc or source jars, and as such fails the Sonatype Nexus validation step:

Event: Failed: Javadoc Validation
Friday, October 14, 2016 18:06:02 CDT (GMT-0500)
typeId	javadoc-staging
failureMessage	Missing: no javadoc jar found in folder '/org/bdgenomics/adam/adam-assembly_2.10/0.20.0'
failureMessage	Missing: no javadoc jar found in folder '/org/bdgenomics/adam/adam-assembly-spark2_2.10/0.20.0'
failureMessage	Missing: no javadoc jar found in folder '/org/bdgenomics/adam/adam-assembly-spark2_2.11/0.20.0'
failureMessage	Missing: no javadoc jar found in folder '/org/bdgenomics/adam/adam-assembly_2.11/0.20.0'

Event: Failed: Sources Validation
Friday, October 14, 2016 18:06:05 CDT (GMT-0500)
typeId	sources-staging
failureMessage	Missing: no sources jar found in folder '/org/bdgenomics/adam/adam-assembly_2.10/0.20.0'
failureMessage	Missing: no sources jar found in folder '/org/bdgenomics/adam/adam-assembly-spark2_2.10/0.20.0'
failureMessage	Missing: no sources jar found in folder '/org/bdgenomics/adam/adam-assembly-spark2_2.11/0.20.0'
failureMessage	Missing: no sources jar found in folder '/org/bdgenomics/adam/adam-assembly_2.11/0.20.0'

**Comment by heuermh** [comment]
Sent an email to ossrh-users@sonatype to see if it might be possible to deploy signed empty sources and javadoc jars to the currently open staging repository.  Otherwise I think we might be hosed and may need to move to an 0.20.1 release.

**Comment by fnothaft** [comment]
OOC, how have we been getting around this with [adam-assembly](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22adam-distribution%22)? Is the requirement only for artifacts that push JARs?

**Comment by heuermh** [comment]
The adam-distribution module has `<packaging>pom</packaging>`, while adam-assembly has `<packaging>jar</packaging>`.

From http://central.sonatype.org/pages/requirements.html#supply-javadoc-and-sources:

"Projects with packaging other than pom have to supply JAR files that contain Javadoc and sources."

I've run into this before elsewhere and the workaround is to include a dummy public class so that javadoc won't complain.  As far as I know that would require moving the release tag and re-attempting the whole release.

Sonatype does allow empty source and javadoc jars; I'm hoping to find a way to push them to the staging repository so that I can attempt another close with the artifacts already staged.

**Comment by heuermh** [comment]
#1215 should fix things for the next release cycle; still trying to figure out if there is a way to push artifacts to Maven Central based on the current release tags.

**Comment by heuermh** [comment]
Found a workaround!
https://support.sonatype.com/hc/en-us/articles/213465868-Uploading-to-a-Staging-Repository-via-REST-API

Will give it a try tomorrow.

**Comment by heuermh** [comment]
After uploading the sources and javadoc artifacts, signatures, and checksums via the REST API, the staging repository successfully closed.

**Comment by heuermh** [comment]
0.20.0 artifacts are available on Maven Central
http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.bdgenomics.adam%22

Woot!
