### ISSUE TITLE
Maintaining sorted/partitioned knowledge

### ISSUE THREAD

**Issue by devin-petersohn** [bigdatagenomics/adam#1216]
It would be beneficial if we had a way to know that a given file was sorted when it was written. As is, RDDs are force-sorted and partitioned before operations that require sorted RDDs. 

Implementing Issue #1175 is a part of this work.

**Comment by heuermh** [comment]
See also https://github.com/bigdatagenomics/adam/issues/188

**Comment by devin-petersohn** [comment]
@fnothaft Following up from our conversation this morning, the mix-in implementation is finally debugged. I am going to move toward working on splitting partition and sort.

Here is the working repo for those interested: https://github.com/devin-petersohn/adam/tree/partitioner

**Comment by jpdna** [comment]
@devin-petersohn - just want to make sure you have seen this thread: #651

**Comment by jpdna** [comment]
It may be useful to look at:
https://issues.apache.org/jira/browse/SPARK-8836
https://issues.apache.org/jira/browse/SPARK-2213

**Comment by devin-petersohn** [comment]
Resolved with #1324.
