### ISSUE TITLE
Bump Spark, Scala, Hadoop dependency versions

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#1221]
Apache Spark version 2.0.1 was released on 03 Oct 2016 and defaults to Scala version 2.11.8 and Hadoop 2.7 and later.

Apache Spark version 1.6.2 was released on 25 June 2016 and defaults to Scala version 2.10.5 and Hadoop 2.6.  When bumping the Scala version to 2.10.5 downstream I see other libraries requiring 2.10.6.

**Comment by DruidSmith** [comment]
Is ADAM working on Spark 2.0?  Has anyone looked at running ADAM atop AWS EMR?

**Comment by heuermh** [comment]
> Is ADAM working on Spark 2.0?

Yes, as of version 0.20.0, released last week.

**Comment by heuermh** [comment]
See also
https://issues.apache.org/jira/browse/SPARK-18138

**Comment by fnothaft** [comment]
Sigh! Reopening this issue. See [comment](https://github.com/bigdatagenomics/adam/pull/1256#issuecomment-259598564); TL;DR is that #1254 spuriously passed but the `move_to_spark2.sh` script is broken now on ToT. If no one else is interested, I'll hack on this in the AM.
