### ISSUE TITLE
Strand bias doesn't get exported

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1226]
Similar to #1203, Strand bias does not get properly exported on conversion back to VCF.

**Comment by heuermh** [comment]
Are you referring to VCF INFO reserved key SB?
The corresponding field was intentionally removed from `Variant` in recent changes.

**Comment by fnothaft** [comment]
Format key, not info.

**Comment by heuermh** [comment]
I see, so you're saying the fix in #1203 was only on the read side, not the write side.
