### ISSUE TITLE
Annotate classes with their production worthiness

### ISSUE THREAD

**Issue by carlyeks** [bigdatagenomics/adam#123]
Currently, this information is stored in scaladoc, or in the commit message, or is just lost, but it would be good to know the level of maturity for our interfaces.

@hammer sent out [this link](http://developer.yahoo.com/blogs/hadoop/towards-enterprise-class-compatibility-apache-hadoop-453.html) about the ways that Hadoop currently classifies their interface, we should use something similar.

We should annotate the current classes that we have, as well as document our process and ensure that future PRs adhere to this standard.

**Comment by heuermh** [comment]
Will do this as of 1.0 along with semantic versioning (#338).

**Comment by heuermh** [comment]
See recent discussion in https://github.com/apache/spark/pull/15374

**Comment by heuermh** [comment]
Closing as WontFix
