### ISSUE TITLE
how to compare with the last the column for the same chromosome name?

### ISSUE THREAD

**Issue by Fei-Guang** [bigdatagenomics/adam#1237]
`$ samtools view rdd1.bam |head -1`

<table width="3000">
  <tr>
    
     NB501244AR:119:HJY3WBGXY:3:11508:7857:8792      16      chr1    10002   0       40M     *       0       0 AACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACC        ///E////6E////EEAEEE/EEEEEEEEEEEEAEAAA/A        XT:A:R  NM:i:0  X0:i:594        XM:i:0  XO:i:0  XG:i:0  MD:Z:40 
  </tr>
</table>

`$ cat rdd2.kmer | head -10`
chr1    1       0.42235 0.01501 10001   110000
chr1    2       0.41104 0.01254 60001   160000
chr1    3       0.42826 0.00282 110001  177417  227418  260000
chr1    4       0.4151  0.00288 160001  177417  227418  267719  317720  360000
chr1    5       0.39534 0.00166 260001  267719  317720  410000
chr1    6       0.42745 0.0008  360001  460000
chr1    7       0.47991 0.0041  410001  471368  521369  560000
chr1    8       0.44    0.00977 460001  471368  521369  610000
chr1    9       0.39048 0.00875 560001  660000
chr1    10      0.42579 0.00624 610001  710000

what i want to do is to  compare the 4th column of rdd1.bam with the 5th column and last column of rdd2.kmer if both rdd has the same chromosome name(The third column of rdd1 should be same as the first column of rdd2)

`if the 4th column of rdd1.bam  in range   [the 5th column of rdd2.kmer, the last column of rdd2.kmer]`
`the count[chr1] ++`

how can i do it with adam0.20?

**Comment by fnothaft** [comment]
Hi @Fei-Guang! How do you know which line of the second file (rdd2.kmer) corresponds to which read? If the first read in rdd1.bam  should line up with the first line of rdd2.kmer, I'd do:

```
import org.bdgenomics.adam.rdd.ADAMContext._
val reads = sc.loadAlignments("rdd1.bam")
val lines = sc.textFile("rdd2.kmer")

// conceptually, we could just do reads.rdd.zip(lines), but!
// we aren't guaranteed that both RDDs have the same number
// of records in each partition, so zipWithIndex followed by join
// is (slower, but) safer
val zippedLinesAndReads = reads.rdd
  .zipWithIndex
  .map(_.swap)
  .join(lines.zipWithIndex.map(_.swap))

val countsByChromosome = zippedLinesAndReads.flatMap(kv => {
  val (_, (read, line)) = kv

  // get the range from the rdd2.kmer file
  val columns = line.split("\t[") // i assume this is tab delimited?
  val start = columns(4).toLong
  val end = columns(5).toLong

  // is the alignment start position between the start and end pos from the line?
  // if yes, emit the chromosome name and 1
  if (start <= read.getStart && read.getStart < end) {
    Some((read.getContigName, 1))
  } else {
    None
  }
}).reduceByKeyLocally(_ + _)
```

**Comment by fnothaft** [comment]
What's the format of the `rdd2.kmer` file? If it is a typical feature format (e.g., BED, GTF), this code would be slightly cleaner.

**Comment by Fei-Guang** [comment]
hello, @fnothaft

Both rdd should have the same chromosome#, it means
The third column of rdd1 should be same as the first column of rdd2.

take the first line of rdd1 as an example, the  chromosome# is chr1.

Many thanks for the help

**Comment by Fei-Guang** [comment]
hello @fnothaft 

the format of the rdd2.kmer is defined by our engineer,  not in  BED and GTF format

**Comment by Fei-Guang** [comment]
i run the code you provided it reports the following error:
MY ENV:
spark-2.0.1-bin-hadoop2.6
adam-distribution-spark2_2.11-0.20.0
scala-2.11.8


java.io.NotSerializableException: org.bdgenomics.formats.avro.AlignmentRecord
Serialization stack:
	- object not serializable (class: org.bdgenomics.formats.avro.AlignmentRecord, value: {"readInFragment": 0, "contigName": "chr10", "start": 61758687, "oldPosition": null, "end": 61758727, "mapq": 25, "readName": "NB501244AR:119:HJY3WBGXY:2:11112:6137:19359", "sequence": "AAAATACTGAGACTTATCAGAATTTCAGGCTAAAGCAACC", "qual": "AAAAAAEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEE", "cigar": "40M", "oldCigar": null, "basesTrimmedFromStart": 0, "basesTrimmedFromEnd": 0, "readPaired": false, "properPair": false, "readMapped": true, "mateMapped": false, "failedVendorQualityChecks": false, "duplicateRead": false, "readNegativeStrand": false, "mateNegativeStrand": false, "primaryAlignment": true, "secondaryAlignment": false, "supplementaryAlignment": false, "mismatchingPositions": "40", "origQual": null, "attributes": "XT:A:U\tXO:i:0\tXM:i:0\tNM:i:0\tXG:i:0\tX1:i:0\tX0:i:1", "recordGroupName": null, "recordGroupSample": null, "mateAlignmentStart": null, "mateAlignmentEnd": null, "mateContigName": null, "inferredInsertSize": null})
	at org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:40)
	at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:46)
	at org.apache.spark.serializer.SerializationStream.writeValue(Serializer.scala:135)
	at org.apache.spark.storage.DiskBlockObjectWriter.write(DiskBlockObjectWriter.scala:185)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:150)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:79)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:47)
	at org.apache.spark.scheduler.Task.run(Task.scala:86)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2016-11-04 10:30:56 ERROR TaskSetManager:70 - Task 0.0 in stage 2.0 (TID 9) had a not serializable result: org.bdgenomics.formats.avro.AlignmentRecord
Serialization stack:
	- object not serializable (class: org.bdgenomics.formats.avro.AlignmentRecord, value: {"readInFragment": 0, "contigName": "chr1", "start": 10001, "oldPosition": null, "end": 10041, "mapq": 0, "readName": "NB501244AR:119:HJY3WBGXY:3:11508:7857:8792", "sequence": "AACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACC", "qual": "///E////6E////EEAEEE/EEEEEEEEEEEEAEAAA/A", "cigar": "40M", "oldCigar": null, "basesTrimmedFromStart": 0, "basesTrimmedFromEnd": 0, "readPaired": false, "properPair": false, "readMapped": true, "mateMapped": false, "failedVendorQualityChecks": false, "duplicateRead": false, "readNegativeStrand": true, "mateNegativeStrand": false, "primaryAlignment": true, "secondaryAlignment": false, "supplementaryAlignment": false, "mismatchingPositions": "40", "origQual": null, "attributes": "XT:A:R\tXO:i:0\tXM:i:0\tNM:i:0\tXG:i:0\tX0:i:594", "recordGroupName": null, "recordGroupSample": null, "mateAlignmentStart": null, "mateAlignmentEnd": null, "mateContigName": null, "inferredInsertSize": null}); not retrying
2016-11-04 10:30:56 ERROR TaskSetManager:70 - Task 4.0 in stage 2.0 (TID 13) had a not serializable result: org.bdgenomics.formats.avro.AlignmentRecord
Serialization stack:
	- object not serializable (class: org.bdgenomics.formats.avro.AlignmentRecord, value: {"readInFragment": 0, "contigName": "chr10", "start": 61758687, "oldPosition": null, "end": 61758727, "mapq": 25, "readName": "NB501244AR:119:HJY3WBGXY:2:11112:6137:19359", "sequence": "AAAATACTGAGACTTATCAGAATTTCAGGCTAAAGCAACC", "qual": "AAAAAAEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEE", "cigar": "40M", "oldCigar": null, "basesTrimmedFromStart": 0, "basesTrimmedFromEnd": 0, "readPaired": false, "properPair": false, "readMapped": true, "mateMapped": false, "failedVendorQualityChecks": false, "duplicateRead": false, "readNegativeStrand": false, "mateNegativeStrand": false, "primaryAlignment": true, "secondaryAlignment": false, "supplementaryAlignment": false, "mismatchingPositions": "40", "origQual": null, "attributes": "XT:A:U\tXO:i:0\tXM:i:0\tNM:i:0\tXG:i:0\tX1:i:0\tX0:i:1", "recordGroupName": null, "recordGroupSample": null, "mateAlignmentStart": null, "mateAlignmentEnd": null, "mateContigName": null, "inferredInsertSize": null}); not retrying
2016-11-04 10:30:56 ERROR TaskSetManager:70 - Task 3.0 in stage 2.0 (TID 12) had a not serializable result: org.bdgenomics.formats.avro.AlignmentRecord
Serialization stack:
	- object not serializable (class: org.bdgenomics.formats.avro.AlignmentRecord, value: {"readInFragment": 0, "contigName": "chr7", "start": 68163823, "oldPosition": null, "end": 68163863, "mapq": 0, "readName": "NB501244AR:119:HJY3WBGXY:4:21602:16293:18064", "sequence": "TGTGAGGGTGTTGCCCAAAAGAGATTAACATTTGAGTCAG", "qual": "AAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE", "cigar": "40M", "oldCigar": null, "basesTrimmedFromStart": 0, "basesTrimmedFromEnd": 0, "readPaired": false, "properPair": false, "readMapped": true, "mateMapped": false, "failedVendorQualityChecks": false, "duplicateRead": false, "readNegativeStrand": false, "mateNegativeStrand": false, "primaryAlignment": true, "secondaryAlignment": false, "supplementaryAlignment": false, "mismatchingPositions": "40", "origQual": null, "attributes": "XT:A:R\tXO:i:0\tXM:i:0\tNM:i:0\tXG:i:0\tXA:Z:chr3,-84617448,40M,0;\tX1:i:0\tX0:i:2", "recordGroupName": null, "recordGroupSample": null, "mateAlignmentStart": null, "mateAlignmentEnd": null, "mateContigName": null, "inferredInsertSize": null}); not retrying
2016-11-04 10:30:56 ERROR TaskSetManager:70 - Task 2.0 in stage 2.0 (TID 11) had a not serializable result: org.bdgenomics.formats.avro.AlignmentRecord
Serialization stack:
	- object not serializable (class: org.bdgenomics.formats.avro.AlignmentRecord, value: {"readInFragment": 0, "contigName": "chr4", "start": 181076278, "oldPosition": null, "end": 181076318, "mapq": 25, "readName": "NB501244AR:119:HJY3WBGXY:2:23302:26459:8305", "sequence": "CACTGTGTTTTACTTCTATTTTAAAAAACCTGAAGGCTAT", "qual": "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAAAAA", "cigar": "40M", "oldCigar": null, "basesTrimmedFromStart": 0, "basesTrimmedFromEnd": 0, "readPaired": false, "properPair": false, "readMapped": true, "mateMapped": false, "failedVendorQualityChecks": false, "duplicateRead": false, "readNegativeStrand": true, "mateNegativeStrand": false, "primaryAlignment": true, "secondaryAlignment": false, "supplementaryAlignment": false, "mismatchingPositions": "40", "origQual": null, "attributes": "XT:A:U\tXO:i:0\tXM:i:0\tNM:i:0\tXG:i:0\tX1:i:0\tX0:i:1", "recordGroupName": null, "recordGroupSample": null, "mateAlignmentStart": null, "mateAlignmentEnd": null, "mateContigName": null, "inferredInsertSize": null}); not retrying

Process finished with exit code 1

**Comment by fnothaft** [comment]
Hi @Fei-Guang! Where are you running that? Are you running that in `spark-shell`? ADAM relies on a [custom Kryo serializer Registrator](https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/serialization/ADAMKryoRegistrator.scala) for serialization. If you use [./bin/adam-shell](https://github.com/bigdatagenomics/adam/blob/master/bin/adam-shell), this starts a Spark shell where the serialization config (and classpath) are set up.

**Comment by Fei-Guang** [comment]
hello @fnothaft

what should be changed in the code  if  the line of the second file (rdd2.kmer) corresponds the line of the rdd1.bam by the  chromosome name?

**Comment by fnothaft** [comment]
@Fei-Guang I think you'd want:

```
import org.bdgenomics.adam.rdd.ADAMContext._
val reads = sc.loadAlignments("rdd1.bam")
val lines = sc.textFile("rdd2.kmer")
  .map(line => {
  // get the range from the rdd2.kmer file
  val columns = line.split("\t[") // i assume this is tab delimited?
  val contig = columns(0)
  val start = columns(4).toLong
  val end = columns(5).toLong

  (contig, (start, end))
})

// join against the other RDD keyed by contig name
val zippedLinesAndReads = reads.rdd.flatMap(read => {
  // check whether the read is mapped, lest we get a null pointer exception
  if (read.getReadMapped) {
    Some((read.getContigName, read.getStart))
  } else {
    None
  }
}).join(lines)

val countsByChromosome = zippedLinesAndReads.flatMap(kv => {
  val (contigName, (readStart, (start, end))) = kv

  // is the alignment start position between the start and end pos from the line?
  // if yes, emit the chromosome name and 1
  if (start <= readStart && readStart < end) {
    Some((contigName, 1))
  } else {
    None
  }
}).reduceByKeyLocally(_ + _)
```
