### ISSUE TITLE
Assembly jar doesn't get rebuilt on CLI changes

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1238]
At least, this is what I'm seeing locally. I'm not exactly sure why this is, but it appears that the CLI jar gets rebuilt, but the shaded uberjar doesn't. @heuermh I've assigned this to you, because I think you're the best person to take this on.

**Comment by heuermh** [comment]
I'm not able to replicate this.

Making a change to `ADAMMain.scala` changes the file size of the uberjar
```
$ mvn install
$ ls -ls /Users/heuermh/.m2/repository/org/bdgenomics/adam/adam-assembly_2.10/0.20.1-SNAPSHOT/adam-assembly_2.10-0.20.1-SNAPSHOT.jar
42332825 Nov  4 06:12 adam-assembly_2.10-0.20.1-SNAPSHOT.jar

// make change, then
$ mvn install
$ ls -ls /Users/heuermh/.m2/repository/org/bdgenomics/adam/adam-assembly_2.10/0.20.1-SNAPSHOT/adam-assembly_2.10-0.20.1-SNAPSHOT.jar
42332833 Nov  4 06:20 adam-assembly_2.10-0.20.1-SNAPSHOT.jar
``

**Comment by fnothaft** [comment]
I will close this for now and reopen if I have this repro.
