### ISSUE TITLE
java.io.FileNotFoundException for old  adam file after upgrade to adam0.20

### ISSUE THREAD

**Issue by Fei-Guang** [bigdatagenomics/adam#1241]
i have created adam file with old version adam-submit 0.16,

     $docker run -v `pwd`:/data -e SPARK_PRINT_LAUNCH_COMMAND=1 -it heuermh/adam adam-submit count_kmers /tmp/small.adam /tmp/kmers.adam 10
Using ADAM_MAIN=org.bdgenomics.adam.cli.ADAMMain
Using SPARK_SUBMIT=/home/linuxbrew/.linuxbrew/bin/spark-submit
Spark Command: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -cp /home/linuxbrew/.linuxbrew/Cellar/apache-spark/2.0.1/libexec/conf/:/home/linuxbrew/.linuxbrew/Cellar/apache-spark/2.0.1/libexec/jars/* -Xmx1g org.apache.spark.deploy.SparkSubmit --conf spark.kryo.registrator=org.bdgenomics.adam.serialization.ADAMKryoRegistrator --conf spark.serializer=org.apache.spark.serializer.KryoSerializer --class org.bdgenomics.adam.cli.ADAMMain /home/linuxbrew/.linuxbrew/Cellar/adam/0.20.0/libexec/repo/adam_2.11-0.20.0.jar

 it will report java.io.FileNotFoundException for  /tmp/small.adam.

i delete the /tmp/small.adam then recreate it with new version adam-submit0.20 , it runs ok

**Comment by heuermh** [comment]
Until we hit ADAM version 1.0 and start maintaining binary compatibility, bdg-formats schema are allowed to change between versions.  Thus an ADAM file written from version 0.16.0 will not necessarily work on version 0.20.0.

As far as the `FileNotFoundException`, I don't have quite enough here to reproduce.

**Comment by fnothaft** [comment]
Hi @Fei-Guang! In your docker command, you don't have a `/tmp` volume mounted. You just have `-v pwd:/data`. Perhaps is the file under `/data` instead of `/tmp`?
