### ISSUE TITLE
Dead-ish code cleanup in `org.bdgenomics.adam.utils`

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1242]
- [ ] [MapTools](https://github.com/bigdatagenomics/adam/blob/ca4d9649bac2523f9951c24f2e184a1b37f9ba06/adam-core/src/main/scala/org/bdgenomics/adam/util/MapTools.scala) is imported in one class, but unused
- [ ] [RegExp](https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/util/RegExp.scala) is used in one class but should be removed
- [ ] [IntervalListReader](https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/util/IntervalListReader.scala) is unused
- [ ] [ImplicitJavaConversions](https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/util/ImplicitJavaConversions.scala) is imported in four classes but should be removed
- [ ] [Util](https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/util/Util.scala) is used in one place but should be removed

**Comment by heuermh** [comment]
+1
