### ISSUE TITLE
Does the nested record Flattener drop Maps/Arrays?

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1244]
I saw this when doing a cleanup pass over `org.bdgenomics.adam.util`. Specifically, look at the following lines:

* https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/util/Flattener.scala#L62-L65
* https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/util/Flattener.scala#L129-132

This is somewhat problematic as some of our nested schemas (specifically, Genotype) use Array fields, and many use Maps.

CC @tomwhite. Do you know if this code is still in use? If not, it might make more sense to drop the code instead of patching the code. I think we were using it in Eggo to flatten schemas for Hive/Impala/Spark SQL before those tools supported nested schemas, but I think those tools all support nested schemas now.

**Comment by fnothaft** [comment]
Ping @tomwhite @laserson for comment.

**Comment by brianpburns** [comment]
Any update on this? It looks like you made a commit removing some of the code, but the utility is still present at the path you reference in the first message for the issue.
