### ISSUE TITLE
ADAM minor release to support htsjdk 2.7.0?

### ISSUE THREAD

**Issue by lbergelson** [bigdatagenomics/adam#1248]
[GATK4](github.com/broadinstitute/gatk) depends on ADAM, this allows us to support reading from ADAM datafiles.  We've recently run into an issue where htsjdk 2.7.0 removed some deprecated classes that ADAM was using.  Would be possible to do a minor release of ADAM that incorporates the [patch that removes those classes](https://github.com/bigdatagenomics/adam/commit/8181c49883e0a7b88a01da5f39eac7dc77201fc8)? 

I don't know what the release process is like, so if it's a pain to do a minor release we can work around it by either publishing our own snapshot or temporarily disabling support until the next full release.

**Comment by fnothaft** [comment]
Hi @lbergelson! We are planning to do our next major release towards the end of this month, but if that timeline would be a bit long for you, we could probably push a point release out. Would end of November be OK for you, or do you need something sooner? Let us know!

**Comment by lbergelson** [comment]
Hi @fnothaft, thanks for the response.  A December release is sooner than I had expected.  I think it could work for us.  

An end of November point release would be better though. We're going to be doing our own release hopefully in December and we'd like to not be relying on any self hosted sketchy snapshot releases then.

If it's a hassle though we can wait until December.

**Comment by fnothaft** [comment]
I think we'd be targeting the last week of November, or possibly the week of Thanksgiving. CC @heuermh for comment.

**Comment by heuermh** [comment]
The current milestone date for 0.21.0 is Nov 15th.  See https://github.com/bigdatagenomics/adam/issues/1088

**Comment by lbergelson** [comment]
Ack, somehow I misread end of the month as end of **next** month end of this month would be great.  Sorry for the confusion.

**Comment by fnothaft** [comment]
No problem! I'm going to close this ticket as we're tracking the November 15th release target on #1088, but please ping us on either of the tickets if you have questions @lbergelson!
