### ISSUE TITLE
Removing ProgramRecords info when saving data to sam/bam?

### ISSUE THREAD

**Issue by liamlee** [bigdatagenomics/adam#1257]
Hi,

Before ADAM,I got PG info in the sam file:
![image](https://cloud.githubusercontent.com/assets/781297/20171164/66f1ab3e-a76a-11e6-9121-3376ddd116aa.png)

After ADAM, the output sam/bam file lost the PG info
![image](https://cloud.githubusercontent.com/assets/781297/20171244/be1b9c8a-a76a-11e6-9c4f-17fa80d47d7b.png)

**Comment by fnothaft** [comment]
Agreed, this is something we are missing. I've opened https://github.com/bigdatagenomics/bdg-formats/issues/114 as we'll need an upstream schema addition. I think this implementation will be similar to #1233.

**Comment by fnothaft** [comment]
I don't think this will make the upcoming 0.21.0 release, but we'll pick this up in 0.22.0.

**Comment by heuermh** [comment]
+1

**Comment by liamlee** [comment]
Looking forward to this .
