### ISSUE TITLE
Add more ANN field parsing unit tests

### ISSUE THREAD

**Issue by jpdna** [bigdatagenomics/adam#1273]

**Comment by heuermh** [comment]
Sorry, looks like we're clobbering each other setting the milestone!

**Comment by heuermh** [comment]
There is a lot of unit test coverage for the converter in
https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/test/scala/org/bdgenomics/adam/converters/TranscriptEffectConverterSuite.scala

Feel free to borrow from it as necessary.

**Comment by jpdna** [comment]
No, seems fine to me.

**Comment by heuermh** [comment]
Fixed by #1288
