### ISSUE TITLE
GenomicRDD.pipe may hang on failure error codes

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#1282]
See https://github.com/bigdatagenomics/adam/pull/1276, in particular test failures at
https://amplab.cs.berkeley.edu/jenkins//job/ADAM-prb/1617/

**Comment by fnothaft** [comment]
Closing as we weren't able to reproduce this in unit tests (see #1292) and the bug hasn't shown up IRL since. @heuermh please reopen if needed.
