### ISSUE TITLE
Improve test coverage for SAMRecord<->AlignmentRecord

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1284]
Similar to #1107, but for SAMRecord<->AlignmentRecord. Ideally, we should have 100% test coverage for each. What I'd propose is not just adding more tests, but a rewrite of the conversion code. What I'm doing in #1107 (PR coming tomorrow or Monday) is actually rewriting the VariantContextConverter Genotype code to be pretty close to purely functional. There are hairy nits to this, but it makes the code pretty clean, and it makes writing good tests trivial.

**Comment by heuermh** [comment]
Closing as WontFix.  I don't want to re-write the alignment conversion code to be functional, and there already is another implementation in bdg-convert.
