### ISSUE TITLE
how to submit my own driver class via adam-submit?

### ISSUE THREAD

**Issue by Fei-Guang** [bigdatagenomics/adam#1289]
i just created a driver as the following:
```

// scalastyle:off println
package com.ano.adam

import org.apache.spark.sql.SparkSession
import org.bdgenomics.adam.rdd.ADAMContext._


/** Count kmer in the specified format */
object AnnoSp {
  def main(args: Array[String]) {
    val spark = SparkSession.builder
      .config("spark.kryo.registrator", "org.bdgenomics.adam.serialization.ADAMKryoRegistrator")
      .config("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
      .config("spark.submit.deployMode", "client")

      //.config("spark.yarn.jars", "")
      .master("local[*]")
```
and packed it use 
`jar cvf mydriver1.jar -C classes .\com\ano\adam`

how to submit mydriver1.jar to spark via adam-submit?

**Comment by heuermh** [comment]
Hello @Fei-Guang, there is a full example in this style at https://github.com/heuermh/adam-examples.

Copy from the build there to configure maven-shade-plugin to create a fat jar and then submit via `spark-submit`, e.g.
```bash
$ spark-submit \
  --master ... \
  --class com.ano.adam.AnnoSp \
  target/annosp.jar
```

**Comment by Fei-Guang** [comment]
yes, i know how to submit it in a fat jar. and this is not submitted via adam-submit, but spark-submit instead.

**Comment by heuermh** [comment]
Sorry, I'm not sure exactly what you are saying.

If you want to do it the other way, then you can implement `Command`, provide your own main that delegates to `ADAMMain`, and use `adam-submit`
```bash
$ ADAM_MAIN=com.ano.adam.AnnoSpMain \
  adam-submit \
  --jars target/annosp.jar \
  --
```
Full example in this style at https://github.com/heuermh/adam-commands

**Comment by Fei-Guang** [comment]
that's what i want , many thanks
