### ISSUE TITLE
private ADAMContext constructor?

### ISSUE THREAD

**Issue by ryan-williams** [bigdatagenomics/adam#1296]
I'm upgrading from `0.20.0` to something closer to head, and I see that 480c1f47da82774d68d10ebc9d0b26d431a53f75 made the `ADAMContext` ctor private, so I am changing several call-sites from:

```scala
val adamContext = new ADAMContext(sc)
```

to

```scala
val adamContext: ADAMContext = sc
```

Any good reasons for the ctor itself to be `private`?

**Comment by heuermh** [comment]
I've also noticed this in some `adam-shell` examples in docs
