### ISSUE TITLE
Support for read alignment and variant calling in Adam? (e.g. BWA + Freebayes)

### ISSUE THREAD

**Issue by NeillGibson** [bigdatagenomics/adam#1311]
Hi, 

Are you planning to support read alignment and variant calling in Adam? For example with BWA and Freebayes?

As far as I know most development work in Adam is focused on:
- porting genomics data formats(FASTQ,BAM,VCF,BED) to HDFS+MapReduce friendly formats
- developing BAM post processing tools like MarkDuplicates, RealignIndels and BQSR. 

And that the focus is not on not developing new software for read alignment or variant calling. 
I did see that work was done on adding pipes for stream FASTQ, BAM and VCF to legacy tools. 
https://github.com/bigdatagenomics/adam/issues/1112

Are you planning to support / test / develop read alignment + variant calling pipelines on Spark + Adam that make use of external read aligners / variant callers + your own data formats + bam post processing tools? 

For Spark + Adam to be a real alternative to a normal HPC cluster for genomics data analysis read alignment + variant calling support is essential. 

Thank you.

**Comment by waltermblair** [comment]
Check out [CS-BWAMEM](https://github.com/ytchen0323/cloud-scale-bwamem), it needs some updating but is an implementation of bwa via spark/adam.

**Comment by fnothaft** [comment]
+1 @waltermblair. I've got a WIP update PR at https://github.com/ytchen0323/cloud-scale-bwamem/pull/9

**Comment by tumulurig3** [comment]
Will this be integrated with the ADAM project itself? Alignment with BWA is the critical missing link in ADAM.

**Comment by heuermh** [comment]
> Will this be integrated with the ADAM project itself?

Long term perhaps the [cloud-scale-bwamem](https://github.com/ytchen0323/cloud-scale-bwamem) repository may migrate under the [bigdatagenomics](https://github.com/bigdatagenomics) organization, to facilitate support and tighter integration with ADAM release cycles.  It is not likely the code with be migrated into the [adam](https://github.com/bigdatagenomics/adam) repository though, as most applications are developed as separate repositories.

Note there are a few other options to integrating BWA and ADAM:

#### BWA with ADAM on Apache Spark using workflow engine

BWA and ADAM can be run as part of the same pipeline, as is demonstrated here, with [Toil](https://github.com/BD2KGenomics/toil) as the workflow engine and Docker as the container technology:

https://github.com/BD2KGenomics/toil-scripts/blob/master/src/toil_scripts/adam_gatk_pipeline/align_and_call.py

Docker images for this pipeline are developed in the [cgl-docker-lib](https://github.com/BD2KGenomics/cgl-docker-lib) repository and hosted on [quay.io](https://quay.io/organization/ucsc_cgl).

#### ADAM on Apache Spark with BWA using ADAM Pipe API

An alternative execution model is being developed in the [cannoli](https://github.com/heuermh/cannoli) repository, where the data are partitioned using Apache Spark and ADAM and then streamed over pipes to an external BWA process on each compute node.

This takes advantage of the [ADAM Pipe API](https://github.com/bigdatagenomics/adam/blob/master/docs/source/60_building_apps.md#using-adams-pipe-api-pipes), which in turn builds on Apache Spark's `RDD.pipe` API.

#### Reimplement BWA algorithm on ADAM on Apache Spark

Another option would be to reimplement the BWA algorithm in Scala on ADAM on Apache Spark.  We currently have no plans to do this.  If someone is interested and willing however, ... :)

**Comment by fnothaft** [comment]
In addition to calling the native BWA code, CS-bwamem has a Scala implementation of several of the core BWA algos.

**Comment by NeillGibson** [comment]
Thank you @fnothaft  and @heuermh for this information on how to run BWA and Adam together on a Spark cluster. 

I look forward to trying one or more of these options later this year to run a read alignment(bwa) and variant calling pipeline(freebayes/gatk) on a Spark cluster. I see that GATK is supported downstream and that also a Freebayes wrapper is being developer in the canoli repository.

**Comment by heuermh** [comment]
Thank you @NeillGibson for asking good questions!  Ping us when you're ready to give things a go, maybe the story will be clearer by then.

Meanwhile, if you might be interested, we host a weekly video call for our team and collaborators.  Email my username at berkeley.edu for details.

**Comment by fnothaft** [comment]
Closing as the alignment steps are downstream in Cannoli (e.g., [bwa](https://github.com/bigdatagenomics/cannoli/blob/master/src/main/scala/org/bdgenomics/cannoli/Bwa.scala)) and variant calling is in [Avocado](https://github.com/bigdatagenomics/avocado/).

**Comment by caspase8** [comment]
How can I implement Cannoli in ADAM, please help.
