### ISSUE TITLE
Support for gVCF merging and genotyping (e.g. CombineGVCFs and GenotypeGVCFs)

### ISSUE THREAD

**Issue by NeillGibson** [bigdatagenomics/adam#1312]
Hi, 

Are you planning to support gVCF merging and genotyping on Spark / Adam?

As far as I know the only way to variant call 100K samples is trough creating gVCF files per sample and subsequent gVCF merging and genotyping. 

The most well known / production ready implementation of this is from the Broad in GATK:

**CombineGVCFs**
https://software.broadinstitute.org/gatk/gatkdocs/org_broadinstitute_gatk_tools_walkers_variantutils_CombineGVCFs.php

**GenotypeGVCFs**
https://software.broadinstitute.org/gatk/gatkdocs/org_broadinstitute_gatk_tools_walkers_variantutils_GenotypeGVCFs.php

For variant calling of the the 100K+ samples in Exac/GnomAD the first merge step was replaced with GenomicsDB from intel. As I understand it GenomicsDB efficiently stores per sample gVCF tracks and can then efficiently stream merged VCF into GenotypeGVCFs

**Broad/Intel GenomicsDB**
https://github.com/Intel-HLS/GenomicsDB
https://vimeo.com/194823486/506da42daf (from minute 19)

Genomics DB is based on Intel TileDB
http://istc-bigdata.org/tiledb/index.html

Something similar to CombineGVCFs/GenotypeGVCFs/GenomicsDB is being developed by DNAnexus that also supports on demand joint genotyping from Freebayes gVCF:

GLnexus
https://github.com/dnanexus-rnd/GLnexus

Are you also planning scalable gVCF storage and on demand gVCF merge and joint genotyping on top of Spark / Adam?

Thank you.

**Comment by ggittu** [comment]
@heuermh @fnothaft Is there any document that says how to use CombineGVCFs and GenotypeGVCFs in ADAM (spark way)?

**Comment by heuermh** [comment]
Is this helpful?

https://bdg-avocado.readthedocs.io/en/latest/workflows/joint.html

**Comment by ggittu** [comment]
@heuermh Got it. So i will run something like 

avocado-submit jointer -from_gvcf /vcf/*.gvcf /output

Here I think the jointer is for CombineGVCFs , what is the one I can use for GenotypeGVCFs?
