### ISSUE TITLE
Repository for Pipe API wrappers for bioinformatics tools

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#1314]
Thinking about #1313, and also some experiments with the Pipe API https://github.com/heuermh/adam-snpeff and https://github.com/heuermh/adam-dishevelled-bio, I wonder if we should create a new Maven module or new repository for Pipe API wrappers for bioinformatics tools.  Such could be popular with external collaborators. A flag for using local binaries vs. call via docker would be useful.

**Comment by fnothaft** [comment]
+1. I had been thinking "cannoli" would be a good name for this, as cannoli means "little pipe".

**Comment by heuermh** [comment]
of course, the name is the only hard part

**Comment by fnothaft** [comment]
> of course, the name is the only hard part

You ever see the animated Dilbert show? IIRC, they had an entire episode about that.

**Comment by heuermh** [comment]
Proposal here
https://github.com/heuermh/cannoli

To extend the example to a real tool, imagine Args4J options matching all the tool command line options, those would then populate the string command before calling `pipe(string)`.

I think though that the cannoli API should be more narrow than `BDGSparkCommand`.  The reading and writing from the filesystem in the example probably doesn't need to be there.

**Comment by heuermh** [comment]
See https://github.com/bigdatagenomics/cannoli
