### ISSUE TITLE
FeatureRDD instantiation tries to cache the RDD

### ISSUE THREAD

**Issue by laserson** [bigdatagenomics/adam#1321]
Currently, when you create a `FeatureRDD` via, say, `sc.loadBed()`, the `apply` function tries to cache the RDD bc it first computes a `SequenceDictionary` off of it:

https://github.com/bigdatagenomics/adam/blob/47fa49cb8904f770307a22ed0dffcbd21c9c6b06/adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/FeatureRDD.scala#L95

I am working on my laptop on a 120 GB bed dataset and this is not gonna end well.  This feels unexpected...is it necessary?  Perhaps allow the user to specify the storage level?  Thoughts?

**Comment by laserson** [comment]
To be fair, I'm in the middle of this computation, and I suppose Spark may deal with this issue gracefully.  Will update soon.

**Comment by heuermh** [comment]
That's a fairly large BED file, are you doing wheat genomics now?  Hope you have 1 TB RAM on that laptop.  :)

**Comment by heuermh** [comment]
@laserson still curious as to the use case here.

Note that https://github.com/bigdatagenomics/adam/pull/1411 modifies how the `SequenceDictionary` is created for BED, GFF3, GTF, and NarrowPeak formats, and that may have performance implications.

**Comment by fnothaft** [comment]
I mean, in general, I think @laserson is correct here; we shouldn't cache unless we provide an option to control how we cache (a la `Transform`). It's a simple patch.

**Comment by heuermh** [comment]
> provide an option

+1

**Comment by laserson** [comment]
I guess this is a bit hacky, but I was loading the phylop data set which is a wigfix file with a float value at every genome position. I converted it to bed for loading with adam.

**Comment by fnothaft** [comment]
Oh, that makes a fair bit of sense now.

**Comment by heuermh** [comment]
To push down a cache flag to the `apply` method, we'd have to add it to all the `loadXxx` feature methods, is that worth it? 

`Transform` works differently, in that the `-cache` flag calls `rdd.persist` explicitly [Transform.scala#L171](https://github.com/bigdatagenomics/adam/blob/master/adam-cli/src/main/scala/org/bdgenomics/adam/cli/Transform.scala#L171).

**Comment by fnothaft** [comment]
> To push down a cache flag to the apply method, we'd have to add it to all the loadXxx feature methods, is that worth it?

I would be fine with us adding that.

**Comment by laserson** [comment]
Does that flag make sense for the other `loadXXX` methods?

**Comment by heuermh** [comment]
@laserson see also #1447.  `transformFeatures` CLI command now has `-cache` and `-storage_level` arguments.

> Does that flag make sense for the other `loadXXX` methods?

Possibly.  This case is a bit unique in that`persist` is called when constructing the RDD, instead of other places where `persist` might be called in-between transform steps.
