### ISSUE TITLE
Bump Spark 2 build to Spark 2.1.0

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1330]

**Comment by heuermh** [comment]
ok to push this off until 0.22.0?  We should do a deep dive into the transitive dependency changes between 1.x and 2.1.x and make sure we're not introducing any conflicts.  E.g., I seem to recall there is/was a Kryo inconsistency recently.

**Comment by fnothaft** [comment]
@heuermh I'm OK with pushing off to 0.22.0 if you'd like. That being said, this change is just to the Spark 2 build, not to the default (Spark 1) build, which remains pegged to 1.6.2. Not sure if that changes your opinion.
