### ISSUE TITLE
Version 0.21.0: VariantContextConverter fails for 1000G VCF data

### ISSUE THREAD

**Issue by akmorrow13** [bigdatagenomics/adam#1353]
I am testing on chr1 and chr20, found here: ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/

<img width="1151" alt="screen shot 2017-01-17 at 4 39 07 pm" src="https://cloud.githubusercontent.com/assets/6503416/22046182/be536414-dcd3-11e6-9a29-c2f19516d6dc.png">

**Comment by fnothaft** [comment]
Does this repro with ToT/#1346 and #1348 merged in? The stack traces look similar...

**Comment by akmorrow13** [comment]
Yep this was fixed in the 21.1-SNAPSHOT. Thanks!
