### ISSUE TITLE
Increase visibility for ADAMContext.sc and/or getFs... methods

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#1356]
The Hadoop configuration from the SparkContext associated with an ADAMContext needs to be accessible for subclasses to access the FileSystem
```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] .../org/dishevelled/bio/adam/BiojavaAdamContext.java:[136,52]
  sc has private access in org.bdgenomics.adam.rdd.ADAMContext
```

Alternately, we could increase the visibility of the `getFs...` methods from `private[rdd]` to `protected`.

**Comment by fnothaft** [comment]
Ah, I hadn't thought of the Java access patterns here. I think we should just make the `sc` field of `ADAMContext` public again.

**Comment by heuermh** [comment]
The workaround is not so bad, I wrap sc in the constructor into a JavaSparkContext field

```java
public class MyAdamContext extends ADAMContext {
  private final transient JavaSparkContext javaSparkContext;

  public MyAdamContext(final SparkContext sc) {
    super(sc);
    javaSparkContext = new JavaSparkContext(sc);
  }

  //...

  FileSystem fileSystem = path.getFileSystem(javaSparkContext.hadoopConfiguration());
```
https://github.com/heuermh/dishevelled-bio/blob/master/adam/src/main/java/org/dishevelled/bio/adam/BiojavaAdamContext.java#L133

What do you think about the `getFs...` methods?
