### ISSUE TITLE
When doing a release, the SNAPSHOT should bump by 0.1.0, not 0.0.1

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1364]
Mostly for discussion with @heuermh, but I think this impacts @akmorrow13 as well, so I figured I'd make a ticket. I think by default, we've been bumping the SNAPSHOT by 0.0.1 (i.e., after 0.21.0 is released, ToT becomes 0.21.1-SNAPSHOT). Since we have maintenance branches for any 0.21.x release, I think it would make sense to bump by 0.1.0 (i.e., after 0.21.0 is released, ToT becomes 0.22.0-SNAPSHOT). Thoughts? I was noticing this after moving to a snapshot in a downstream repo.

**Comment by heuermh** [comment]
+1

**Comment by akmorrow13** [comment]
Sounds good. Mango fix branches are using 0.21.1-SNAPSHOT right now for variant fixes.

**Comment by heuermh** [comment]
Decided then, we will do this from now on, thanks!
