### ISSUE TITLE
Bits of VariantContextConverter don't get ValidationStringencied

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1371]
E.g., https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala#L1923 does not get a validation stringency check.

**Comment by heuermh** [comment]
Now you've verbed it?  We really need a better name  :)

**Comment by fnothaft** [comment]
> Now you've verbed it? We really need a better name :)

In all fairness, I had slept very little at the point when I verbed it.
