### ISSUE TITLE
Increase visibility for SupportedHeaderLines.allHeaderLines

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#1372]
```
[INFO] Compiling 6 Scala sources to target/scala-2.10.6/classes...
[ERROR] .../Freebayes.scala:77: object SupportedHeaderLines in package converters
cannot be accessed in package org.bdgenomics.adam.converters
[ERROR] implicit val uFormatter = new VCFOutFormatter(SupportedHeaderLines.allHeaderLines)
```
In this specific use case I'd like to add Freebayes-specific headers to the ones we already support, something like
```scala
val freebayesHeaderLines = Seq( ... )
val headerLines = SupportedHeaderLines.addHeaderLines ++ freebayesHeaderLines
implicit val uFormatter = new VCFOutFormatter(headerLines)
```

**Comment by fnothaft** [comment]
+1, although perhaps we should do a name change as well? `SupportedHeaderLines` makes it sound like all other header lines will be lost.

**Comment by heuermh** [comment]
Ah that's right, we combine those in the input VCF with our supported header lines, so I don't actually need to define freebayes specific header lines.  How about rename to `VCFHeaderLines`?

**Comment by fnothaft** [comment]
That's a little too close to `htsjdk.variant.vcf.VCFHeaderLine` for me.

**Comment by heuermh** [comment]
ok, propose away  :)

**Comment by fnothaft** [comment]
Perhaps DefaultHeaderLines, since they're what we add by default.
