### ISSUE TITLE
Set the wrong value for end for symbolic alts

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1381]
See https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala#L1851. We should not be taking the reference allele length; we should use the end position value...

**Comment by heuermh** [comment]
I actually disagree with this; there might be additional discussion in bdg-formats, or perhaps I didn't bring it up yet.

The `end` field is documented strictly as `Calculated by start + referenceAllele.length()` and I find complicating that definition with "...or unless the VCF INFO key END is present and valid etc." messy.

Would a new field `VariantAnnotation.symbolicEnd` be better for mapping for the VCF INFO key "END"?

**Comment by fnothaft** [comment]
You can disagree all you want, but we throw an exception when saving Variants with multi-base symbolic alts back to VCF right now.

**Comment by heuermh** [comment]
When we convert htsjdk `VariantContext` to `o.b.a.models.VariantContext`, we're setting `Variant.end` to `start + referenceAllele.length()` and if VCF INFO key END is present, adding an entry to `Variant.attributes`.  That seems correct to me.

On converting `o.b.a.models.VariantContext` to htsjdk `VariantContext`, is it htsjdk that throws an exception?  I suppose the conversion should be
```
builder.stop(variant.getAnnotation.getSomatic ?
  variant.getAnnotation.getAttributes.get("END") : variant.getEnd)
```
(wrapped in Options with defaults as necessary)

Or am I misunderstanding the problem?

**Comment by fnothaft** [comment]
> When we convert htsjdk VariantContext to o.b.a.models.VariantContext, we're setting Variant.end to start + referenceAllele.length() and if VCF INFO key END is present, adding an entry to Variant.attributes. That seems correct to me.

I think you're doing too narrow of a reading here. Reference allele != referenceAllele.length. If you've got a symbolic call, the reference allele is typically given as the first base covered by the symbolic alt for brevity, but obviously the reference allele is not actually a single base, it is the whole sequence that is covered by the alt.

I'd also note that the only place that the stop position is codified in the VCF spec (at least, for 4.2, as I'm reading it) is for symbolic alts with an END key.

> On converting o.b.a.models.VariantContext to htsjdk VariantContext, is it htsjdk that throws an exception?

Correct.

> builder.stop(variant.getAnnotation.getSomatic ?
>  variant.getAnnotation.getAttributes.get("END") : variant.getEnd)

Not somatic, symbolic ;)

**Comment by heuermh** [comment]
> If you've got a symbolic call...

Right, the current definition for `Variant.end` doesn't make sense for symbolic alleles. Over in https://github.com/bigdatagenomics/bdg-formats/pull/107 you propose updating the definition with the two conditions. I would prefer keeping the symbolic end in `VariantAnnotation.attributes` or in a separate `VariantAnnotation.symbolicEnd` field.

> Not somatic, symbolic ;)

Distracted brain is not detail-oriented brain, apparently.  :)
