### ISSUE TITLE
INDEL realigner binary search conditional is flipped

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1402]
This is a bad one. See https://github.com/bigdatagenomics/adam/blame/master/adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/realignment/RealignIndels.scala#L88-L93. However, what's weird with this is that it should indicate that the realigner is borked, and that isn't consistent with validation data, nor our instrumentation telemetry. I've started to pull in some additional debug infrastructure to capture what's going on at each target in order to suss this out.

**Comment by heuermh** [comment]
The conditional says if the read starts before the start of the indel realignment target, which is the head of the tail after splitting targets in half, then return the head else return the tail.

Seems right to me, unless the conditional in `TargetOrdering.lt` doesn't match its method scaladoc (`target.readRange.compareTo(_) < 0`).

**Comment by fnothaft** [comment]
Ah see, the trouble is, what you wrote is `read < target`. What `TargetOrdering.lt(tail.head._1, read)` implements is `target < read`.

**Comment by fnothaft** [comment]
And yeah, I think the method scaladoc is wrong.

**Comment by fnothaft** [comment]
Lo and behold, the `TargetOrdering.lt` line is [missed](https://coveralls.io/builds/10331707/source?filename=adam-core%2Fsrc%2Fmain%2Fscala%2Forg%2Fbdgenomics%2Fadam%2Frdd%2Fread%2Frealignment%2FIndelRealignmentTarget.scala#L75), as is the [tree split](https://coveralls.io/builds/10331707/source?filename=adam-core%2Fsrc%2Fmain%2Fscala%2Forg%2Fbdgenomics%2Fadam%2Frdd%2Fread%2Frealignment%2FRealignIndels.scala#L89).
