### ISSUE TITLE
problem using  transform command

### ISSUE THREAD

**Issue by shohbek** [bigdatagenomics/adam#1406]
transform $ADAM_HOME/adam-core/src/test/resources/small.sam /tmp/small.adam.
according to above adam command I tried yo use exist small.sam file convert to small.adam ,unfortunely error . like that 
transform: file on standard input is not a valid GTS file
stdin:1:1: expecting an integer (number of vertices)
Please help me

**Comment by fnothaft** [comment]
Hi @shohbek! I can't tell for sure from the error message, but it looks like you might be missing the call to the `adam-submit` script. E.g., if you are in the root of your ADAM repo checkout, instead of:

```
transform $ADAM_HOME/adam-core/src/test/resources/small.sam /tmp/small.adam
```

it should be:

```
./bin/adam-submit transform $ADAM_HOME/adam-core/src/test/resources/small.sam /tmp/small.adam
```

**Comment by shohbek** [comment]
Thank your attention , but , When I use  `adam-submit`  , error: command not found So I have used in first line  `./adam-submit` 

After , `./adam-submit`  this command it runs ,It showed me Adam Actions, All was look like ok , but
 transform --help also  deference also sung adam actions deference 
For example , After , `./adam-submit`  this command  , transform --help ,
 `Usage: transform [OPTION] < file.gts `
Apply geometric transformations to the input.

  -r ANGLE  --rx=ANGLE      rotate around x-axis (angle in degrees)
  -m ANGLE  --ry=ANGLE      rotate around y-axis
  -n ANGLE  --rz=ANGLE      rotate around z-axis
  -s FACTOR --scale=FACTOR  scale by FACTOR
  -R FACTOR --sx=FACTOR     scale x-axis by FACTOR
  -M FACTOR --sy=FACTOR     scale y-axis by FACTOR
  -N FACTOR --sz=FACTOR     scale z-axis by FACTOR
  -t V      --tx=V          translate of V along x-axis
  -u V      --ty=V          translate of V along y-axis
  -w V      --tz=V          translate of V along z-axis
  -i        --revert        turn surface inside out
  -o        --normalize     fit the resulting surface in a cube of
                            size 1 centered at the origin `

What kind of problem this , It took much time honestly .

I followed every step  in the beginning of installation and usage, but unfortunately , I cannot figure out this kind of strange problems

**Comment by fnothaft** [comment]
Hi @shohbek!

Are the two commands you are running:

```
./adam-submit
./adam-submit transform --help
```

or

```
./adam-submit
transform --help
```

I would expect the first set of commands to work, but the second set of commands will definitely not work.

**Comment by shohbek** [comment]
Thank you ,

**Comment by fnothaft** [comment]
Thanks @shohbek! Please feel free to reopen this issue if you have any other problems.
