### ISSUE TITLE
Remove Smith-Waterman consensus mode

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1414]
This code is currently unused. As part of this pull request, we will:

- [ ] Delete the org.bdgenomics.adam.algorithms.smithwaterman package
- [ ] Delete the ConsensusGeneratorFromSmithWaterman
- [ ] Move the org.bdgenomics.adam.algorithms.consensus package into org.bdgenomics.adam.rdd.read package

**Comment by heuermh** [comment]
Closing as WontFix
