### ISSUE TITLE
Improve unit test coverage of Feature parser/encoder helper

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1418]
Specifically, in `org.bdgenomics.adam.rdd.feature.Features`. We need to improve coverage of the ontology term and dbxref codes, as well as the GFF tools.

**Comment by MaxGreil** [comment]
I can pick this issue up.
@fnothaft  can you please explain what needs to be done here?

**Comment by heuermh** [comment]
Closing as WontFix
