### ISSUE TITLE
loadReferenceFile missing from Java API

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1421]
Additionally, we should add `loadTwoBit` and `loadContigMap` functions to the Scala API. `loadReferenceFile` just loads these manually.

**Comment by heuermh** [comment]
+1 to adding new `loadTwoBit` and `loadContigMap` functions.

I'm not sure `JavaADAMContext.loadReferenceFile` is necessary, as there aren't any options or default values in its method signature.
