### ISSUE TITLE
Improve metrics coverage across ADAMContext load methods

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#1428]

**Comment by fnothaft** [comment]
Actually, even better, I found today that many of the `_.instrument` calls are misapplied.

**Comment by xubo245** [comment]
Why are there some problems in ADAMContextSuite.scala?

I run it in local (windows system), Is the reason my environmental configuration error?

![qq 20170310203040](https://cloud.githubusercontent.com/assets/8759816/23795417/81ce424a-05d0-11e7-9cae-2a151b5e771e.png)

Adam-0.21.1-SNAPSHOT and adam-0.21.0 both happened.

**Comment by heuermh** [comment]
Fixed by #1487
