### ISSUE TITLE
Clean up replicated join code in INDEL realigner and BQSR

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1429]
We have duplicated "hand optimized" region joins in BQSR (#1423) and IR (#1412). We should eliminate these and suss out any performance issues that we get going from specialized-to-generalized.

**Comment by heuermh** [comment]
@fnothaft is this still an issue?  Move to 0.25.0?

**Comment by heuermh** [comment]
Closing as WontFix
