### ISSUE TITLE
Document using ADAM snapshot

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1432]
Our README mentions that we publish snapshots, but we don't mention how to use them.

**Comment by heuermh** [comment]
Yes, the README needs an update on how to build; it doesn't mention the `move_to...` scripts either.

**Comment by xubo245** [comment]
@fnothaft   I just add a ADAM-0.21.1-SNAPSHOT into my project, so I write some document in:
https://github.com/bigdatagenomics/adam/pull/1433

detail: https://github.com/bigdatagenomics/adam/pull/1433/commits/446ae819d72b5a5a189419ad5d556c2b9c462964

**Comment by fnothaft** [comment]
This was resolved by #1433.
