### ISSUE TITLE
Port over code for populating SequenceDictionaries from .dict files

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1449]
Some code to do this is in https://github.com/heuermh/cannoli/pull/11. Additionally, we should update the various places in the code that "create" a sequence dictionary from thin air to support providing a `.dict` file.

**Comment by heuermh** [comment]
See also Bedtools "genome" file
http://bedtools.readthedocs.io/en/latest/content/overview.html#what-is-a-genome-file
