### ISSUE TITLE
Publish Markdown and Scaladoc to the interwebs

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1453]
We used to use https://github.com/bigdatagenomics/adam/blob/master/scripts/publish-scaladoc.sh but it didn't work well.

**Comment by fnothaft** [comment]
Pushed a [gh-pages branch](https://github.com/bigdatagenomics/adam/tree/gh-pages).

**Comment by fnothaft** [comment]
And here's our docs: http://bdgenomics.org/adam/

Aren't they lovely? :-p

**Comment by heuermh** [comment]
Eesh, those project docs look pretty sad.  A bunch of the links and some of the MathJax formatting didn't work.

From what I can tell, we can use GitHub Pages Jekyll with the `gh-pages` branch.  Then we could leave the markdown pages unrendered by pandoc.

As far as sequencing, do you want to merge #1461 before the 0.22.0 release then then have us look into better markdown rendering after?

**Comment by heuermh** [comment]
See also #774

**Comment by fnothaft** [comment]
Under the principle of "perfect is the enemy of good", I would rather publish a release with ugly docs than a release with no docs. That said, I'd like to merge #1461 before 0.22.0.

**Comment by heuermh** [comment]
+1
