### ISSUE TITLE
New primitives for adam-core

### ISSUE THREAD

**Issue by devin-petersohn** [bigdatagenomics/adam#1454]
Here is a link to the list of primitives we would need in a Bedtools implementation:

http://bedtools.readthedocs.io/en/latest/content/overview.html#summary-of-available-tools

Which primitives would be useful in ADAM?

**Comment by heuermh** [comment]
Bedtools `intersect`, `closest`, and `merge` are those operations I use most frequently.

**Comment by devin-petersohn** [comment]
For now, we will add things to the layer above ADAM, and we will merge primitives into ADAM as we have them tested.

**Comment by heuermh** [comment]
Sounds reasonable.
