### ISSUE TITLE
Update to Hadoop-BAM 7.8.0

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1455]
Bumps to latest version of HTSJDK. Should tack on to #1440. Will need to update SAM/BAM/CRAM queryname sorted loading code. As part of that fix, we should consolidate the [BAM->Fragments path](https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala#L1570-L1578) into a `loadBamAsFragments` method, which will make it easier to use downstream (e.g., in https://github.com/heuermh/cannoli/pull/15).

**Comment by heuermh** [comment]
While we're in there I'd suggest taking out
```scala
} else if (filePath.endsWith(".reads.adam")) {
  log.info(s"Loading $filePath as ADAM AlignmentRecords and converting to Fragments.")
  loadAlignments(filePath).toFragments
```

And from `loadAlignments`
```scala
} else if (filePath.endsWith("contig.adam")) {
  log.info(s"Loading $filePath as Parquet of NucleotideContigFragment and converting to AlignmentRecords. Projection is ignored.")
  AlignmentRecordRDD.unaligned(loadParquetContigFragments(filePath).toReads)
```

Sorry, I'll create a new issue.
