### ISSUE TITLE
make reading fasta less memory hungry

### ISSUE THREAD

**Issue by antonkulaga** [bigdatagenomics/adam#1458]
When I download latest human genome release and convert fasta to adam it eats >22 Gb memory (for 3.2 GB) file. It would be nice to optimize it somehow in terms of memory consumption.

**Comment by heuermh** [comment]
Is this on a single node?  What are you using for `-fragment_length` (the default is 10kb)?

**Comment by antonkulaga** [comment]
Yes, it is signle node with default fragment_length

**Comment by antonkulaga** [comment]
Any progress on this?

**Comment by fnothaft** [comment]
Sorry, no major news here. We've been backlogged with the 0.23.0 release and Python/R API additions. How are you using the output of the conversion? If you are using it for a broadcast object via the ReferenceFile API, you may want to consider the TwoBitFile implementation, which is much more efficient from a memory capacity perspective.

**Comment by fnothaft** [comment]
I'll take a look at this soon though; we added sequence dictionary loading code that may eliminate the need for some of the code and caching that is in the FASTA load path.

**Comment by heuermh** [comment]
Fixed by #2175
