### ISSUE TITLE
FeatureRDD.toCoverage throws NullPointerException when there is no coverage information

### ISSUE THREAD

**Issue by devin-petersohn** [bigdatagenomics/adam#1471]
This is more of a discussion on how to handle this case.

Do we want to leave it, or should we add a `require()`?

The exception isn't thrown until the `CoverageRDD` is materialized, and `NullPointerExceptions` are notoriously difficult to debug at times.

I think it would be nicer to have in ADAM, but I am also happy to handle this exception downstream if that is the consensus.

**Comment by fnothaft** [comment]
I would +1 adding a `require`. IMO, users shouldn't see a `NPE`.
