### ISSUE TITLE
Allow joins on regions that are within a threshold (instead of requiring overlap)

### ISSUE THREAD

**Issue by devin-petersohn** [bigdatagenomics/adam#1473]
In order to comply with BedTools requirements, we need an option to join on data that fits some threshold.

**Comment by fnothaft** [comment]
+1! We used to have something like this, actually. There are myriad ways to do this, but IMO the simplest way is to increase the width of the reference region keys on one side of the join. Not sure if you had an alternative approach in mind; this is but one approach out of many...

**Comment by devin-petersohn** [comment]
I've given this some thought and I believe that using the `ReferenceRegion.distance()` is the best way to go about it. In my cleanup of `ReferenceRegion.scala` I am adding an `isNearby()` method that takes a threshold. This can completely replace the overlaps calls in all cases.
