### ISSUE TITLE
ReferenceRegion overlaps and covers returns false if overlap is 1

### ISSUE THREAD

**Issue by devin-petersohn** [bigdatagenomics/adam#1492]
`ReferenceRegion("chr0", 10, 100).overlaps(region("chr0", 100, 110)))`
`ReferenceRegion("chr0", 10, 100).covers(region("chr0", 100, 110)))`

Should these be returning false?

Referencing #1473, #1474.

**Comment by fnothaft** [comment]
They should return false. Our coordinate system is 0-based half-open --> i.e., in an interval, start is inclusive, end is exclusive.

**Comment by devin-petersohn** [comment]
I knew this on Friday, sorry for the silly question.

Closing as question answered.

**Comment by fnothaft** [comment]
No sweat!
