### ISSUE TITLE
Sequence dictionary records in TwoBitFile are not stable

### ISSUE THREAD

**Issue by tomwhite** [bigdatagenomics/adam#1502]
The order of the contigs in a dictionary produced from TwoBitFile is not the same as the order they are stored in in the .2bit file.

I think the problem is the records are being stored in a standard map, rather than one that preserves insertion order (like ListMap).

See https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/util/TwoBitFile.scala#L70

**Comment by heuermh** [comment]
Good catch!  In what applications would the order matter?

**Comment by tomwhite** [comment]
I had some problems with partitioning in GATK which boiled down to the ordering of the reference sequence dictionary. I think a fasta dict file has an order, so it would be good to be consistent with that if possible.
