### ISSUE TITLE
Alignment Record sort is not consistent with samtools

### ISSUE THREAD

**Issue by akmorrow13** [bigdatagenomics/adam#1504]
I have sorted platinum trio files using ADAM and saved them as a single file bam. When generating an index using samtools (samtools index NA12891.bam) I have to resort using samtools for some of the files. I get the following error:
`NO_COOR reads not in a single block at the end 0 -1`
Meaning that I have to resort.
The ADAM sorting complies with samtools for NA12878, but not NA12891 and NA12892.

**Comment by fnothaft** [comment]
That is very odd. What's the exact command you used to sort?

**Comment by akmorrow13** [comment]
./bin/adam-submit --master yarn-client --num-executors 12 --executor-cores 8 --executor-memory 20G -- transform -sort_reads -single /data/platinum/adam/NA12891_S1.bam.adam /data/platinum/alignments_sorted/NA12891_S1.sorted.bam

**Comment by fnothaft** [comment]
Checking this now.

**Comment by fnothaft** [comment]
Sigh. This is A Thing.
