### ISSUE TITLE
Where can I find "Phred-scaled quality score" (QUAL)?

### ISSUE THREAD

**Issue by majkiw** [bigdatagenomics/adam#1506]
Hey,
Following instructions in https://github.com/bigdatagenomics/adam/wiki/FAQ-(Frequently-Asked-Questions) and http://bdgenomics.org/mail/ I created a question in Google Groups https://groups.google.com/forum/#!topic/adam-developers/WNu5a8wIwz8
Since I don't think anyone looks there anymore it I will ask it here again.

When reading VCF I cannot find "Phred-scaled quality score" (QUAL) and even htsjdkVC.getPhredScaledQual doesn't seem to be accessed anywhere.
I also don't see the values when printing the whole Genotype object.
Is the QUAL field omitted on purpose or am I missing something obvious?

Thank you,
Michał Wysocki

**Comment by heuermh** [comment]
Sorry for not seeing your post on the mailing list!

In the VCF specification, QUAL is defined
```
6. QUAL - quality: Phred-scaled quality score for the assertion made
in ALT. i.e. −10log10 prob(call in ALT is wrong). If ALT is ‘.’ (no variant) then
this is −10log10 prob(variant), and if ALT is not ‘.’ this is −10log10 prob(no variant).
If unknown, the missing value should be specified. (Float)
```

We use a split-allelic model, where each ALT at a site is a separate `Variant`.  There is no way to distribute this per-site quality score over all the separate variants so we have to drop it.

**Comment by majkiw** [comment]
Thank you for the quick response.
I read the definition before but I didn't realize split-allelic approach breaks it.
