### ISSUE TITLE
Split apart #1324

### ISSUE THREAD

**Issue by devin-petersohn** [bigdatagenomics/adam#1507]
Split apart #1324 into separate PR for sorted PR and joins rework PR.

Maintaining sorted knowledge can help in optimizations for downstream applications, but the join part of #1324 is monstrous.

I believe that separating the PR into separate sorted/join PRs can expedite the process for getting the sort and partition map knowledge into ADAM. Thoughts?

**Comment by fnothaft** [comment]
I mean, my general sense was that #1324 was about a week away from being ready to merge, just depending on you feeling done with it and me and @heuermh doing another review pass? Since @akmorrow13 is pretty booked up for the next week with end-of-semester stuff, I'd rather not split the PR.

**Comment by devin-petersohn** [comment]
Closing: agreement was reached.
