### ISSUE TITLE
Allow +Inf and -Inf Float values when reading VCF

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#1512]
Per the VCF 4.3 specification,

Float (32-bit, formatted to match the regular expression
`^[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?$`, `NaN`, or `+/-Inf`)

From what I can tell, Scala float parsing delegates to [the implementation in java](https://docs.oracle.com/javase/7/docs/api/java/lang/Double.html#valueOf(java.lang.String)), which uses
```
...
"[+-]?(" + // Optional sign character
"NaN|" +           // "NaN" string
"Infinity|" +      // "Infinity" string
...
```

Thus we may need to special case `+Inf` and `-Inf`.  Reported by @tangxuan_twitter on [Gitter](https://gitter.im/bigdatagenomics/adam).

**Comment by fnothaft** [comment]
@heuermh This is an upstream issue in htsjdk, no?

**Comment by heuermh** [comment]
In Scala number format parsing actually.  I couldn't see a simple fix so I left it here.

**Comment by fnothaft** [comment]
Oh, that's right. htsjdk just gives us Strings, that we then have to make sense of. LOVE IT.
