### ISSUE TITLE
Stranded vs unstranded in getReferenceRegions() for features

### ISSUE THREAD

**Issue by devin-petersohn** [bigdatagenomics/adam#1513]
[Here](https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/FeatureRDD.scala#L331) we call `ReferenceRegion.unstranded()`, losing the strandedness information. 

There are known issues using this in the joins when trying to join datatypes that have no stranded information from the start.

**Comment by fnothaft** [comment]
This appears to be out of date; I believe this is closed. We'll reopen if necessary later.
