### ISSUE TITLE
Bump to bdg-formats 0.11.0

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1520]
See https://github.com/bigdatagenomics/bdg-formats/milestone/6.

@heuermh I'm thinking that we complete https://github.com/bigdatagenomics/bdg-formats/issues/114 and then cut bdg-formats 0.11.0. This will allow us to tackle #1257 for 0.23.0. This would push the genotype refactor (https://github.com/bigdatagenomics/bdg-formats/pull/108) out to 0.24.0. How does this sound to you?

**Comment by heuermh** [comment]
+1
