### ISSUE TITLE
Compute a SequenceDictionary from a *.genome file

### ISSUE THREAD

**Issue by devin-petersohn** [bigdatagenomics/adam#1534]
Bedtools uses `*.genome` files to serve the same purpose as our `SequenceDictionary`, so instead of computing based on the bounds of the data would it be possible to use the `*.genome` file to create the `SequenceDictionary`?

**Comment by heuermh** [comment]
Yes, mentioned here https://github.com/bigdatagenomics/adam/issues/1449#issuecomment-290777805
