### ISSUE TITLE
Is parquet using delta encoding for positions?

### ISSUE THREAD

**Issue by jpdna** [bigdatagenomics/adam#1552]
I'm having trouble confirming as parquet-tools is not building for me right now, but I wanted to check if we think that our `long` genomic positions are being encoded in the most efficient way possible (probably delta for sorted data)  in   parquet.  See discussion here: https://issues.apache.org/jira/browse/PARQUET-225

**Comment by fnothaft** [comment]
To get delta encoding, you need to set disableDictionaryEncoding to true. This effectively enables the Parquet 2 format, which supports delta encoding. There was a discussion recently on the Spark lists that the vectorized Spark SQL reader only supports Parquet 1, so you may see worse performance with delta encoding from Spark SQL. Truth be told, I looked at file sizes a while back and moving to delta encoding didn't seem to make a huge difference.

**Comment by fnothaft** [comment]
I don't think there's anything actionable here for right now, so I'll close this. Please reopen if you have a question @jpdna.
