### ISSUE TITLE
Handling Validation Stringency without repeated code

### ISSUE THREAD

**Issue by devin-petersohn** [bigdatagenomics/adam#1572]
We have some duplicated code [here](https://github.com/bigdatagenomics/adam/blob/6ee0b8b28fdbdb5e52041519ac9a671f741bc5e5/adam-core/src/main/scala/org/bdgenomics/adam/rdd/feature/FeatureParser.scala#L38) and [here](https://github.com/bigdatagenomics/adam/blob/c78a0edfde4a06beed6dbe74808c135744fd3c71/adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala#L210) for `throwWarnOrNone()`. This may belong in `adam.util`, and can afford to be generic (as in the `GenomicRDD` implementation). This should hopefully also make it easier in the future to simply use it in all cases of `ValidationStringency` in the future.

**Comment by heuermh** [comment]
Closing as WontFix
