### ISSUE TITLE
Unaligned Trait does nothing

### ISSUE THREAD

**Issue by devin-petersohn** [bigdatagenomics/adam#1573]
It seems like the `Unaligned` trait isn't doing [anything](https://github.com/bigdatagenomics/adam/blob/c78a0edfde4a06beed6dbe74808c135744fd3c71/adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala#L1419). Should it be removed?

**Comment by fnothaft** [comment]
+1. I think I had intended to remove it in https://github.com/bigdatagenomics/adam/commit/5ae88202339b47851ab91f85c58a1185ad232740, but for some reason did not.
