### ISSUE TITLE
Add filterBySequenceDictionary to GenomicRDD

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#1575]
As suggested in comment https://github.com/bigdatagenomics/adam/pull/1557#discussion_r122308994, add
```scala
def filterBySequenceDictionary(sd: SequenceDictionary): U = {
  ...
}
```
and
```scala
def filterBySequenceDictionary(): U = {
  filterBySequenceDictionary(this.sequences)
}
```
methods on `GenomicRDD`.

**Comment by fnothaft** [comment]
So, I didn't quite understand what was going on back on https://github.com/bigdatagenomics/adam/pull/1557#discussion_r122308994, and I still don't quite understand what this method would do. Is it "filter items mapped to contigs present in a sequence dictionary"? If so, we should be able to mash [`filterByOverlappingRegions`](https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala#L516) and the addition of `all` to the `ReferenceRegion` object in https://github.com/bigdatagenomics/adam/commit/e98ee2d1c5582364673fada70779aab5a73856b1. My preference would be to overload the `filterByOverlappingRegions` name; `filterBySequenceDictionary` sounds weird to me.

**Comment by heuermh** [comment]
I was mistaken earlier in that I thought the sequence dictionary was used in region joins.  The question is really what to do when reading in features:

When reading in a BED file:
 - Use an empty sequence dictionary, or
 - Create a sequence dictionary on the fly from the contig names in the BED records and length max(end), or
 - Create a sequence dictionary on the fly from the contig names in the BED records and an infinite length, similar to `ReferenceRegion.all`

When reading in a BED file with a genome file:
 - Load records without regard for sequence dictionary, or
 - Consider `ValidationStringency`, validate records against sequence dictionary

The thinking behind this suggestion was to load records without regard for sequence dictionary and then filter after the fact, if desired.

**Comment by fnothaft** [comment]
> I was mistaken earlier in that I thought the sequence dictionary was used in region joins.

It used to be.

WRT BED, my feeling is empty sequence dictionary in the first case, load records without regard for sequence dictionary in the second case. We don't currently validate reads or variants/genotypes against a sequence dictionary, so why add checking specific to feature file formats?

**Comment by heuermh** [comment]
+1 to both.  @devin-petersohn thoughts?

**Comment by devin-petersohn** [comment]
That sounds good to me.

**Comment by heuermh** [comment]
ok, created new issue #1588, closing this one, will update pull request #1557
