### ISSUE TITLE
Spark 1.x Scala 2.10 snapshot artifacts missing since 31 March 2017

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#1578]
From Jenkins build failure downstream in https://github.com/bigdatagenomics/cannoli/pull/42
```
[INFO] ------------------------------------------------------------------------
[INFO] Building cannoli 2.10 0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/bdgenomics/adam/adam-cli_2.10/0.23.0-SNAPSHOT/maven-metadata.xml

Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/bdgenomics/adam/adam-cli_2.10/0.23.0-SNAPSHOT/adam-cli_2.10-0.23.0-SNAPSHOT.pom

[WARNING] The POM for org.bdgenomics.adam:adam-cli_2.10:jar:0.23.0-SNAPSHOT is missing, no dependency information available
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/bdgenomics/adam/adam-cli_2.10/0.23.0-SNAPSHOT/adam-cli_2.10-0.23.0-SNAPSHOT.jar
```

There hasn't been a `_2.10` snapshot pushed to Sonatype since 31 March 2017, and that was version 0.21.1-SNAPSHOT.

https://oss.sonatype.org/content/repositories/snapshots/org/bdgenomics/adam/adam-cli_2.10/

The `_2.11` snapshots are there (most recent 22 June 2017 for version 0.23.0-SNAPSHOT)

https://oss.sonatype.org/content/repositories/snapshots/org/bdgenomics/adam/adam-cli_2.11/

as are the `spark2_2.10` snapshots (most recent 22 June 2017 for version 0.23.0-SNAPSHOT)

https://oss.sonatype.org/content/repositories/snapshots/org/bdgenomics/adam/adam-cli-spark2_2.10/

**Comment by fnothaft** [comment]
Yeah, this is caused by the documentation publishing step. Let me look...

**Comment by fnothaft** [comment]
I've fixed this in @AmplabJenkins by disabling the `publish-scaladoc.sh` script for now, which needs credentials.
