### ISSUE TITLE
Eliminate unused ConcreteADAMRDDFunctions class

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1580]
I was considering doing this in #1391, as it would eliminate the classtag hacking I've added in https://github.com/bigdatagenomics/adam/pull/1391/commits/92e296eb98c3ec585a4c365c37dd3f07827e9849. However, I don't want this to come in to #1391, because I'd rather it get a standalone review, etc. Here's the to-do:

- [ ] Eliminate unused ConcreteADAMRDDFunctions class
- [ ] Move functionality from ADAMRDDFunctions into GenomicRDD
- [ ] Change GenomicRDD from a trait into an abstract class with a view bound on `T: Manifest`, which eliminates the need to hack the classtags

**Comment by heuermh** [comment]
@fnothaft move to 0.25.0?

**Comment by fnothaft** [comment]
I think this is keep in 0.24.0, but let me confirm.
