### ISSUE TITLE
New Illumina FASTQ spec adds metadata to read name line

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1585]
From http://support.illumina.com/content/dam/illumina-support/help/BaseSpaceHelp_v2/Content/Vault/Informatics/Sequencing_Analysis/BS/swSEQ_mBS_FASTQFiles.htm:

```
@<instrument>:<run number>:<flowcell ID>:<lane>:<tile>:<x-pos>:<y-pos> <read>:<is filtered>:<control number>:<sample number>
```

This causes trouble when grouping reads by fragment.

**Comment by heuermh** [comment]
Lovely.
