### ISSUE TITLE
Interleaved FASTQ recognizes only /1 suffix pattern

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#1589]
[FastqRecordConverter](https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/converters/FastqRecordConverter.scala#L43) supports read suffixes with a few different patterns, `[space]1`, `+1`, `_1`, and `/1`.  I've seen `[space]1` and `/1` in the wild.

[InterleavedFastqInputFormat](https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/java/org/bdgenomics/adam/io/InterleavedFastqInputFormat.java#L95) only recognizes `/1`, resulting in empty `FragmentRDD`s if the interleaved FASTQ file uses one of the other patterns.

**Comment by fnothaft** [comment]
Resolved by https://github.com/bigdatagenomics/adam/commit/7a11d9ebc2f5f0fc04eb81c321ac987c2ee290fd.
