### ISSUE TITLE
RFC: Removing Spark 1.x, Scala 2.10 support in 0.24.0 release

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1597]
[From the spark-dev list, it looks like Spark 2.3.0 will add support for Scala 2.12 and drop support for Scala 2.10.](http://apache-spark-developers-list.1001551.n3.nabble.com/RFC-removing-Scala-2-10-td21116.html) As such, I think that we should drop Spark 1.x and Scala 2.10 support in the first ADAM release after Spark 2.3.0, which for now, I am assuming to be ADAM 0.24.0. Thoughts?

**Comment by heuermh** [comment]
+1

For me, the stragglers are cgcloud and dockerized Spark for Toil, both of which are still our responsibility to some extent.  I haven't heard from any external users still wanting Spark 1.x.

**Comment by antonkulaga** [comment]
+1

**Comment by antonkulaga** [comment]
Maybe for 0.23 release, you can at least make Spark 2 and Scala 2.11 the default one so people will not need to run 2.11/spark2 bash scripts each time the clone adam?

**Comment by heuermh** [comment]
> Maybe for 0.23 release, you can at least make Spark 2 and Scala 2.11 the default one...

Sorry, misread this originally.  We don't want to change the release scripts before the 0.23.0 release, so Spark 1.x/Scala 2.10 will remain the default.
