### ISSUE TITLE
Scala copy method not supported in abstract classes such as AlignmentRecordRDD

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#1599]
See issue https://github.com/bigdatagenomics/cannoli/issues/55

**Comment by devin-petersohn** [comment]
Are you wanting to add `def copy(...)` to `RDDBoundAlignmentRecordRDD` and `DatasetBoundAlignmentRecordRDD`?

**Comment by heuermh** [comment]
No, it isn't present on `AlignmentRecordRDD`, which is abstract

**Comment by devin-petersohn** [comment]
Are you wanting an abstract definition in `AlignmentRecordRDD`, and then implementations in the above mentioned classes?

If you don't want changes in ADAM, you could just use the Companion [object](https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDD.scala#L150):
`AlignmentRecordRDD(rdd, sequences, recordGroups)`

**Comment by heuermh** [comment]
That was my fix in https://github.com/bigdatagenomics/cannoli/pull/56.  The copy method is some Scala magick, I'm not sure if we want to add explict ones everywhere.
