### ISSUE TITLE
VariantRDD doesn't save partition map

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#1601]
@devin-petersohn I noticed that `VariantRDD` doesn't call `AvroGenomicRDD.savePartitionMap` in `saveMetadata`.

https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/VariantRDD.scala#L182

Was this omission intentional?

**Comment by devin-petersohn** [comment]
No this was not intended, but I believe @fnothaft has a better way to handle the `optPartitionMap` in #1590.
