### ISSUE TITLE
Make it easier to modify/interrogate metadata from Python/R

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1604]
Extends from #1600. Right now, we have handles to the `GenomicRDD` from Python and R, but we can't read or modify the metadata wrapped in those `GenomicRDD`s. We should:

- [ ] Add wrappers for `SequenceDictionary` and `SequenceRecord`
- [ ] Add a wrapper for `Sample`
- [ ] Add wrappers for `RecordGroupDictionary` and `RecordGroup`
- [ ] Extend the `GenomicRDD` manipulation functions from #1600 into Python and R

**Comment by heuermh** [comment]
@fnothaft move to 0.25.0?

**Comment by heuermh** [comment]
Closing as WontFix
