### ISSUE TITLE
Snapshot Distribution Does not include jar files

### ISSUE THREAD

**Issue by pbashyal-nmdp** [bigdatagenomics/adam#1607]
The sanpshot distribution in https://oss.sonatype.org/content/repositories/snapshots/org/bdgenomics/adam/adam-distribution-spark2_2.11/0.23.0-SNAPSHOT/ is not complete. The jar files are not in the distribution.

Eg. `adam-distribution_2.11-0.23.0-20170711.025002-241-bin.tar.bz2` expands to:
```
[adam-distribution-spark2_2.11-0.23.0-SNAPSHOT]$ ls -la
total 196
drwxrwxr-x 5 hadoop hadoop   4096 Jul 13 16:30 .
drwxr-xr-x 6 hadoop hadoop   4096 Jul 13 16:41 ..
drwxr-xr-x 2 hadoop hadoop   4096 Jul 11 02:35 bin
-rw-r--r-- 1 hadoop hadoop 123491 Jun 24 11:20 CHANGES.md
-rw-r--r-- 1 hadoop hadoop   5151 Jun 24 11:20 CONTRIBUTING.md
drwxr-xr-x 3 hadoop hadoop   4096 Jul 11 02:52 javadocs
-rw-r--r-- 1 hadoop hadoop  16714 Jun 24 11:20 LICENSE.txt
-rw-r--r-- 1 hadoop hadoop  24094 Jun 24 11:20 README.md
drwxr-xr-x 5 hadoop hadoop   4096 Jul 11 02:46 scaladocs
```

**Comment by fnothaft** [comment]
Thanks for flagging this @pbashyal-nmdp! I see exactly what's going on here; we changed the assembly JAR name and forgot to change it in the distribution package.
