### ISSUE TITLE
Architecture section is missing from docs

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1630]

**Comment by devin-petersohn** [comment]
Do we have any UML or lower level design documents to help describe the architecture? I couldn't find any in the group shared documents.

**Comment by devin-petersohn** [comment]
Will we be moving the `Apache Spark`, `Apache Parquet`, and `Apache Avro` sections from the [intro](https://github.com/bigdatagenomics/adam/blob/master/docs/source/01_intro.md) to the architecture?

**Comment by fnothaft** [comment]
Yeah, I'd say so.
