### ISSUE TITLE
Installation instructions for Homebrew missing from documentation

### ISSUE THREAD

**Issue by devin-petersohn** [bigdatagenomics/adam#1631]

**Comment by devin-petersohn** [comment]
@heuermh, are there any other installation methods missing from the docs?

**Comment by heuermh** [comment]
I suppose we could add bioconda, docker, and singularity if we wanted to.  Is this for the README or the proper docs?  I want to cut down the README to bare minimum and linking to the docs, but that should really go with #1548 which is milestoned 0.24.0.

**Comment by devin-petersohn** [comment]
This is for the long [docs](https://github.com/bigdatagenomics/adam/blob/master/docs/source/02_installation.md).

**Comment by heuermh** [comment]
Homebrew:

https://brew.sh/
```bash
$ brew tap homebrew/science
$ brew install adam
```

Linuxbrew:

http://linuxbrew.sh/
```bash
$ brew tap homebrew/science
$ brew install adam
```

Bioconda:

https://bioconda.github.io/#using-bioconda
```bash
$ conda config --add channels bioconda
$ conda install adam
```

Docker image built on linuxbrew:

https://www.docker.com
```bash
$ docker run heuermh/adam
```

Docker image built on bioconda from BioContainers:

https://biocontainers.pro/
```bash
$ docker run quay.io/biocontainers/adam
```

Docker image built for Toil stuff:

(not sure if this is up-to-date)
https://github.com/BD2KGenomics/cgl-docker-lib/blob/master/adam/README.md
```bash
$ docker run \
       --net=host \
       -p 9999:9999 \
       quay.io/ucsc_cgl/adam:latest \
       --master spark://<spark_master_ip>:7077 \
       --conf spark.driver.port=9999 -- \
       flagstat hdfs://<hdfs_master_ip>:8020/mouse_chrM.bam 
```

Singularity image built on bioconda from BioContainers:

(tbd, I'm not sure where to find these yet)
```bash
```

The bioconda/BioContainers automagic might also make these images available in the Galaxy tool registry.  Will look into it.

**Comment by fnothaft** [comment]
@heuermh can you PR these additions to the docs?

**Comment by devin-petersohn** [comment]
@heuermh assigning you for now, let me know if you can't make these additions.

**Comment by heuermh** [comment]
Yep, am working on it
