### ISSUE TITLE
Intro docs missing a number of active projects

### ISSUE THREAD

**Issue by devin-petersohn** [bigdatagenomics/adam#1632]
The last few [lines](https://github.com/bigdatagenomics/adam/blob/master/docs/source/01_intro.md) of the file contain other projects, but it is missing a few.

**Comment by fnothaft** [comment]
+1. I think we should add an "Ecosystem" section with a diagram of the BDG projects, tagged by their "readiness".

**Comment by heuermh** [comment]
Should we use a separate awesome list for this?

https://github.com/awesome-spark/awesome-spark#bioinformatics
https://github.com/sindresorhus/awesome

Or perhaps create one in addition to what is in the docs.  It'd be nice for it to be more community-driven.

**Comment by fnothaft** [comment]
Resolved by #1653.
