### ISSUE TITLE
Building downstream apps docs reformatting

### ISSUE THREAD

**Issue by devin-petersohn** [bigdatagenomics/adam#1638]
Some of the code blocks are incomplete and could use minor cleanup.

**Comment by devin-petersohn** [comment]
For the lazy: [link](https://github.com/bigdatagenomics/adam/blob/master/docs/source/60_building_apps.md)

**Comment by heuermh** [comment]
How so?  They use `...` on purpose and link to the full example projects adam-examples and adam-commands.

**Comment by fnothaft** [comment]
I'm with @heuermh here. Shall we close this issue?

**Comment by devin-petersohn** [comment]
Sure, we can close.
