### ISSUE TITLE
Algorithms docs formatting

### ISSUE THREAD

**Issue by devin-petersohn** [bigdatagenomics/adam#1639]
The [rendered docs](https://github.com/bigdatagenomics/adam/blob/master/docs/source/70_algorithms.md) are not correctly formatted for the equations. The intradoc links don't work either.

**Comment by devin-petersohn** [comment]
@gunjanbaid will resolve this.

**Comment by gunjanbaid** [comment]
Thanks @devin-petersohn, working on this.

**Comment by gunjanbaid** [comment]
Is there a known solution for rendering equations properly in github markdown? I was not able to find one.

**Comment by devin-petersohn** [comment]
Right now, it looks like the only solution is to render the image elsewhere and use it: https://github.com/github/markup/issues/897

**Comment by heuermh** [comment]
> Is there a known solution for rendering equations properly in github markdown?

"The input language for mathematics is LaTeX markup."

I believe our end goal is to use readthedocs, which runs Sphinx
http://www.sphinx-doc.org/en/stable/ext/math.html

**Comment by gunjanbaid** [comment]
Ok, I'll use the latex formatting supported by Sphinx. Just wanted to make sure readability on GitHub was not a concern.

**Comment by gunjanbaid** [comment]
@devin-petersohn I fixed the simple latex that can be rendered in Sphinx markdown. The latex in the `\begin{algorithm}` and `\end{algorithm}` lines requires additional latex packages. With Sphinx, these are normally included in a `conf.py` file but I don't know how to enable these for https://adam.readthedocs.io since we don't have Sphinx set up yet.

Let me know if you want me to just include an image of these sections for now.

**Comment by fnothaft** [comment]
Thanks @gunjanbaid! WRT Sphinx, perhaps we should plan to move all the docs over to Sphinx as the last thing we do before cutting the release? I can plan to sign on for this task. If so, would you mind adding a `conf.py` file to the docs in #1645?

**Comment by gunjanbaid** [comment]
@fnothaft Sounds good, I will add a `conf.py` in.

**Comment by fnothaft** [comment]
Thanks @gunjanbaid! I'm about to open a PR for #1548 that will also add a `conf.py`, so let's coordinate there.

**Comment by devin-petersohn** [comment]
@heuermh @fnothaft can this PR be closed?

**Comment by heuermh** [comment]
> can this PR be closed?

This is the issue, #1645 is the pull request.  Some of the changes in that pull request may still be applicable, they need to be rebased though.

**Comment by heuermh** [comment]
Fixed by #1646.
