### ISSUE TITLE
incorrect grep for assembly jars in bin/pyadam

### ISSUE THREAD

**Issue by akmorrow13** [bigdatagenomics/adam#1647]
the pyadam script has the incorrect grep for the assembly jars at https://github.com/bigdatagenomics/adam/blob/master/bin/pyadam#L33

Should
`grep "^adam_[0-9A-Za-z\.-]*\.jar$"` 
be
`^adam-assembly_[0-9A-Za-z\.-]*\.jar$" 
`?

Unless I am missing the jar it is supposed to be accessing.

**Comment by fnothaft** [comment]
Thanks for catching this @akmorrow13! It should be `"^adam[0-9A-Za-z\.\_\-]*\.jar$"`, as it is in `adam-submit`
