### ISSUE TITLE
bdgenomics.adam vs bdg.adam for R/Python APIs

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1655]
I put the package name for the Python library as `bdgenomics.adam` while the R library lives at `bdg.adam`. What are folks thoughts about which one is preferable? `bdgenomics.adam` is more consistent with the Scala/Java side of the house, but `bdg.adam` is shorter.

I'd like this to be consistent across any Python libraries we make available, e.g., https://github.com/fnothaft/toil-bdg/issues/12.

**Comment by heuermh** [comment]
+1 to `bdgenomics.adam` with future migration to `bigdatagenomics.adam` if/when we obtain the .org domain name and change all the Scala/Java package names and groupIds.

**Comment by pbashyal-nmdp** [comment]
+1 to `bdgenomics.adam`

**Comment by heuermh** [comment]
@fnothaft do you want to make this change in #1651 or would you prefer I do this in a separate PR?

**Comment by akmorrow13** [comment]
Referencing issue https://github.com/bigdatagenomics/adam/issues/1691, then should the name be bdgenomics-adam for python?

**Comment by heuermh** [comment]
Is bdgenomics-adam valid for both python and R?

**Comment by pbashyal-nmdp** [comment]
You can't have dash `-` in the package name in python. You could change it to underscore `_` instead. See [PEP 423](https://www.python.org/dev/peps/pep-0423/) for Python package standard.

**Comment by pbashyal-nmdp** [comment]
[PEP 8](https://www.python.org/dev/peps/pep-0008/#package-and-module-names) is also has a recommendation for package/module names.

**Comment by heuermh** [comment]
What I see there is that `${community}.${project}` seems to be reasonable.  Why does that prevent `${community}.${other project}` from working (#1691)?

https://www.python.org/dev/peps/pep-0423/#id81
https://www.python.org/dev/peps/pep-0423/#id87
Yes:
    Package name: "kheops.pyramid", i.e. `import kheops.pyramid`
    Project name: "kheops.pyramid", i.e. `pip install kheops.pyramid`

**Comment by fnothaft** [comment]
Ah, so IIRC, @akmorrow13 was seeing that the packages would pip install in incompatible ways. I'm wondering if the culprit is the way we're structuring our directories. E.g., if we do `adam-python/src/bdg.adam` instead of `adam-python/src/bdg/adam`, does that resolve the problem?

**Comment by heuermh** [comment]
I don't think so, this project used as an example in the packaging doc is `src/${community}/${project}`
https://bitbucket.org/gawel/gpfileupload/src/54887f3493542b392156178d403c49a9cda27ba2/gp/fileupload/?at=default

And shouldn't it be `src/bdgenomics/adam`?
