### ISSUE TITLE
Add performance benchmarks similar to Samtools CRAM benchmarking page

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#1661]
Add performance benchmarks similar to http://www.htslib.org/benchmarks/CRAM.html on the same data.

Although I'm not sure these particular benchmarks actually do anything.  Can anyone translate?

"Conversion from BAM to is achieved via htslib test_view -b or -C. Decoding times are computed using test_view -B (benchmarking mode) with performs input, uncompression and decoding only. Encoding time includes decoding of the input BAM, so subtract the BAM decoding time to get encode-only, although the difference is only minor."

**Comment by fnothaft** [comment]
I think the size benchmarks are reasonable. The decoding time benchmarks are a bit hard to interpret, and are probably more interpretable as application level benchmarks like in #1634.
