### ISSUE TITLE
Incorrect README.md  kmer.scala loadAliments method parameter name

### ISSUE THREAD

**Issue by joonsikjang** [bigdatagenomics/adam#1662]
projection -> optProjection

**Comment by heuermh** [comment]
Thanks for reporting this, @joonsikjang!  We're in the middle of a lot of doc fixes in preparation for the 0.23.0 release.  This particular fix should be covered in #1653.

**Comment by fnothaft** [comment]
I'm going to tag this with 0.23.0 so that we make sure it gets closed.

**Comment by fnothaft** [comment]
Resolved by #1653.
