### ISSUE TITLE
Include bdgenomics.adam-0.23.0_SNAPSHOT-py2.7.egg in distribution tarball

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#1667]
I don't believe `pyadam` will work out of the box after downloading and decompressing the distribution tarball.

**Comment by akmorrow13** [comment]
Going off of this @heuermh , what is the best way to use ADAM python APIs in an external project? https://github.com/bigdatagenomics/mango/pull/307 depends on the ADAM python apis, but it is not accessible through pip. Is there a plan to add these to pip, or is there an alternative way in which we can access adam python in an alternative project?

**Comment by heuermh** [comment]
I don't know.  Who are our go-to python experts?  ;) @pbashyal-nmdp may also be interested.

**Comment by akmorrow13** [comment]
I can definitely set up a PyPl account and push it so it is accessible by pip (see here: http://peterdowns.com/posts/first-time-with-pypi.html) The process seems quite painless. The only issue with putting this library on pip is that is it relatively useless without the jars. Should we put it up there anyways @heuermh and @fnothaft ?

**Comment by fnothaft** [comment]
How do you have your packaging set up? I assume you're using a virtualenv? We will push to pip at the release. In the intermediate, once you've activated your virtualenv, you can cd into `adam-python` and run `make develop`, which will install the bindings into the virtualenv.

**Comment by fnothaft** [comment]
WRT pip, PySpark is pushed to pip and has some fancy logic that moves the Spark jars into a python package. We need to play around with that a bit, but it is doable.

**Comment by akmorrow13** [comment]
Yes, I have been cding into adam-python and running pip install and that is working for testing. I am just trying to figure the best way to handle things when we merge into the Mango master branch. We don't need the jars because those are built into the mango jar, we just need the python APIs.

**Comment by fnothaft** [comment]
Ah, gotcha. In the PiPy config, we should be able to make it so that installing the JARs is optional, if that would help.

**Comment by pbashyal-nmdp** [comment]
When I run `make sdist`  it produces `dist/bdgenomics.adam-0.23.0-SNAPSHOT.tar.gz` When I try to `pip install` the distribution, it fails not finding the version module.

```
(venv) > pip install dist/bdgenomics.adam-0.23.0-SNAPSHOT.tar.gz
Processing ./dist/bdgenomics.adam-0.23.0-SNAPSHOT.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/7l/5w7957112mjb8yjf6lf13c2cycqhx4/T/pip-qQtkk4-build/setup.py", line 20, in <module>
        from version import version as adam_version
    ImportError: No module named version

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/7l/5w7957112mjb8yjf6lf13c2cycqhx4/T/pip-qQtkk4-build/
```

**Comment by pbashyal-nmdp** [comment]
I'd like the `dist/bdgenomics.adam-0.23.0-SNAPSHOT.tar.gz` to be part of the release. I can then download the release, use `pip install` to install the python package as well as install the packages for R etc..
