### ISSUE TITLE
Include bdg.adam-0.23.0.tar.gz in distribution tarballs

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#1668]
`adamR` will not work out of the box after downloading and decompressing the distribution tarball as the `bdg.adam` R library has not been installed.

Including it would allow users to install via `R CMD INSTALL` before running `adamR`.

We may also need to do an installation for "snapshot" builds run from a working directory.

**Comment by pbashyal-nmdp** [comment]
+1 Please include `bdg.adam_0.23.0.tar.gz` as part of the distribution.
