### ISSUE TITLE
Error with metadata: Multivalued flags are not supported for INFO lines

### ISSUE THREAD

**Issue by dmmiller612** [bigdatagenomics/adam#1669]
Hello,

I have ran into an issue with one of the headers in my vcf file, where Adam throws the error: Multivalued flags are not supported for INFO lines: INFO=<ID=SNP,Number=A,Type=Flag,Description="Variant is a SNP">

I saw in VariantContextConverter on line 1272 where the error was getting thrown. Do multivalued flags cause problems? Is there any type of work around this issue? Can we skip the INFO metadata somehow when loading a variant rdd?

**Comment by heuermh** [comment]
@dmmiller612 I don't believe multivalued flags are supported by the VCF specification.  There is a `ValidationStringency` parameter that you can use, try setting it to `ValidationStringency.LENIENT`, although I don't know if that allows processing to continue after this kind of error.

**Comment by dmmiller612** [comment]
Interesting. This annotation came from SnpSift, so I figured it was okay. I can't find exactly what is multivalued about that flag. It just says that the number is alphanumeric, is that the problem?

**Comment by heuermh** [comment]
Number=A is cardinality; it means there is one value for each [A]llele.

There is some discussion about the specification issue here
https://github.com/samtools/hts-specs/pull/123#r66714347

There is some draft doc on our VCF to bdg-formats mapping here, although it still needs cleanup and to find a home somewhere in ADAM docs
https://github.com/heuermh/bdg-formats/blob/docs/docs/source/variants.md

**Comment by fnothaft** [comment]
Per discussion between me and @heuermh, this VCF is out of compliance with the spec, and we are not able to patch this issue in ADAM. We'll close this as a won't fix. You should be able to work around this with validation stringency.
