### ISSUE TITLE
change bdgenomics.adam package name for adam-python to bdg-adam

### ISSUE THREAD

**Issue by akmorrow13** [bigdatagenomics/adam#1691]
the python package name bdgenomics.adam restricts other bdgenomic.* packages from being installed correctly

**Comment by heuermh** [comment]
Only caught the tail end of this conversation, how does this relate to #1655?

**Comment by akmorrow13** [comment]
This doesn't relate. We cant name it either bdg.adam or bdgenomics.adam, or it will overwrite other installed bdg packages. The name should be bdg-adam or bdgenomics-adam.

**Comment by fnothaft** [comment]
+1 @akmorrow13
