### ISSUE TITLE
Add ability to normalize INDEL variants

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1710]
Similar to #1709, but for variants.

**Comment by heuermh** [comment]
+1

**Comment by heuermh** [comment]
This algorithm looks reasonable
http://genome.sph.umich.edu/wiki/Variant_Normalization#Implementation

The comparisons are a bit old though, is this still the current best practice?

**Comment by fnothaft** [comment]
@heuermh that algorithm is more or less what is implemented for the CIGAR normalization on reads. My preference is not that we add a new algorithm, but rather that we refactor the current read normalization algorithm so that it can also take variants.

To be more specific WRT the changes needed, for reads, normalization is bounded since we can't shift the INDEL before the start of the read alignment. I mean, I do suppose we could, but that would be unusual since we would've expected the read to either be soft-clipped during alignment or aligned without an INDEL. For variants, we don't have a bound that is known a priori from the variant itself. E.g., consider a deletion in a STR. Normalization should move that deletion all the way to the start of the STR, but we don't know how long the STR is from the variant that we are normalizing.

**Comment by heuermh** [comment]
Closing as WontFix, Cannoli provides multiple methods for normalizing variants (`bcftoolsNorm`, `vtNormalize`)
