### ISSUE TITLE
Log with parameterized messages consistently for performance

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#1712]
Per https://www.slf4j.org/faq.html#logging_performance, logging with parameterized messages
```scala
log.info("message {} {}", one, two)
```
is preferable to alternatives found in our code base
```scala
log.info("message s% %s".format(one, two))

if (log.isInfoEnabled()) {
  log.info("message s% %s".format(one, two))
}

logInfo("message s% %s".format(one, two)")
```
See also mention in comment https://github.com/bigdatagenomics/adam/pull/1684#issuecomment-327497557

**Comment by fnothaft** [comment]
+1; also, perhaps everywhere that we've got a log.info(String) call, we can switch to logInfo?

**Comment by heuermh** [comment]
> +1; also, perhaps everywhere that we've got a log.info(String) call, we can switch to logInfo?

Yep, that is what I was thinking.

**Comment by fnothaft** [comment]
Sounds good!

**Comment by heuermh** [comment]
Turns out the parameterized message methods in slf4j aren't so convenient to use from scala
```
[ERROR] adam/adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/realignment/RealignIndels.scala:470:
error: ambiguous reference to overloaded definition,
[WARNING] both method warn in trait Logger of type (x$1: String, x$2: Any, x$3: Any)Unit
[WARNING] and  method warn in trait Logger of type (x$1: String, x$2: <repeated...>[Object])Unit
[INFO] match argument types (String,Option[(Int, org.bdgenomics.adam.rdd.read.realignment.IndelRealignmentTarget)],Throwable)
[WARNING]           log.warn("Realigning target {} failed with {}.", target, t)
[INFO]               ^
```
I think the best way forward is to commit to `logInfo` style and then refactor bdg-utils `Logging` to match and use slf4j parameterized message methods under the hood.

**Comment by heuermh** [comment]
Note http://software.clapper.org/grizzled-slf4j/ might be of use.
