### ISSUE TITLE
Unable to create .adam from .sam

### ISSUE THREAD

**Issue by Rokshan2016** [bigdatagenomics/adam#1717]
Can anyone help for this---

Exception in thread "main" java.io.FileNotFoundException: Couldn't find any files matching /home/rokshan.jahan/project/spark-genome-alignment-demo/build/adam/adam-co/src/test/resources/small.sam. If you are trying to glob a directory of Parquet files, you need to glob inside the directory as well (e.g., "glob.me.*.adam/*", instead of "glob.me.*.adam".

**Comment by heuermh** [comment]
Sure, what is the call that causes this exception?

**Comment by Rokshan2016** [comment]
Thanks for quick reply
I am trying to convert .sam to .adam

 ./adam-submit transformAlignments /home/rokshan.jahan/project/spark-genome-alignment-demo/build/adam/adam-co/src/test/resources/small.sam /home/rokshan.jahan/project/spark-genome-alignment-demo/build/adam/adam-core/src/test/resources/small.adam

**Comment by heuermh** [comment]
You might have a typo:

/home/rokshan.jahan/project/spark-genome-alignment-demo/build/adam/**adam-co**/src/test/resources/small.sam

 to

/home/rokshan.jahan/project/spark-genome-alignment-demo/build/adam/**adam-core**/src/test/resources/small.sam

**Comment by Rokshan2016** [comment]
ok , let me check that, thanks

**Comment by Rokshan2016** [comment]
[error.txt](https://github.com/bigdatagenomics/adam/files/1297600/error.txt)

Please find the full stack trace 
Thanks

**Comment by heuermh** [comment]
If you are using Spark on YARN over a cluster, then the paths need to be on shared storage, such as HDFS.

**Comment by Rokshan2016** [comment]
ok, let me try that

Thanks

**Comment by Rokshan2016** [comment]
It works .
Thanks:)
