### ISSUE TITLE
Confirm all I/O resources created by ADAM are closed properly

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#1719]
From discussion re: https://github.com/HadoopGenomics/Hadoop-BAM/pull/152

**Comment by fnothaft** [comment]
@heuermh I'd love to see this in 0.24.0, but realistically I don't know if anyone is planning to take it. Should this bump to 0.25.0?

**Comment by heuermh** [comment]
+1 to 0.25.0
