### ISSUE TITLE
Is it correct Adam file

### ISSUE THREAD

**Issue by Rokshan2016** [bigdatagenomics/adam#1720]
Hi
I executed the following command

./adam-submit transformAlignments hdfs://hadoop-master:8020/user/rokshan.jahan/small.sam  hdfs://hadoop-master:8020/user/rokshan.jahan/small.adam

It executed successfully. And small.adam contains following files

_common_metadata
_metadata
_processing.avro
_rgdict.avro
_seqdict.avro
_SUCCESS
part-r-00000.gz.parquet

Just want to make sure that this how the .adam looks like!

Thanks

**Comment by heuermh** [comment]
That looks reasonable to me.

To confirm you can either read it back in with `loadAlignments` or use [parquet-tools](https://github.com/apache/parquet-mr/tree/master/parquet-tools) to inspect what is present on disk.

```bash
$ parquet-tools head small.adam/part-r-00000.gz.parquet 
readInFragment = 0
contigName = 1
start = 26472783
end = 26472858
mapq = 60
readName = simread:1:26472783:false
sequence = GTATAAGAGCAGCCTTATTCCTATTTATAATCAGGGTGAAACACCTGTGCCAATGCCAAGACAGGGGTGCCAAGA
cigar = 75M
basesTrimmedFromStart = 0
basesTrimmedFromEnd = 0
readPaired = false
properPair = false
readMapped = true
mateMapped = false
failedVendorQualityChecks = false
duplicateRead = false
readNegativeStrand = true
mateNegativeStrand = false
primaryAlignment = true
secondaryAlignment = false
supplementaryAlignment = false
attributes = XS:i:0	AS:i:75	NM:i:0

$ parquet-tools meta small.adam/part-r-00000.gz.parquet 
file:                      small.adam/part-r-00000.gz.parquet 
creator:                   parquet-mr version 1.8.2 (build c6522788629e590a53eb79874b95f6c3ff11f16c) 
extra:                     parquet.avro.schema = {"type":"record",...
file schema:               org.bdgenomics.formats.avro.AlignmentRecord 
--------------------------------------------------------------------------------
readInFragment:            OPTIONAL INT32 R:0 D:1
contigName:                OPTIONAL BINARY O:UTF8 R:0 D:1
start:                     OPTIONAL INT64 R:0 D:1
oldPosition:               OPTIONAL INT64 R:0 D:1
end:                       OPTIONAL INT64 R:0 D:1
mapq:                      OPTIONAL INT32 R:0 D:1
readName:                  OPTIONAL BINARY O:UTF8 R:0 D:1
sequence:                  OPTIONAL BINARY O:UTF8 R:0 D:1
qual:                      OPTIONAL BINARY O:UTF8 R:0 D:1
cigar:                     OPTIONAL BINARY O:UTF8 R:0 D:1
oldCigar:                  OPTIONAL BINARY O:UTF8 R:0 D:1
basesTrimmedFromStart:     OPTIONAL INT32 R:0 D:1
basesTrimmedFromEnd:       OPTIONAL INT32 R:0 D:1
readPaired:                OPTIONAL BOOLEAN R:0 D:1
properPair:                OPTIONAL BOOLEAN R:0 D:1
readMapped:                OPTIONAL BOOLEAN R:0 D:1
mateMapped:                OPTIONAL BOOLEAN R:0 D:1
failedVendorQualityChecks: OPTIONAL BOOLEAN R:0 D:1
duplicateRead:             OPTIONAL BOOLEAN R:0 D:1
readNegativeStrand:        OPTIONAL BOOLEAN R:0 D:1
mateNegativeStrand:        OPTIONAL BOOLEAN R:0 D:1
primaryAlignment:          OPTIONAL BOOLEAN R:0 D:1
secondaryAlignment:        OPTIONAL BOOLEAN R:0 D:1
supplementaryAlignment:    OPTIONAL BOOLEAN R:0 D:1
mismatchingPositions:      OPTIONAL BINARY O:UTF8 R:0 D:1
origQual:                  OPTIONAL BINARY O:UTF8 R:0 D:1
attributes:                OPTIONAL BINARY O:UTF8 R:0 D:1
recordGroupName:           OPTIONAL BINARY O:UTF8 R:0 D:1
recordGroupSample:         OPTIONAL BINARY O:UTF8 R:0 D:1
mateAlignmentStart:        OPTIONAL INT64 R:0 D:1
mateContigName:            OPTIONAL BINARY O:UTF8 R:0 D:1
inferredInsertSize:        OPTIONAL INT64 R:0 D:1

row group 1:               RC:20 TS:4114 OFFSET:4 
--------------------------------------------------------------------------------
readInFragment:             INT32 GZIP DO:0 FPO:4 SZ:98/58/0.59 VC:20 ENC:PLAIN_DICTIONARY,BIT_PACKED,RLE
contigName:                 BINARY GZIP DO:0 FPO:102 SZ:93/53/0.57 VC:20 ENC:PLAIN_DICTIONARY,BIT_PACKED,RLE
start:                      INT64 GZIP DO:0 FPO:195 SZ:180/209/1.16 VC:20 ENC:PLAIN,BIT_PACKED,RLE
oldPosition:                INT64 GZIP DO:0 FPO:375 SZ:47/27/0.57 VC:20 ENC:PLAIN,BIT_PACKED,RLE
end:                        INT64 GZIP DO:0 FPO:422 SZ:180/209/1.16 VC:20 ENC:PLAIN,BIT_PACKED,RLE
mapq:                       INT32 GZIP DO:0 FPO:602 SZ:117/83/0.71 VC:20 ENC:PLAIN_DICTIONARY,BIT_PACKED,RLE
readName:                   BINARY GZIP DO:0 FPO:719 SZ:276/644/2.33 VC:20 ENC:PLAIN,BIT_PACKED,RLE
sequence:                   BINARY GZIP DO:0 FPO:995 SZ:733/1763/2.41 VC:20 ENC:PLAIN,BIT_PACKED,RLE
qual:                       BINARY GZIP DO:0 FPO:1728 SZ:47/27/0.57 VC:20 ENC:PLAIN,BIT_PACKED,RLE
cigar:                      BINARY GZIP DO:0 FPO:1775 SZ:99/59/0.60 VC:20 ENC:PLAIN_DICTIONARY,BIT_PACKED,RLE
oldCigar:                   BINARY GZIP DO:0 FPO:1874 SZ:47/27/0.57 VC:20 ENC:PLAIN,BIT_PACKED,RLE
basesTrimmedFromStart:      INT32 GZIP DO:0 FPO:1921 SZ:98/58/0.59 VC:20 ENC:PLAIN_DICTIONARY,BIT_PACKED,RLE
basesTrimmedFromEnd:        INT32 GZIP DO:0 FPO:2019 SZ:98/58/0.59 VC:20 ENC:PLAIN_DICTIONARY,BIT_PACKED,RLE
readPaired:                 BOOLEAN GZIP DO:0 FPO:2117 SZ:54/36/0.67 VC:20 ENC:PLAIN,BIT_PACKED,RLE
properPair:                 BOOLEAN GZIP DO:0 FPO:2171 SZ:54/36/0.67 VC:20 ENC:PLAIN,BIT_PACKED,RLE
readMapped:                 BOOLEAN GZIP DO:0 FPO:2225 SZ:56/36/0.64 VC:20 ENC:PLAIN,BIT_PACKED,RLE
mateMapped:                 BOOLEAN GZIP DO:0 FPO:2281 SZ:54/36/0.67 VC:20 ENC:PLAIN,BIT_PACKED,RLE
failedVendorQualityChecks:  BOOLEAN GZIP DO:0 FPO:2335 SZ:54/36/0.67 VC:20 ENC:PLAIN,BIT_PACKED,RLE
duplicateRead:              BOOLEAN GZIP DO:0 FPO:2389 SZ:54/36/0.67 VC:20 ENC:PLAIN,BIT_PACKED,RLE
readNegativeStrand:         BOOLEAN GZIP DO:0 FPO:2443 SZ:56/36/0.64 VC:20 ENC:PLAIN,BIT_PACKED,RLE
mateNegativeStrand:         BOOLEAN GZIP DO:0 FPO:2499 SZ:54/36/0.67 VC:20 ENC:PLAIN,BIT_PACKED,RLE
primaryAlignment:           BOOLEAN GZIP DO:0 FPO:2553 SZ:56/36/0.64 VC:20 ENC:PLAIN,BIT_PACKED,RLE
secondaryAlignment:         BOOLEAN GZIP DO:0 FPO:2609 SZ:54/36/0.67 VC:20 ENC:PLAIN,BIT_PACKED,RLE
supplementaryAlignment:     BOOLEAN GZIP DO:0 FPO:2663 SZ:54/36/0.67 VC:20 ENC:PLAIN,BIT_PACKED,RLE
mismatchingPositions:       BINARY GZIP DO:0 FPO:2717 SZ:47/27/0.57 VC:20 ENC:PLAIN,BIT_PACKED,RLE
origQual:                   BINARY GZIP DO:0 FPO:2764 SZ:47/27/0.57 VC:20 ENC:PLAIN,BIT_PACKED,RLE
attributes:                 BINARY GZIP DO:0 FPO:2811 SZ:181/254/1.40 VC:20 ENC:PLAIN_DICTIONARY,BIT_PACKED,RLE
recordGroupName:            BINARY GZIP DO:0 FPO:2992 SZ:47/27/0.57 VC:20 ENC:PLAIN,BIT_PACKED,RLE
recordGroupSample:          BINARY GZIP DO:0 FPO:3039 SZ:47/27/0.57 VC:20 ENC:PLAIN,BIT_PACKED,RLE
mateAlignmentStart:         INT64 GZIP DO:0 FPO:3086 SZ:47/27/0.57 VC:20 ENC:PLAIN,BIT_PACKED,RLE
mateContigName:             BINARY GZIP DO:0 FPO:3133 SZ:47/27/0.57 VC:20 ENC:PLAIN,BIT_PACKED,RLE
inferredInsertSize:         INT64 GZIP DO:0 FPO:3180 SZ:47/27/0.57 VC:20 ENC:PLAIN,BIT_PACKED,RLE
```

**Comment by Rokshan2016** [comment]
ok, will try that

**Comment by Rokshan2016** [comment]
I tried & found the following , so it means it is working fine?

[rokshan.jahan@   parquet-mr]$ parquet-tools head /home/rokshan.jahan/project/small.adam/part-r-00000.gz.parquet
readInFragment = 0
contigName = 1
start = 26472783
end = 26472858
mapq = 60
readName = simread:1:26472783:false
sequence = GTATAAGAGCAGCCTTATTCCTATTTATAATCAGGGTGAAACACCTGTGCCAATGCCAAGACAGGGGTGCCAAGA
cigar = 75M
basesTrimmedFromStart = 0
basesTrimmedFromEnd = 0
readPaired = false
properPair = false
readMapped = true
mateMapped = false
failedVendorQualityChecks = false
duplicateRead = false
readNegativeStrand = true
mateNegativeStrand = false
primaryAlignment = true
secondaryAlignment = false
supplementaryAlignment = false
attributes = XS:i:0     AS:i:75 NM:i:0

readInFragment = 0
contigName = 1
start = 240997787
end = 240997862
mapq = 60
readName = simread:1:240997787:true
sequence = CTTTATTTTTATTTTTAAGGTTTTTTTTGTTTGTTTGTTTTGAGATGGAGTCTCGCTCCACCGCCCAGACTGGAG
cigar = 75M
basesTrimmedFromStart = 0
basesTrimmedFromEnd = 0
readPaired = false
properPair = false
readMapped = true
mateMapped = false
failedVendorQualityChecks = false
duplicateRead = false
readNegativeStrand = false
mateNegativeStrand = false
primaryAlignment = true
secondaryAlignment = false
supplementaryAlignment = false
attributes = XS:i:39    AS:i:75 NM:i:0

readInFragment = 0
contigName = 1
start = 189606653
end = 189606728
mapq = 60
readName = simread:1:189606653:true
sequence = TGTATCTTCCTCCCCTGCTGTATGTTTCCTGCCCTCAAACATCACACTCCACGTTCTTCAGCTTTAGGACTTGGA
cigar = 75M
basesTrimmedFromStart = 0
basesTrimmedFromEnd = 0
readPaired = false
properPair = false
readMapped = true
mateMapped = false
failedVendorQualityChecks = false
duplicateRead = false
readNegativeStrand = false
mateNegativeStrand = false
primaryAlignment = true
secondaryAlignment = false
supplementaryAlignment = false
attributes = XS:i:0     AS:i:75 NM:i:0

readInFragment = 0
contigName = 1
start = 207027738
end = 207027813
mapq = 60
readName = simread:1:207027738:true
sequence = TTTAATAAATGTTGATTGTCCTATTTAATTATTCTCAACTTTCCGATTTTATTTCCCATGTAACAGTGTTGTTTT
cigar = 75M
basesTrimmedFromStart = 0
basesTrimmedFromEnd = 0
readPaired = false
properPair = false
readMapped = true
mateMapped = false
failedVendorQualityChecks = false
duplicateRead = false
readNegativeStrand = false
mateNegativeStrand = false
primaryAlignment = true
secondaryAlignment = false
supplementaryAlignment = false
attributes = XS:i:0     AS:i:75 NM:i:0

readInFragment = 0
contigName = 1
start = 14397233
end = 14397308
mapq = 60
readName = simread:1:14397233:false
sequence = TAAAATGCCCCCATCTTCCCAGAGCTGCCAGCCCTCACAATGCCAACAGCTAAATGTACCCAAGTGTTACTGAAC
cigar = 75M
basesTrimmedFromStart = 0
basesTrimmedFromEnd = 0
readPaired = false
properPair = false
readMapped = true
mateMapped = false
failedVendorQualityChecks = false
duplicateRead = false
readNegativeStrand = true
mateNegativeStrand = false
primaryAlignment = true
secondaryAlignment = false
supplementaryAlignment = false
attributes = XS:i:0     AS:i:75 NM:i:0

**Comment by heuermh** [comment]
Yes, that looks ok!

**Comment by Rokshan2016** [comment]
Thanks!
