### ISSUE TITLE
.fastq Alignment 

### ISSUE THREAD

**Issue by Rokshan2016** [bigdatagenomics/adam#1723]
Hi,
Is there any Adam command I can use to do .fastq / sequence alignment .

**Comment by heuermh** [comment]
To clarify, you have unaligned sequencing reads in FASTQ format and want to align them against a reference genome assembly?

If so, my recommendation would be to run BWA on Spark via Cannoli
https://github.com/bigdatagenomics/cannoli

A workflow written in Toil can be found here
https://github.com/bigdatagenomics/workflows/blob/master/bdgenomics/workflows/cannoli_pipeline/bwa_alignment.py

**Comment by Rokshan2016** [comment]
ok, let me try this

Thanks!
