### ISSUE TITLE
Accessing GenomicRDD join functions in python

### ISSUE THREAD

**Issue by akmorrow13** [bigdatagenomics/adam#1728]
I would like to be able to access join functionality in adam-python. Would the best way to do this be to create a wrapper accessing the GenomicRDD joins or do something new with SparkSQL? Any thoughts?

**Comment by fnothaft** [comment]
You'll need both. Specifically, you'll need a wrapper around the region join for python (easy) and you'll need an implementation of [GenericGenomicRDD](https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala#L1413) that extends `GenomicDataset` (hard). Let's chat about this on Monday.

**Comment by heuermh** [comment]
@fnothaft push to 0.25.0?
