### ISSUE TITLE
Aligned Human Genome couldn't convert to Adam 

### ISSUE THREAD

**Issue by Rokshan2016** [bigdatagenomics/adam#1729]
I did this steps-
1. Index : Reference human genome using bow tie ( A. fna)
2. Align : A. fna and A.fastq-- Done successfully--Got the output in A.fastq

When I am trying to convert A.fastq(Aligned) to adam , its not working .

Any suggestion will be helpful.

Thanks

**Comment by Rokshan2016** [comment]
1. Index : I used Bow tie for index reference genome
2. Alignment: data (.fastq ) with the indexed reference genome
Output : .fastq file (Aligned with index)

But whenever  I m trying to convert  .fastq file (Aligned with index) to adam using the command:
./adam-submit transformAlignments hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/data/SRR1517848.fastq hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/SRR1517848.adam

It didnt give the correct parquet files inside .adam

**Comment by fnothaft** [comment]
You shouldn't be getting a fastq file out of Bowtie, you should be getting a SAM file, so that part of the workflow looks suspicious. What error are you getting when you run `transformAlignments`?

**Comment by Rokshan2016** [comment]
I got the .adam . There was parquet files. But Data was not correct

**Comment by Rokshan2016** [comment]
I used BWA for indexing and alignment
Did this steps:
1. Indexed the reference genome
2. Align the .fastq with the  Indexed the reference genome and got the output as .sam
3.  Convert the .sam to .adam
Output was correct
But my concern is : I want to skip the .sam conversion,
**   I want to align the .fastq with the  Indexed  reference genome and got the output as .adam

Is there any way I can do that?
