### ISSUE TITLE
Cloud-scale BWA MEM

### ISSUE THREAD

**Issue by Rokshan2016** [bigdatagenomics/adam#1730]
Hi, 
I am unable to install cloud-Scale BWAMEM . It showing following error:

[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for cs.ucla.edu:jniSWExtend:so:0.2.2
[WARNING] 'dependencies.dependency.systemPath' for cs.ucla.edu:cloud-scale-bwamem:jar should use a variable instead of a hard-coded path /home/rokshan.jahan/project/spark-genome-alignment-demo/build/cloud-scale-bwamem/target/cloud-scale-bwamem-0.2.2.jar @ line 19, column 19
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 25, column 15
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:native-maven-plugin is missing. @ line 33, column 15
[WARNING] 'dependencies.dependency.systemPath' for cs.ucla.edu:cloud-scale-bwamem:jar refers to a non-existing file /home/rokshan.jahan/project/spark-genome-alignment-demo/build/cloud-scale-bwamem/target/cloud-scale-bwamem-0.2.2.jar @ line 19, column 19
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building JNI Smith-Waterman Extend on FPGA 0.2.2
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.562 s
[INFO] Finished at: 2017-09-16T23:01:18-04:00
[INFO] Final Memory: 17M/483M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project jniSWExtend: Could not resolve dependencies for project cs.ucla.edu:jniSWExtend:so:0.2.2: Could not find artifact cs.ucla.edu:cloud-scale-bwamem:jar:0.2.2 at specified path /home/rokshan.jahan/project/spark-genome-alignment-demo/build/cloud-scale-bwamem/target/cloud-scale-bwamem-0.2.2.jar -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[rokshan.jahan@ip-10-48-3-63 cloud-scale-bwamem]$ ^C
[rokshan.jahan@ip-10-48-3-63 cloud-scale-bwamem]$

Any suggestion will be helpful.

Thanks

**Comment by heuermh** [comment]
For issues with cloud-scale-bwamem, you'll want to file issues at
https://github.com/ytchen0323/cloud-scale-bwamem/issues

That said, you will find better performance using BWA via Cannoli
https://github.com/bigdatagenomics/cannoli

**Comment by Rokshan2016** [comment]
Thanks . Will Check that
