### ISSUE TITLE
vcf2adam support

### ISSUE THREAD

**Issue by skprasadu** [bigdatagenomics/adam#1731]
Team,

I am trying the exercise from @ https://aws.amazon.com/blogs/big-data/interactive-analysis-of-genomic-datasets-using-amazon-athena/ and when I am trying to convert from vcf2adam to convert to Parquet format. It is exiting telling vcf2adam is not supported only fasta2adam is supported. Can someone help?

Krishna

**Comment by fnothaft** [comment]
Hi @skprasadu! We split the `vcf2adam` command into two commands: `transformGenotypes` and `transformVariants`

**Comment by fnothaft** [comment]
I believe this issue is resolved; please reopen if you need any help. Thanks!
