### ISSUE TITLE
Opening up permission on GenericGenomicRDD constructor

### ISSUE THREAD

**Issue by devin-petersohn** [bigdatagenomics/adam#1735]
Is there a reason to keep GenericGenomicRDD constructor package private? I could use the constructor downstream, if it's not closed for a serious issue.

**Comment by fnothaft** [comment]
I generally prefer to keep things closed up if possible, but if you need it then you need it. What are you doing downstream?

As a minor aside, we'd likely want to keep the constructor closed but add an apply method, but that's beside the point.

**Comment by devin-petersohn** [comment]
I need to enable nested set theory operations, which is impossible to generalize without using some kind of `GenericGenomicRDD`-like object (because I must define a `regionFn` for most operations). It is also a cleaner abstraction than `GenomicRDD[(T, Iterable[X]), Nothing]`.

**Comment by devin-petersohn** [comment]
I should also add that `transform` on a non-Generic `GenomicRDD` returns a `Nothing` object.

**Comment by fnothaft** [comment]
Is it correct to read your first comment as:

> because I must define a regionFn for most operations

being the important clause? Specifically, you need to customize the `regionFn` after a join?

> I should also add that transform on a non-Generic GenomicRDD returns a Nothing object.

Can you give an example? I haven't seen this before but I haven't been looking for it.

**Comment by devin-petersohn** [comment]
> Specifically, you need to customize the `regionFn` after a join?

For set theory operations, many times you want the resulting region data to be changed in some way (subtract, intersect, etc.).

> Can you give an example? I haven't seen this before but I haven't been looking for it.

This is only post-join. I updated my comment too late. When we cast to a `[GenomicRDD[(T, Iterable[X]), Z]` from a `GenericGenomicRDD` in the join, the type checking somehow infers `Z` to be `Nothing`.

**Comment by fnothaft** [comment]
> For set theory operations, many times you want the resulting region data to be changed in some way (subtract, intersect, etc.).

Oh yeah, the rationale makes sense. I just want to make sure I'm understanding why you need the interface opened up.
