### ISSUE TITLE
command failure after build success

### ISSUE THREAD

**Issue by Rokshan2016** [bigdatagenomics/adam#1744]
Hi,
I have successfully build Adam . But after running the following command I am having this error:

Command:   ./adam-submit transformAlignments hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/data1/SRR1517848.fastq hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/SRR1517848.adam -force_load_fastq

Error:
17/09/25 00:39:00 INFO cli.ADAMMain: ADAM invoked with args: "transformAlignments" "hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/data1/SRR1517848.fastq" "hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/SRR1517848.adam" "-force_load_fastq"
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/parquet/hadoop/metadata/CompressionCodecName
        at org.bdgenomics.utils.cli.ParquetArgs$class.$init$(ParquetArgs.scala:40)
        at org.bdgenomics.adam.cli.InitArgs.<init>(ADAMMain.scala:71)
        at sun.reflect.N

**Comment by fnothaft** [comment]
Hi @Rokshan2016! This issue is being discussed on #1742. Please follow the discussion on that ticket. Thanks!
