### ISSUE TITLE
New Shuffle Join Implementation - Left Outer + Group By Left

### ISSUE THREAD

**Issue by devin-petersohn** [bigdatagenomics/adam#1745]
This is needed to correctly implement a subtract primitive. Without a group by the subtraction returns incorrect intervals.

@fnothaft, @heuermh thoughts on return type? It can be:
`GenericGenomicRDD[(T, Iterable[Option[X]]` 
or
`GenericGenomicRDD[(T, Iterable[X]]` (flattened, so some empty `Iterable`s).

I have no strong preference.

**Comment by heuermh** [comment]
I vote for `(T, Iterable[X])`, an option is already iterable.

**Comment by fnothaft** [comment]
SGTM, definitely `(T, Iterable[X])`.
