### ISSUE TITLE
Add transform to fix chromosome prefixes to genomic RDDs and CLIs

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1757]
Inspired by a tweet; Illumina's hap.py tool has a `--fixchr` option.

**Comment by heuermh** [comment]
I added this for BED files to dsh-bio recently
https://github.com/heuermh/dishevelled-bio/blob/master/tools/src/main/java/org/dishevelled/bio/tools/RenameReferences.java

Hacks with regular expressions, what could be better?

**Comment by heuermh** [comment]
Closing as WontFix
