### ISSUE TITLE
Request for a new release

### ISSUE THREAD

**Issue by droazen** [bigdatagenomics/adam#1762]
It's been a while since this project was last released -- are there any plans to cut a new release with the changes since April? Thanks!

**Comment by fnothaft** [comment]
Hi @droazen! Sorry about the lag in release cadence, we've been "very" close to a new release for... a while now -> we've added Python and R support in this release, which has really dragged the timeline out. We're down to mostly documentation and release workflow issues that are holding up the release; I'm hopeful to close those in the next 2 weeks. Is that OK on your end?

**Comment by fnothaft** [comment]
We're tracking the remaining issues for the release at https://github.com/bigdatagenomics/adam/milestone/16.

**Comment by droazen** [comment]
Thanks @fnothaft for the update -- glad to hear that you're so close to a release!

**Comment by fnothaft** [comment]
@droazen no problem, sorry we've slipped a fair bit! BTW, the changes to bump GATK4 to ADAM 0.23.0 should be pretty minor; looks like about 15LOC need to change in the GATK4's 2bit file code.

**Comment by heuermh** [comment]
@droazen Thanks for the poke re: the upcoming release, closing this issue as a duplicate of #1430, which will track the actual release commit.
