### ISSUE TITLE
Reconstructing variant contexts will be incorrect if a variant has different qualities across samples

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1773]
At https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/rdd/variant/GenotypeRDD.scala#L301, we group by the `RichVariant`. If we have two records for a single variant that have different qualities/filters/annotations, this groupBy will put them in different variant contexts.

**Comment by heuermh** [comment]
Closing as WontFix
