### ISSUE TITLE
Reinstantiation of SQLContext in pyadam ADAMContext

### ISSUE THREAD

**Issue by akmorrow13** [bigdatagenomics/adam#1774]
Creating an ADAMContext in pyadam generates the error 
`Caused by: ERROR XSDB6: Another instance of Derby may have already booted the database metastore_db.`

The following creates this error (with Spark 2.1.1, scala 2.11):

```
from bdgenomics.adam.adamContext import ADAMContext
ac = ADAMContext(sc)
reads = ac.loadAlignments("mouse_chrM.bam”)
reads.toDF().rdd.count()
```

**Comment by heuermh** [comment]
Closing as duplicate of #1666.
