### ISSUE TITLE
Remove explicit `<compile>` scopes from submodule POMs

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1786]
Hi @heuermh wanted your thoughts on this. I know you added these a few months back in https://github.com/bigdatagenomics/adam/commit/9505d47e881305367fbad4bdfb8f189c3e766b0a and that we had discussed this at the time, but I can't remember what the exact rationale was, and the attached issue doesn't seem to discuss the rationale (its long so I skimmed it and may have missed the discussion). This is really a question of convenience; I was debugging something today so changed a dependency from compile to provided scope. However, since I didn't update the submodule POMs, it was still packaged at compile scope. This was a bit of a hassle since the specific debugging loop was pretty long (it involved deploying the assembly JAR over a slow internet connection). That said, I remember you had a reason for adding the explicit scopes, so I wanted to circle back. Can you jog my memory? No need to change this now, just wanted to create a ticket for discussion.

**Comment by heuermh** [comment]
The motivation was simply to be informational, since scope is compile by default if not specified and some of the scopes were inherited as provided from parent.  It has a side effect of making it more painful to change the scope on a dependency, as you found out.

**Comment by fnothaft** [comment]
Yeah, I'm not sure which way is best. On one hand, I like having the scope explicitly visible. On the other hand, making changes is a bit of a PITA. Anyone else have strong feelings?

As an aside, I think we've got a few dependencies where we forgot to set the scope in the submodule POMs.

**Comment by fnothaft** [comment]
I don't feel strong in favor of removing the scopes, so closing for now.
