### ISSUE TITLE
Issue with adam2vcf

### ISSUE THREAD

**Issue by Rokshan2016** [bigdatagenomics/adam#1787]
Hi,

I am using this command -   ./adam-submit --driver-memory 3g --executor-memory 3g -- adam2vcf -single hdfs://ipsawdvpvfhnn03.ips.local:8020/user/rokshan.jahan/avocado_data/SRR1517974.adam hdfs://ipsawdvpvfhnn03.ips.local:8020/user/rokshan.jahan/SRR1517974.vcf -sort_on_save

SRR1517974.adam - this file I got using avocado biallelicgenotyper

Error-

Oct 30, 2017 2:49:45 PM INFO: org.apache.parquet.hadoop.InternalParquetRecordReader: block read in memory in 153 ms. row count = 1
Oct 30, 2017 2:49:45 PM IN17/10/30 14:49:45 INFO Executor: Finished task 16.0 in stage 0.0 (TID 16). 1278 bytes result sent to driver
17/10/30 14:49:45 INFO TaskSetManager: Starting task 17.0 in stage 0.0 (TID 17, localhost, executor driver, partition 17, ANY, 6146 bytes)
17/10/30 14:49:45 INFO Executor: Running task 17.0 in stage 0.0 (TID 17)
17/10/30 14:49:45 INFO NewHadoopRDD: Input split: ParquetInputSplit{part: hdfs://ipsawdvpvfhnn03.ips.local:8020/user/rokshan.jahan/avocado_data/SRR1517974.adam/part-r-00017.gz.parquet start: 0 end: 32528 length: 32528 hosts: []}
17/10/30 14:49:45 INFO TaskSetManager: Finished task 6.0 in stage 0.0 (TID 6) in 676 ms on localhost (executor driver) (1/200)
17/10/30 14:49:45 INFO TaskSetManager: Finished task 16.0 in stage 0.0 (TID 16) in 49 ms on localhost (executor driver) (2/200)
17/10/30 14:49:45 INFO CodecPool: Got brand-new decompressor [.gz]
17/10/30 14:49:45 ERROR Executor: Exception in task 8.0 in stage 0.0 (TID 8)
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Float
        at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:80)
        at org.apache.avro.generic.GenericDatumWriter.writeArray(GenericDatumWriter.java:138)
        at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:68)
        at org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:114)
        at org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:104)
        at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:66)
        at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:58)

Any suggestion will be helpful for this issue.

Thanks

**Comment by fnothaft** [comment]
Hi @Rokshan2016! This error means that you were running on a Parquet file that had an older schema than your current build of ADAM. Closing for now.
