### ISSUE TITLE
Support minPartitions parameter across load calls

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1792]
Makes it easier to increase the parallelism when loading a file.

**Comment by fnothaft** [comment]
It seems like the only place this can be done is loadFasta. The other textual file formats (minus VCF and FASTQ) already support this parameter, and the other file formats use the new Hadoop APIs, which are incompatible with minPartitions.

**Comment by heuermh** [comment]
Closing as WontFix, `loadFasta` also uses `sc.newAPIHadoopFile(...)`.
