### ISSUE TITLE
Readme link to bigdatagenomics/lime 404s

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#1819]
@devin-petersohn The link to Lime in the latest rev of README.md 404s (https://github.com/bigdatagenomics/lime).  Could your repo be migrated to the bigdatagenomics organization in a timely fashion, or should we update the readme to link to your repo?  Ping me for help, I've done it a few times already.

**Comment by devin-petersohn** [comment]
Migrated Lime to bigdatagenomics.
