### ISSUE TITLE
base counts per position

### ISSUE THREAD

**Issue by jpdna** [bigdatagenomics/adam#1825]
I had an issue related to this a while back but don't see it, so here again:

It would be really useful to be able to query an alignment file (BAM/ADAM) to count the number of bases (A/C/G/T, insert / delete) at each base in the genome.
The returned data would be a tuple of such counts for each position in the reference genome.

This exact functionality is now provided in this tool:
https://github.com/genome/bam-readcount
but is slow.

@fnothaft - I'm sure this sort of functionality exists as a step in Avocado, can you point me where to look?

The applications I have for this are:
1) naive / exploratory variant calling where you want just these counts to explore what sort of test to do
  - especially in the context of somatic calling where you are want to interpret only a 5-10% variant allele fraction
2) evaluate the background noise/bias at positions

**Comment by fnothaft** [comment]
Hi @jpdna! In avocado, I've just got the logic for a more restricted case: ref vs. alt. That said, it wouldn't be arduous to add. Do you mind opening said issue against Avocado?

**Comment by fnothaft** [comment]
Moved downstream to https://github.com/bigdatagenomics/avocado/pull/297.
