### ISSUE TITLE
Allow variant annotations to be loaded into genotypes

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1838]
In #1771 we stripped variant annotation loading out of genotypes, in favor of keeping the variant annotations stored in the accompanying variant (c.f., `VariantContext`). However, if you're working with single sample data (e.g., gVCFs), having the variant annotation nested under the genotype may be useful.

**Comment by heuermh** [comment]
What are you thinking for resolving this one?  Would it be better to roll back before releasing 0.23.0?

**Comment by fnothaft** [comment]
I don't think we need to resolve this in 0.23.0 (it can wait for 0.24.0, which will follow fairly shortly thereafter), but it winds up being a pretty straightforward fix that adds a configuration flag. I'll have a patch along shortly.

**Comment by heuermh** [comment]
A configuration flag change should probably go in 0.23.0 then, for better or worse folks stick with release versions.  We're still waiting on Hadoop-BAM 7.9.1.

**Comment by fnothaft** [comment]
+1 to that; I just wouldn't want it to drag out the 0.23.0 release is all.
