### ISSUE TITLE
optimize SmithWaterman alignment

### ISSUE THREAD

**Issue by eyalfa** [bigdatagenomics/adam#1850]
Hi,
we at [Nrgrene](http://www.nrgene.com/) use a slightly modified version of this library's SmithWaterman algorithm.
Lately I went through an optimization session over this code after which I was able to increase its throughput by a factor of 3.

optimizations include the following techniques:
1. remove temporary object creation from inner loop (buildScoringMatrix).
2. represent the scoring and move matrix with a flat array instead of array of arrays.
3. use StringBuilder where appropriate (move).
4. eliminate branches in scoring function (constant gap).
5. introduce a scoring method optimized for valid DNA sequences, when all characters are known to be valid nucleotides (no wildcard), a rather small perfect hash can be build to determine the score without conditions.
7. introduced an `align` method that checks the given sequences and determine the scoring function to be used.

will you guys be willing to accept these as a pull-request? I'd be more than happy to contribute this work back to the community.

**Comment by heuermh** [comment]
Yes, that would be great!  A few other things to things to consider:

This API was designed as utility code for another algorithm, are there changes we might want to make to the public API to make it more discoverable?

Are there output formats other than CIGAR that we should support?

When I did the comparison some time ago, this code compared favorably to the Smith Waterman in biojava 1.x.  See [this package](https://github.com/heuermh/dishevelled-bio/tree/master/align/src/main/java/org/dishevelled/bio/align), although I seem to have misplaced the biojava 1.x Smith Waterman on Spark implementation over time.  I wonder, might you be interested in co-writing a short open access paper (say PeerJ or F1000) after these changes land?

**Comment by eyalfa** [comment]
@heuermh , still didn't have the time to look at the code in the ADAM project, as I mentioned I've optimized a lightly modified version of the code.
my optimizations didn't change the alignment output or API, I did add methods that accepts a predefined scoring function (the DNA specialized function is table based, if you're going to use the same weights for multiple alignments you might want to consider pre-allocating it) and another method that scans the two input sequences to determine whether the DNA specialized function can be used. other than that no interface changes.
so regarding your question about other outputs other than CIGAN, the current answer is no.

not sure what do you mean by PeerJ of F1000 but I'm definitely willing to share my optimizations techniques.

**Comment by heuermh** [comment]
Sorry for any misunderstanding.  I would like to take advantage of this opportunity when integrating the optimizations you have made to make a few other changes.

Then with the optimizations and any additional changes in, there might be enough performance improvement over the state of the art to justify a short paper.  I've had good experience with the open access journals [PeerJ](https://peerj.com/) and [F1000](https://f1000research.com/).

**Comment by heuermh** [comment]
Hello @eyalfa, these optimizations would still be welcome.  Might you have any time to submit a pull request?

**Comment by eyalfa** [comment]
hi @heuermh , almost forgot about this as I was quite busy during the last months (and the months to come)...
I'll try to craft something and if I'd find my self facing lack of time to invest in this I'd just paste here the relevant code so someone else can go through the effort of incorporating this into the Adam project.

**Comment by heuermh** [comment]
That sounds great!  I can pick things up if they aren't quite ready to merge.

**Comment by heuermh** [comment]
Ping @eyalfa, I still have some bandwidth available to integrate your changes.

**Comment by heuermh** [comment]
Closing as WontFix
