### ISSUE TITLE
Push to CRAN

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1851]
As discussed in #1849, we don't think ADAM 0.23.0 can go into CRAN until issues upstream in SparkR are resolved. For the 0.24.0 release, we hope these issues are resolved. For the CRAN release, we'll need to:

- [ ] Make sure that JAR is packaged in properly, à la [`install.spark`](https://github.com/apache/spark/blob/master/R/pkg/R/install.R)
- [ ] Formally test on linux
- [ ] Possibly test on Windows via CRAN windows test server
- [ ] Add [CRAN Markdown document](http://r-pkgs.had.co.nz/release.html#release-check)
- [ ] Add package vignettes

**Comment by fnothaft** [comment]
As per discussion with some Spark folks, the Spark-in-CRAN issue is unlikely to be fixed until Spark 2.3 is released, which is later than our timeline for 0.24.0.

**Comment by heuermh** [comment]
Spark was in CRAN and is now out again, see spark-dev@ email thread "SparkR was removed from CRAN on 2018-05-01".

**Comment by heuermh** [comment]
Note, as of 25 February, SparkR is still not in CRAN
http://apache-spark-developers-list.1001551.n3.nabble.com/Fwd-CRAN-submission-SparkR-2-3-3-td26520.html

**Comment by heuermh** [comment]
and we're back!
https://cran.r-project.org/web/packages/SparkR/index.html

Of course, us depending on Spark 2.4.2 brings other issues.

**Comment by heuermh** [comment]
SparkR is again no longer available in CRAN, closing as WontFix
