### ISSUE TITLE
add filterByOverlappingRegion(query: ReferenceRegion) to R and python APIs

### ISSUE THREAD

**Issue by akmorrow13** [bigdatagenomics/adam#1852]
We must have a user defined function in order to filter an RDD by ReferenceRegion. We can add this into the R and python APIs by default.

**Comment by fnothaft** [comment]
+1! Can you take this @akmorrow13? This should be straightforward now that we've added https://github.com/bigdatagenomics/adam/commit/495de2c5fe7bd7f64297085cc8a4a530f4079108.

**Comment by akmorrow13** [comment]
yep I got it!

**Comment by heuermh** [comment]
Fixed by #1869.
