### ISSUE TITLE
Cannot find `find-adam-assembly.sh` in bioconda build

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#1862]
@fnothaft might need help debugging this one.  The bioconda install splits the bin and package directories.

I thought the patches should no longer be necessary, because we rolled in the `# Find original directory of this script, resovling symlinks` block somewhere, but perhaps I am mistaken?

https://github.com/bioconda/bioconda-recipes/pull/7203/files

See
https://travis-ci.org/bioconda/bioconda-recipes/jobs/325551375

```
+ /bin/bash -x -e /opt/conda/conda-bld/adam_1515176451401/test_tmp/run_test.sh
+ adam-submit --help
/opt/conda/conda-bld/adam_1515176451401/_t_env/bin/adam-submit:
line 54: /opt/conda/conda-bld/adam_1515176451401/_t_env/bin/find-adam-assembly.sh:
No such file or directory
```

**Comment by fnothaft** [comment]
I would patch so that you've got `set -x -v` in all the scripts and see how far you can get.

**Comment by heuermh** [comment]
Looks like we still need those `# Find original directory of this script` blocks, at least for the bioconda recipe.

https://travis-ci.org/heuermh/bioconda-recipes/builds/325707349
