### ISSUE TITLE
Allow users to configure partitioning for pipe APIs

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1863]
I'd like users to be able to configure the partitioning for piped commands. Specifically, I'd like to be able to choose between a few strategies, such as:

- [ ] Default (our current strategy, where we partition by contiguous genomic region)
- [ ] Partition by target (allows users to provide a second GenomicRDD, and does something like a regionJoinAndGroupByLeft using the second RDD) --> This would be useful for things like calling variants on an exome panel
- [ ] Skip partitioning (what happens if no sequence dictionary is attached)

Thoughts/comments?

**Comment by heuermh** [comment]
From what I see, #1758 fits into this use case.

**Comment by heuermh** [comment]
Closing as WontFix
