### ISSUE TITLE
Only python 2? 

### ISSUE THREAD

**Issue by zfrenchee** [bigdatagenomics/adam#1871]
Hello ADAM developers, 
I just found this project and it looks like exactly what I'm looking for. I made the switch some time ago from python2 to python3 as my default. It seems like ADAM might be only python2 compatible. Is that right?

```
/Documents/genomics_project(master) » pip install bdgenomics.adam
Collecting bdgenomics.adam
  Downloading bdgenomics.adam-0.23.0.tar.gz (48.3MB)
    100% |████████████████████████████████| 48.4MB 27kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/0w/fzyy4qz93l56_bh1jyn3vgp00000gn/T/pip-build-niuwhkvj/bdgenomics.adam/setup.py", line 25, in <module>
        from version import version as adam_version
      File "/private/var/folders/0w/fzyy4qz93l56_bh1jyn3vgp00000gn/T/pip-build-niuwhkvj/bdgenomics.adam/version.py", line 22
        print version
                    ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int version)?

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/0w/fzyy4qz93l56_bh1jyn3vgp00000gn/T/pip-build-niuwhkvj/bdgenomics.adam/
```

**Comment by fnothaft** [comment]
Hi! I don't actually think we've got any functionality that _needs_ Python 2, rather we've possibly been inattentive to a few things that need to be _futureize_d. I'd be glad to give Python 3 compat a check!

**Comment by heuermh** [comment]
Is this actually a Python 3 vs 2 thing?  I may have ran into the same issue when pip installing inside a conda virtualenv, where I swear I was using python 2.7.

**Comment by zfrenchee** [comment]
I switched to python2 and this successfully installed, so I can confirm this is a python2/python3 issue.
