### ISSUE TITLE
Add convenience method to filter by contig

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#1877]
This should apply to both the underlying RDD/Dataset and the sequence dictionary:

- [x] Add `filterContigs` method to `SequenceDictionary`
- [ ] Add `filterByContig` method to `GenomicRDD`
- [ ] `filterByOverlappingRegion` should call `filterContigs`

**Comment by heuermh** [comment]
+1

What do you think about additional `filterBy` methods on the other RDD classes?  There are a few I'd like to add, plus some in https://github.com/antonkulaga/adam-playground that would be nice to have.

**Comment by fnothaft** [comment]
+1, let's separate them out into multiple tickets, but otherwise SGTM!

**Comment by heuermh** [comment]
Will do.  I'll also ping Anton, even though the method implementations are trivial, it'd be friendly to ask if he's ok since his repo appears to be licensed MPL-2.0.

**Comment by heuermh** [comment]
I've added `SequenceDictionary.filterToReferenceName`(s) in #1995.

The rest of this issue may require some further discussion though.  If implemented at the level of `GenomicRDD` then it would have to use `ReferenceRegion`s, if at the level of the typed `FooRDD` then it could simply be a filter on `foo.contigName`.

**Comment by heuermh** [comment]
My apologies, #1995 only fixed the first item above, reopening.
