### ISSUE TITLE
Build info/version info inside ADAM-generated files

### ISSUE THREAD

**Issue by nealsid** [bigdatagenomics/adam#188]
We should build off of Sebastian's work in https://github.com/bigdatagenomics/adam/pull/138 to output ADAM version info inside files generated by ADAM, so that we can version files containing ADAMRecords, ADAMNucleotideFragments, ADAMVariants, etc.

**Comment by heuermh** [comment]
Is this worth another look?  Parquet dependency is now at version 1.8.x.

**Comment by fnothaft** [comment]
Perhaps we can write this with our various metadata?

**Comment by fnothaft** [comment]
We should resolve this as part of #1257.

**Comment by fnothaft** [comment]
This will be resolved as part of #1257. Closing as dupe.
