### ISSUE TITLE
adam-submit aborts if ADAM_HOME is set

### ISSUE THREAD

**Issue by pbashyal-nmdp** [bigdatagenomics/adam#1882]
If `ADAM_HOME` is set, `adam-submit` aborts with the message:
```
java.lang.ClassNotFoundException: org.bdgenomics.adam.cli.ADAMMain
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
```

The `bin/find-adam-assembly.sh` used by `adam-submit` sources`bin/find-adam-home`.  `find-adam-home` script exits when `ADAM_HOME` is found. Since it is sourced, the `adam-submit` also exits.

To reproduce this, set `ADAM_HOME` and try running `adam-submit` .

Here's my patch to get it working:
```diff
diff --git a/bin/find-adam-home b/bin/find-adam-home
index 10269078..967f62a1 100755
--- a/bin/find-adam-home
+++ b/bin/find-adam-home
@@ -25,7 +25,7 @@ FIND_ADAM_HOME_PYTHON_SCRIPT="$(cd "$(dirname "$0")"; pwd)/find_adam_home.py"

 # Short cirtuit if the user already has this set.
 if [ ! -z "${ADAM_HOME}" ]; then
-   exit 0
+   true
 elif [ ! -f "$FIND_ADAM_HOME_PYTHON_SCRIPT" ]; then
   # If we are not in the same directory as find_adam_home.py we are not pip installed so we don't
   # need to search the different Python directories for a ADAM installation.
```

**Comment by heuermh** [comment]
Thanks @pbashyal-nmdp!  What is the use case for setting `ADAM-HOME`?

**Comment by pbashyal-nmdp** [comment]
Setting `ADAM_HOME` lets you decouple the installation location of adam from the scripts that call `adam-submit`. The same script can be run locally for testing and on the cluster.

Having `export PATH=$ADAM_HOME/bin:$PATH` also lets you run `adam-submit` from anywhere on the system.

**Comment by heuermh** [comment]
@fnothaft I'm still a bit shaky on changes to the bin scripts to support Python, is there a reason why `find-adam-home` short circuits out if `ADAM_HOME` is set?

**Comment by fnothaft** [comment]
> @fnothaft I'm still a bit shaky on changes to the bin scripts to support Python, is there a reason why find-adam-home short circuits out if ADAM_HOME is set?

It shouldn't. I'd tested the exact use case that @pbashyal-nmdp is running locally (before we merged the PR) and it had worked for me; I'm guessing that I then made a change after testing that locally and broke things. @pbashyal-nmdp do you mind if I commit the patch you provided (after testing it on my end)?

**Comment by pbashyal-nmdp** [comment]
Yes, please use the patch. Thanks!
