### ISSUE TITLE
ReferenceRegion in python does not exist

### ISSUE THREAD

**Issue by akmorrow13** [bigdatagenomics/adam#1884]
Some test files in adam-python have:
`from bdgenomics.adam.models import ReferenceRegion`

Where is this defined? It doesn't seem to be a python module, and I also get the error:
```
----> 6 from bdgenomics.adam.models import ReferenceRegion
ImportError: No module named models
```

**Comment by fnothaft** [comment]
Resolved by #1892. Thanks @akmorrow13!
