### ISSUE TITLE
Release cycle on pypi

### ISSUE THREAD

**Issue by akmorrow13** [bigdatagenomics/adam#1888]
Can we set up pypi releases for SNAPSHOT versions? Will I need permission for this?

**Comment by heuermh** [comment]
Seems reasonable to me.  I don't know about permissions.

**Comment by heuermh** [comment]
@akmorrow13 Would this still be helpful?  In theory Jenkins could push to PyPI at the same time it deploys snapshots to Sonatype snapshots repository.

**Comment by akmorrow13** [comment]
@heuermh this is not as useful anymore because the APIs are more stable. The only catch here is that we would need to auto-increment the version because python does not do snapshots and needs a new version for each push. I will talk to python people next week about this

**Comment by heuermh** [comment]
Thanks!  I'm also considering moving the python and R maven modules out to separate repositories, so they can have language-specific builds, CI, and release scripts.  We can discuss here or I could write up a new issue.

**Comment by heuermh** [comment]
Closing as WontFix, doing the python builds manually at release time is reasonable for now
