### ISSUE TITLE
Should NucleotideContigFragmentRDD create sequence dictionary on load?

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#1894]
One difference I've ran into between `NucleotideContigFragmentRDD` and `SequenceRDD` and `SliceRDD` in #1505 is that `NucleotideContigFragmentRDD` creates a sequence dictionary on load.

https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/rdd/contig/NucleotideContigFragmentRDD.scala#L83

Given that we've removed this functionality from `FeatureRDD` per #1321 (and long tail of related issues/pull requests) and seen performance issues e.g. #1891, should this remain?  Note there isn't a `persist` or `cache` here, which raised the issue with `FeatureRDD`.

Perhaps we move the code above from the ctr to a method `createSequenceDictionary()` or similar?

**Comment by heuermh** [comment]
Somewhat related, I notice we have [IndexedFastaFile](https://github.com/bigdatagenomics/adam/blob/63077b6a0cd595b0391575f0e044e105861a6aca/adam-core/src/main/scala/org/bdgenomics/adam/util/IndexedFastaFile.scala) but it doesn't appear to be used anywhere.

**Comment by fnothaft** [comment]
> Perhaps we move the code above from the ctr to a method createSequenceDictionary() or similar?

+1

**Comment by heuermh** [comment]
Fixed by #1895 and #2170
