### ISSUE TITLE
Standardize names for ADAM file formats

### ISSUE THREAD

**Issue by timodonnell** [bigdatagenomics/adam#190]
We currently call ADAM file formats lots of different things in places like the help messages for commands. I think it’d be useful to standardize our names for these formats, and choose file extensions for them.

I’m not at all tied to any particular names here, and people with more ADAM experience may have better suggestions, but I’ll give an example of what I'm thinking to start off discussion:

Format name | Data is sequence of avro messages of this type | Corresponding classic format | File (actually directory) naming convention
------------------------- | ------------------ | -------------------| ---------------
Alignment | ADAMRecord | BAM, SAM | XXX.align.adam
Contig | ADAMNucleotideContig | FASTA, FASTQ | XXX.contig.adam
Genotype | ADAMGenotype | VCF | XXX.gt.adam
Annotation | ADAMDatabaseAnnotation | VCF | XXX.ann.adam

If people think this is worthwhile and we agree on a set of names I'm happy to update the help text, etc.

**Comment by fnothaft** [comment]
With #587 we've decided to move away from this.
