### ISSUE TITLE
Pipe API doesn't properly handle multiple arguments and spaces

### ISSUE THREAD

**Issue by benwbooth** [bigdatagenomics/adam#1909]
The pipe API command does a simple split on spaces to split into multiple arguments. This will fail if any of the commands are arguments include spaces in them. There is currently no workaround for this. The underlying java ProcessBuilder API allows running commands with multiple arguments by passing in a list of parameters. The pipe API should thus also allow passing in a list of parameters instead of a single string. This would fix the argument separation and escaping issues. So the new interface would look like:

```
  def pipe[X, Y <: GenomicRDD[X, Y], V <: InFormatter[T, U, V]](
    cmd: Seq[String],
    files: Seq[String] = Seq.empty,
```

**Comment by heuermh** [comment]
Thanks for reporting this, @benwbooth!

> The pipe API command does a simple split on spaces to split into multiple arguments. This will fail if any of the commands are arguments include spaces in them. 

Yes, this is an issue.

> `cmd: Seq[String], ...`

This feels correct to me, however we also need to support the pipe API via Java, Python, and R, so the fix will need to propagate to those supporting methods.

Note in [Cannoli](https://github.com/bigdatagenomics/cannoli) we want to support Docker and Singularity over the pipe API, and perhaps a container-aware ProcessBuilder API developed there might be useful to surface in ADAM.  Would you find that helpful?

**Comment by heuermh** [comment]
Thank you for submitting this issue, @benwbooth!
