### ISSUE TITLE
add akmorrow13 to PyPl for bdgenomics.adam

### ISSUE THREAD

**Issue by akmorrow13** [bigdatagenomics/adam#1919]
@fnothaft can you add me so I can upload to the test server?

**Comment by akmorrow13** [comment]
ping @fnothaft

**Comment by heuermh** [comment]
I have accounts on PyPI and TestPyPI but am not sure how the project permissions work.  I don't see any projects listed when I log into TestPyPI, for example.

**Comment by fnothaft** [comment]
Done! Thanks for the ping, @akmorrow13!

**Comment by akmorrow13** [comment]
Thanks @fnothaft !
