### ISSUE TITLE
Fix GFF3 parser to handle trailing FASTA

### ISSUE THREAD

**Issue by benwbooth** [bigdatagenomics/adam#2037]
The GFF3 spec allows trailing FASTA sequences to be put into GFF3 files with a `##FASTA` line preceding them. ADAM's GFF3 parser should either stop parsing the GFF3 file if the `##FASTA` line is encountered, or possibly also return a NucleotideFragmentRDD with the parsed FASTA included somehow.

**Comment by heuermh** [comment]
Hello @benwbooth!

Yes, `loadFeatures` should not choke on a GFF3 file if it contains FASTA sequences.  We don't really have any methods in our API that return more than one `GenomicDataset` types from the same file, so we'd probably want to add GFF3 support to `loadSequences`.  Let me know what you think.

**Comment by benwbooth** [comment]
That seems sensible. Thanks!
