### ISSUE TITLE
Data Sets

### ISSUE THREAD

**Issue by ssabnis** [bigdatagenomics/adam#2043]
Hello,

I am trying to use ADAM in the infrastructure that I have built, I am looking a for a large data set that I can use to process using ADAM. Are there any open data available. ?

Any info much appreciated.

Thanks

**Comment by heuermh** [comment]
Hello @ssabnis!  You'll have to be a bit more specific, human variation?  cancer?  metagenomics?

**Comment by ssabnis** [comment]
Hi @heuermh,

I appreciate your quick response, thank you.

I am looking for any large data set to do performance testing of the ADAM with the infrastructure that I have built. I am open to suggestion from you.

**Comment by ssabnis** [comment]
Thanks a lot @heuermh , This is great help. I will start with this. If you know of any larger file size like 1 TB will help.

**Comment by ssabnis** [comment]
@jondeaton do I need uncompress the .gz file to run the ADAM?

**Comment by heuermh** [comment]
> do I need uncompress the .gz file to run the ADAM?

No, but unless the .gz file is Blocked Gzip format (BGZF) reading performance will not scale with number of executors, as regular Gzip format is not splittable.

**Comment by heuermh** [comment]
You might also want to take a look at the datasets referenced in
https://github.com/bcbio/bcbio_validations

Many different applications are discussed there.

**Comment by heuermh** [comment]
Closing as resolved.
