### ISSUE TITLE
Support Spark 2.4 and Scala 2.12

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#2044]
The branch for Spark version 2.4 release has been cut, and it adds support for Scala 2.12

http://apache-spark-developers-list.1001551.n3.nabble.com/Branch-2-4-is-cut-td24928.html

https://amplab.cs.berkeley.edu/jenkins/view/Spark%20QA%20Test/job/spark-master-test-maven-hadoop-2.7-ubuntu-scala-2.12/229/

**Comment by antonkulaga** [comment]
Spark 2.4 is officially releases already, looking forward to ADAMs Spark 2.4 support

**Comment by heuermh** [comment]
Yep, it's going to take some effort.  As you have seen, there is a blocker issue for us in Spark 2.4.0 upstream in Parquet 1.10.0 and how it interacts with Avro 1.8.2.  The issue is not getting any attention, so we'll have to make some significant changes in ADAM, such as always reading from via the `Dataset` path even if the caller is using the `RDD` path.
