### ISSUE TITLE
loadIndexedBam pulls entire bam file on http files, even when predicate is specified

### ISSUE THREAD

**Issue by akmorrow13** [bigdatagenomics/adam#2057]
When calling `loadIndexedBam()` on an http bam file, Spark first pulls the entire file locally and then indexes the local version. Is there a way to have this function directly query from the http location, based on a predicate?

**Comment by heuermh** [comment]
Is it Spark doing that, or Hadoop-BAM, or htsjdk?

**Comment by heuermh** [comment]
Closing as WontFix
