### ISSUE TITLE
@RG Flow Order field truncated

### ISSUE THREAD

**Issue by davidroberson** [bigdatagenomics/adam#2064]
SAM format has a read group field called "FO" which lists the order dNTP flows during a sequencing run.

![image](https://user-images.githubusercontent.com/7877261/46911236-83646580-cf23-11e8-92f3-ab51b8775f5b.png)

For Ion Torrent runs in particular this could be 500 characters or more.  I have seen that saveAsSam is truncating this field to 18 or 19 characters.

**Comment by heuermh** [comment]
@davidroberson Thank you for reporting this issue!
