### ISSUE TITLE
Support for Elastic Search 

### ISSUE THREAD

**Issue by jasonbrelsford** [bigdatagenomics/adam#2071]
I would really like to see support for exporting parquet schema to elastic search with assuming index based on source.  If able to support defining index and field on the fly would be good as well.    Defining values like (table-to-export, host, port, index_pattern).  Please let me know what other requirements would be helpful.

**Comment by heuermh** [comment]
Closing as WontFix.  Perhaps we can discuss further and reopen if necessary.
