### ISSUE TITLE
python API does not match API

### ISSUE THREAD

**Issue by akmorrow13** [bigdatagenomics/adam#2127]
https://github.com/bigdatagenomics/adam/blob/master/adam-python/bdgenomics/adam/rdd.py#L28
Still has RDD API descriptions, but RDDs have been removed

**Comment by heuermh** [comment]
Only the API doc, right?

**Comment by akmorrow13** [comment]
Ya, the strings just have to be updated to be read by readthedocs

**Comment by heuermh** [comment]
Thanks, perhaps we'll be using that 0.26.0a0 version soon then ;)

**Comment by akmorrow13** [comment]
I actually don't think you will need to change the version. We can just fix the docs and they should automatically pull. I can look into this.

**Comment by heuermh** [comment]
ok, thanks for your Py-wisdom.  :)
