### ISSUE TITLE
Replace jvmRdd with jvmDataset in adam-python

### ISSUE THREAD

**Issue by akmorrow13** [bigdatagenomics/adam#2134]
https://github.com/bigdatagenomics/adam/blob/master/adam-python/bdgenomics/adam/rdd.py#L53 and elsewhere should be called jvmDataset

**Comment by heuermh** [comment]
Python needs types!  What is `jvmRdd` an instance of?

**Comment by akmorrow13** [comment]
jvmRdd is actually a jvmDataset, but it is still called jvmRdd, which is confusing

**Comment by heuermh** [comment]
Yeah but what type?  adam.rdd.GenomicDataset or Spark Dataset?

**Comment by akmorrow13** [comment]
adam.rdd.GenomicDataset

**Comment by akmorrow13** [comment]
I think adam.rdd.GenomicDataset

**Comment by heuermh** [comment]
Yeah there are some magick conversions going on in there and I'm not wholly confident in what is happening.

Perhaps this change could be part of the mess I am making in #2112.

**Comment by heuermh** [comment]
Trying again in #2296
