### ISSUE TITLE
Make SamRecordConverter public

### ISSUE THREAD

**Issue by akmorrow13** [bigdatagenomics/adam#2138]
I am trying to use the [SamRecordConverter](https://github.com/bigdatagenomics/adam/blob/01135748cb2b3c73c238596e9ba8031592506620/adam-core/src/main/scala/org/bdgenomics/adam/converters/SAMRecordConverter.scala#L18) in Mango. I currently copied the code over because it is private to ADAM. Is there a reason we could not make this public? Maybe putting it in bdg converters would make more sense.

**Comment by heuermh** [comment]
What is your use case?  Refactoring the converters to fit in `bdg-convert` is something I've wanted to do for a while, but they reach into the models package and require strange combinations of metadata (e.g. `SAMFileHeader` and `ReadGroupDictionary`, both sides of the conversion).

**Comment by akmorrow13** [comment]
Hmm that sounds a little messy. I am currently using htsjdk and converting from htsjdk -> ADAM formats -> GA4GH formats (because the code is already written to do this). Therefore, I am using the SamRecordConverter to get from htsjdk to ADAM formats. However, as I type this, it may be better to just write a straight htsjdk -> GA4GH converter. Either way though, access to the converters would be nice.

**Comment by heuermh** [comment]
I must be missing something, ADAM already does those conversions

**Comment by akmorrow13** [comment]
Yes, but[ SamRecordConverter](https://github.com/bigdatagenomics/adam/blob/01135748cb2b3c73c238596e9ba8031592506620/adam-core/src/main/scala/org/bdgenomics/adam/converters/SAMRecordConverter.scala#L18) is private to ADAM so I cannot use them in Mango.

**Comment by heuermh** [comment]
Isn't it just something like
```scala
val logger: ...
val converter: AlignmentRecordToGa4ghRead(...)
val ga4ghReads: RDD[GA4GHRead] = sc.loadAlignments("foo.sam")
  .rdd
  .map(converter.convert(_, ConversionStringency.STRICT, logger))
```

**Comment by akmorrow13** [comment]
That converts ADAM alignment to GA4GH. I am trying to convert htsjdk alignment to ADAM.

**Comment by heuermh** [comment]
Sorry if I'm being thick
```
val alignments: RDD[AlignmentRecord] = sc.loadAlignments("foo.sam").rdd
```
?

**Comment by akmorrow13** [comment]
I am not using Spark in this case, but loading a bam file using htsjdk. You currently can only use the converters if you are using Spark.

**Comment by heuermh** [comment]
Ah, I see, not using Spark.  Yeah you shouldn't do that.  😉 

I'd suggest you write your own `SAMRecord` &rarr; GA4GH `Read` &c. converter then.  The ones in ADAM are too tied up in how ADAM handles the header and metadata.

If you still want to use Spark, but not ADAM, you can use [Disq](https://github.com/disq-bio/disq) to obtain the header and an RDD of `SAMRecord`s
```java
JavaSparkContext jsc = ...
HtsjdkReadsRddStorage storage = HtsjdkReadsRddStorage.makeDefault(jsc);
HtsjdkReadsRDD reads = storage.read("foo.bam")
SAMFileHeader header = reads.getHeader();
JavaRDD<SAMRecord> rdd = reads.getReads();
```

**Comment by akmorrow13** [comment]
Closing as it seems the conclusion is to keep these formats tied to RDDs for now

**Comment by ryan-williams** [comment]
The version you copied out didn't depend on Spark things, right @akmorrow13?

**Comment by akmorrow13** [comment]
@ryan-williams nope, it just uses htsjdk and avro formats, so no Spark involved
