### ISSUE TITLE
Rename reads to alignments in methods where appropriate

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#2172]
E.g.
AlignmentRecordDataset

sortReadsByReadName &rarr; sortByReadName
sortReadsByReferencePosition &rarr; sortByReferencePosition
sortReadsByReferencePositionAndIndex &rarr; sortByReferencePositionAndIndex

FragmentDataset

toReads &rarr; toAlignments

Timers

val SortReads = timer("Sort Reads") &rarr; val SortAlignments = timer("Sort Alignments")
val SortByIndex = timer("Sort Reads By Index") &rarr; val SortByIndex = timer("Sort Alignments By Index")

Reads2Coverage &rarr; Coverage

TransformFragments

var loadAsReads &arr; var loadAsAlignments
var saveAsReads &arr; var saveAsAlignments
var sortReads &rarr; var sortAlignments (or simply sort?)

**Comment by heuermh** [comment]
@akmorrow13 Is there a better name than `Alignments2Coverage` for the command line tool that calculates coverage for alignments?  I don't like the `foo2bar` style.

**Comment by akmorrow13** [comment]
We can use toCoverage or AlignmentsToCoverage. The former is shorter and cleaner but doesn't specify the original state, which I think may be important in ADAM

**Comment by heuermh** [comment]
Can we verb something?  All the other commands start with a verb, Count/Merge/Transform/Print/View.

**Comment by akmorrow13** [comment]
I guess countCoverage?

**Comment by heuermh** [comment]
Yeah, naming things is hard.  Is `coverage` enough?

https://www.biostars.org/p/5165/
https://www.illumina.com/science/education/sequencing-coverage.html
https://bedtools.readthedocs.io/en/latest/content/tools/coverage.html

**Comment by akmorrow13** [comment]
Yes @heuermh  that sounds much better!
