### ISSUE TITLE
BUILD FAILURE - Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:java

### ISSUE THREAD

**Issue by amirinSofi** [bigdatagenomics/adam#2227]
I was trying to build the the project. But when I run `mvn install` , I'm stuck at this error below.

> [INFO] --- exec-maven-plugin:1.5.0:java (generate-scala-products) @ adam-core-spark2_2.11 ---
> [WARNING] 
> java.lang.ClassNotFoundException: org.bdgenomics.adam.codegen.DumpSchemasToProduct
>     at java.net.URLClassLoader.findClass (URLClassLoader.java:471)
>     at java.lang.ClassLoader.loadClass (ClassLoader.java:588)
>     at java.lang.ClassLoader.loadClass (ClassLoader.java:521)
>     at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:281)
>     at java.lang.Thread.run (Thread.java:834)
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary for ADAM_2.11 0.30.0-SNAPSHOT:
> [INFO] 
> [INFO] ADAM_2.11 ............................................................ SUCCESS [  1.197 s]
> [INFO] ADAM_2.11: Shader workaround ........................... SUCCESS [  0.730 s]
> [INFO] ADAM_2.11: Avro-to-Dataset codegen utils ........... SUCCESS [  0.515 s]
> [INFO] ADAM_2.11: Core ................................................... FAILURE [  0.412 s]
> [INFO] ADAM_2.11: APIs for Java, Python ........................ SKIPPED
> [INFO] ADAM_2.11: CLI ..................................................... SKIPPED
> [INFO] ADAM_2.11: Assembly ........................................... SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  2.985 s
> [INFO] Finished at: 2019-10-21T14:26:44+08:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:java (generate-scala-products) on project adam-core-spark2_2.11: An exception occured while executing the Java class. org.bdgenomics.adam.codegen.DumpSchemasToProduct -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
> [ERROR] 
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR]   mvn <goals> -rf :adam-core-spark2_2.1
> 
Can anyone help me to look at the problem?
 Thanks in advance.

**Comment by heuermh** [comment]
Hello @amirinSofi, thank you for submitting this issue!

`DumpSchemasToProduct` is a class built in the `adam-codegen` Maven module which is then used when building the `adam-core` module.  I haven't seen this issue, at least not when running Maven from a terminal.  Are you doing that, or running Maven inside an IDE?

**Comment by amirinSofi** [comment]
Hi @heuermh, I was running Maven from a terminal. Is there any solutions I can do?

**Comment by heuermh** [comment]
It is possible we have some dependencies wired up incorrectly, and I don't see them because I have lots of version 0.30.0-SNAPSHOT builds in my local Maven repository already.  I'll try to reproduce from a new EC2 instance.

**Comment by amirinSofi** [comment]
actually, I face **BUILD FAILURE** when i run `mvn install` start from beginning as below:

> [INFO] Reactor Summary for ADAM_2.11 0.30.0-SNAPSHOT:
> [INFO] 
> [INFO] ADAM_2.11 ............................................................ SUCCESS [  4.131 s]
> [INFO] ADAM_2.11: Shader workaround ........................... FAILURE [  0.591 s]
> [INFO] ADAM_2.11: Avro-to-Dataset codegen utils ........... SKIPPED
> [INFO] ADAM_2.11: Core ................................................... SKIPPED
> [INFO] ADAM_2.11: APIs for Java, Python ........................ SKIPPED
> [INFO] ADAM_2.11: CLI ..................................................... SKIPPED
> [INFO] ADAM_2.11: Assembly ........................................... SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  4.847 s
> [INFO] Finished at: 2019-10-22T14:08:47+08:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile (scala-compile-first) on project adam-shade-spark2_2.11: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 240 (Exit value: 240) -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
> [ERROR] 
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR]   mvn <goals> -rf :adam-shade-spark2_2.11

But after I remove `src/` folder from `adam-shade` and `adam-codegen`, somehow I managed to get SUCCESS for **Shader workaround** and **Avro-to-Dataset codegen utils**. I tried to do same thing for `adam-core`, but I stuck with **FAILURE** as seen on my issue. Any ideas?

**Comment by heuermh** [comment]
If you remove all the `src` directories, then there won't be anything left to build.  ;)

Could you send the full output of `mvn --version`?  Maybe there is something

I use scripts in the https://github.com/heuermh/hook repo to bootstrap on Amazon EMR, and that works fine for me

https://github.com/heuermh/hook/blob/master/install-maven.sh
https://github.com/heuermh/hook/blob/master/install-adam-dev.sh

**Comment by amirinSofi** [comment]
Output of `mvn --version` : 
```
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 11.0.4, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.0.0-31-generic", arch: "amd64", family: "unix"
```
Is it the problem related with the maven version?

**Comment by heuermh** [comment]
Ah yes, Apache Spark is not compatible with JDK 11 yet, so neither are we. Can you install a version of JDK 8 (openjdk preferrably)?

**Comment by amirinSofi** [comment]
Yup, after change my JDK 11 to JDK 8, I managed to build ADAM. Thanks for your help mate.

**Comment by heuermh** [comment]
Thank you for submitting the issue!  Sorry I didn't catch the problem quick enough.  I will look for a good place in the docs to mention the strictly-JDK 8 requirement.

**Comment by Paryank0419** [comment]
I have macOS aarch64, so openJDK@8 is not there, I am also getting  -> 
 **Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec** 
 What should I do?
