### ISSUE TITLE
Adam without HDFS

### ISSUE THREAD

**Issue by jamesthegiantpeach** [bigdatagenomics/adam#2238]
I have been able to use adam with EMR, but I would like to use adam over an S3 bucket without HDFS. Is this possible?

**Comment by heuermh** [comment]
For reading or writing?  and Parquet files or flat files (e.g. BAM/VCF)?

**Comment by jamesthegiantpeach** [comment]
Mostly just flat files. I would lie to stream fastq files directly out of an S3 bucket, align it, sort it, markdup, and then stream a bam file back. I have been running some tests from k8s since that is what I happen to have laying around, and I would like to experiment with just removing hdfs entirely. 

Maybe this is stupid?

**Comment by heuermh** [comment]
Thanks for the clarification!  

Spark and ADAM are going to be happiest dealing with Parquet on HDFS, as that scales with the number of executors and is most efficient due to data locality.  Reading and writing to S3 is supported, but on EMR I would recommend using [Conductor](https://github.com/BD2KGenomics/conductor) and/or `s3-dist-cp` to transfer to/from HDFS.

Then with [Cannoli](https://github.com/bigdatagenomics/cannoli) your workflow might look like
```scala
import org.bdgenomics.cannoli.BwaArgs

val args = new BwaArgs()
args.indexPath = "hg38.fa"
args.sample = "sample"

import org.bdgenomics.adam.rdd.ADAMContext._
import org.bdgenomics.cannoli.Cannoli._

var reads = sc.loadPairedFastqAsFragments("sample_1.fq", "sample_2.fq")
val alignments = reads.alignWithBwa(args)
val sorted = alignments.sortByReferencePositionAndIndex()
val markdup = sorted.markDuplicates()
markdup.saveAsSam("sample.bam", isSorted = true, asSingleFile = true)
```

p.s. are you on [Gitter](https://gitter.im/bigdatagenomics/adam)?  It might be easier to back and forth there

**Comment by jamesthegiantpeach** [comment]
I just joined the room i'll comment there thanks.

**Comment by jamesthegiantpeach** [comment]
Closing since I was successfully able to use k8s with S3 only. Shuffle/spill data is written to the hostPath mount of every pod.

**Comment by heuermh** [comment]
Thanks for submitting this issue.  If you might be able to write up your experience with ADAM on k8s at some point, I would appreciate it.  It has been something I've been meaning to learn about.

**Comment by jamesthegiantpeach** [comment]
Ya i'll for sure write up my exp and some benchmarks. Still getting used to the API though so it might be a little bit before I have proper benchmarks.

**Comment by jamesthegiantpeach** [comment]
Btw the above example fails on 

```
val sorted = alignments.sortByReferencePositionAndIndex()
```

Looks like it needs to have a SequenceDictionary added in the alignments.sequences field.

**Comment by heuermh** [comment]
Ah right, you might want to add
```scala
val sequences = sc.loadSequenceDictionary("ref.dict")
alignments.replaceSequences(sequences)
```
in addition to the read group thing mentioned elsewhere

**Comment by jamesthegiantpeach** [comment]
Yea that works. It answers my question about where ref.dict comes into play [here](https://github.com/bigdatagenomics/cannoli/issues/219#issuecomment-571347483).
