### ISSUE TITLE
FastqRecordConvert incompatible with single tube long fragment read headers

### ISSUE THREAD

**Issue by jamesthegiantpeach** [bigdatagenomics/adam#2246]
Greetings,

We are using single tube long fragment reads. Here is a snippet of a few reads:

```
@19A_V100002826L1C001R038000001#635_1089_1106/1 1       1
CTCCCATTTTTAGACATGGGAAACTTTAGTAAAGGAAAAGCTCAGTGAAATACATCAAGATGGTAATAAACGGAGTTACAGAAGCTATACTTCCTGCTTT
+
EFFECFFFFFFFFFEGFFDEFFFDFFFFFFGFFFFFAFFFEFFFFFFFGGFGDFFFFFFFGFFGGGGGEFFGFFFFGEFFFEFGFFGFFFFFFGFFFGFC
@19A_V100002826L1C001R038000002#1520_830_834/1  2       1
AATCTGCATTGCAGGCTATATTAGTCTGTTTTCACACTGCTGATAAAGACATACCCGAGACTGAGTAATTTATAAAGAAAAGAGGTTTAGTGGAGTCACA
+
FFFFFFFFFFGFFF:EFFFFFFFFFCFGFFFFE@FFFFFFFFEFFF:FF=FFFECFF;F6DFFFFFFGFFFFFFGFFFFGF6FEFFFFE?FFFAFFAGFF
```
and

```
@19A_V100002826L1C001R038000001#635_1089_1106/2 1       1
GTCTATTTTGGGCTCACTTTGAAATGGGTGTTCTATAGTATGTGTAGACTAATCATCACAAAGCAGGAAGTATAGCTTCTGTAACTCCGTTTATTACCAT
+
FFFGFFGFGGFGFFFGFFFGFFFGFFFGFFGFGFEFGFFG>FGFFGFFGFFFFFGGFGFGGFFFEGFFGFFGFGGFGGFFGFGFEGFGF:FGFGFGFFFG
@19A_V100002826L1C001R038000002#1520_830_834/2  2       1
CATTTTCTCTTGCCTGCTGCCATGTAAGACATGCCTTTAGCCTTCTGCCATGATTGTGAGGCCTCCCCAGCCATATATAACTGTGACTCCACTAAACCTC
+
FF=FFF@FEEFFFEFFFFGFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFFFFDFFGFFEFFFFCFFFFFDAFGFGFGFAGGGFFFFFFFGFFFGDFFFFE
```
I think the regex in [this](https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/converters/FastqRecordConverter.scala#L41) function is not compatible with the above reads. 

Is simply changing the regex in the above linked file and writing some tests all that needs to happen to fix this? Or are there other places where changes would need to be made?

Something to note is that the second int after the /2 (/1) can be any int:
```
@V300046723L1C001R0020320583#215_532_1049/1     161697  1
GCCCTCTCTGGCTTAAGTGGGCACCTGGGCGATTCACAAGAAGGATTCTGTTATCTCCAGCAGGCACAACTCTGGAGGACAAGGTCTACCCAGAATTTCGGTCTCTGACACAAAAACCACAGAAGCCAGTGCTGCTAGGAGTACCCAGCA
+
GF>GEDGFED8GEEECDFE>=DFF@CF:@>C:EDGGBAFDCF3>FABFCF+@DE;DEC?C<FFD<FG38GCGEEA?B6GDF9FEF@FDG:<FE.DBGBEFDGGDAE;;GBGE4GBGBF=F2CFBGE:EGEC7FEAG2FGDE<?B:FGACG
```

Any guidance here would be helpful.

**Comment by heuermh** [comment]
Hello @jamesthegiantpeach, thank you for submitting this issue!

As far as I remember, the read suffixes are dropped after matching when determining the read name, so all I believe needs to be done is to create a new regex matching the suffixes you observe and OR it into `private val suffixRegex`.

**Comment by jamesthegiantpeach** [comment]
I'm going to submit a PR for this when I get home. 

Do you see any issue with using headers like the one below?

```
@A00741:47:HCM53DRXX:1:1101:1072:1000/1
TGGNCCATGCTCAGCCACCACCCAGGCCACACCTGCCCCCTGACCTCACCGCCCTCAACCCCATGGCTCTCTGGCTTCGCAGTCGCCCTCTGAGCCCTGAAACGCCCCCCTTCCAGACCCTGTGCATAGCAGGTCTACCCCAGACC
+
FFF#:FFFFFFFFF::F:FFFFFFFFFFFFFFFFFFFFFFF,:FFFFFFFFF:FF:FFFFFFFFFFFFFFFF::FFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
```

Going to try and figure out why loading reads of this form with loadPairedFastqAsFragments fails. Somehow the condition [here](https://github.com/bigdatagenomics/adam/blob/dd99cad756ec486efdc896cb1cf7d5080a9c95dd/adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala#L2533) fails, and I suspect that it might have something to do with the regex.

**Comment by jamesthegiantpeach** [comment]
This ended up being a non-issue. I added some stflr reads to your test suite and tests worked fine. Something else is causing my problems. Might be corrupt fastq files.
