### ISSUE TITLE
Load Multiple Files into the ADAM Variant schema

### ISSUE THREAD

**Issue by kattttttt** [bigdatagenomics/adam#2258]
I have managed to load a single vcf file into the ADAM Variant schema using
`adam-submit transformVariants inputpath outputpath`

Now I want to load multiple files into the outputpath
I can't just use the same command with different inputpaths since the output directory already exists after loading the first sample
How can I load multiple samples into the same ADAM variant schema?

**Comment by heuermh** [comment]
Hello @kattttttt!

Spark uses Hadoop file system glob syntax for multiple input files; see
https://hadoop.apache.org/docs/r2.4.1/api/org/apache/hadoop/fs/FileSystem.html#globStatus(org.apache.hadoop.fs.Path)

E.g.
```
$ adam-submit transformVariants data/*.vcf outputpath
```

In `adam-shell` you can union multiple variant datasets together explicitly
```scala
import org.bdgenomics.adam.rdd.ADAMContext._
val variants1 = sc.loadVariants("inputpath1")
val variants2 = sc.loadVariants("inputpath2")
variants1.union(variants2).saveAsParquet("outputpath")
```

Hope this helps!

**Comment by kattttttt** [comment]
yes, thank you!

**Comment by heuermh** [comment]
No problem, thank you!

**Comment by kattttttt** [comment]
Actually, I continue to have problems with loading multiple files:
I keep getting the error message 'Too many arguments: nameOfFileToBeLoaded'
What could be my problem?

**Comment by kattttttt** [comment]
Actually, I continue to have problems with loading multiple files:
I keep getting the error message 'Too many arguments: nameOfFileToBeLoaded'
What could be my problem?

**Comment by heuermh** [comment]
I am sorry, I gave you bad advice above! The example I gave will fail with `Too many arguments` error due to shell path expansion

```
$ adam-submit transformVariants data/*.vcf all.variants.adam
Too many arguments: data/bqsr1.vcf
```

When specifying a glob from the command line, it needs to be in quotes

```
$ adam-submit transformVariants "data/*.vcf" all.variants.adam
  ...
$ du -h *.adam
80G	all.variants.adam
```

**Comment by heuermh** [comment]
Closing as resolved, please reopen if I can help further.
