### ISSUE TITLE
allow software that depends on ADAM to register kryo serializers

### ISSUE THREAD

**Issue by timodonnell** [bigdatagenomics/adam#227]
This is not necessarily a bug -- I might just be misunderstanding something. 

In ADAMContext.createSparkContext, we hard-code a Spark configuration that sets 
"spark.kryo.registrator" to "org.bdgenomics.adam.serialization.ADAMKryoRegistrator"

Is there a way for software based on ADAM that has other objects that needs to be registered with kryo for serialization to override this?

**Comment by fnothaft** [comment]
This is resolved now as we've moved serializer registration into `adam-submit`.
