### ISSUE TITLE
saveAsSam format

### ISSUE THREAD

**Issue by hxdhan** [bigdatagenomics/adam#2321]
when I use this code to generate sam file 
```
val fragments = sc.loadFastq("36_11.fastq", Option("36_22.fastq"))
fragments.saveAsSam("test.sam", SAMFormat.SAM, true, false)
```

I got

@HD	VN:1.6	SO:unsorted
SRR8418436.2 2	77	*	0	0	*	*	0	0	GGAAATTTAAAAAAATACACATGGCCAGGCCCCAGCCCAAATCACTAATAAGAATCTCCAGGGCTTCACCTGTTAGACTGGCAAAAATCCAAAAGTAAACA	@@@BDA:?FHHHDHGFHBF9A?EGE@FHG<BG@DHGE;;B2=@GIDGDCFHHIBGHIIEEFC8?@B(.;>CA>>>;ACC<<?CCB9?9::>:>@C:@@CC>
SRR8418436.2 2	141	*	0	0	*	*	0	0	CACCAGCAATGTGTAGGAATACCTGTTTCTCCACAAAGTGTTTACTTTTGGATTTTTGCCAGTCTAACAGGTGAAGCCCTGGAGATTCTTATTAGTGATTT	?@<BDDABCCBFDHA9F@E@FHDEBEHI@DEBDAHIII1:D@GB@FHIB?@??DGDHG>CGB==C>;F@@C=C;??E=CBB?;AC<CCCDCCA>ACA35@@

but when I use another tool (example picard) I got
@HD     VN:1.6  SO:queryname
@RG     ID:A    SM:1
SRR8418436.2    77      *       0       0       *       *       0       0       GGAAATTTAAAAAAATACACATGGCCAGGCCCCAGCCCAAATCACTAATAAGAATCTCCAGGGCTTCACCTGTTAGACTGGCAAAAATCCAAAAGTAAACA   @@@BDA:?FHHHDHGFHBF9A?EGE@FHG<BG@DHGE;;B2=@GIDGDCFHHIBGHIIEEFC8?@B(.;>CA>>>;ACC<<?CCB9?9::>:>@C:@@CC>   RG:Z:A
SRR8418436.2    141     *       0       0       *       *       0       0       CACCAGCAATGTGTAGGAATACCTGTTTCTCCACAAAGTGTTTACTTTTGGATTTTTGCCAGTCTAACAGGTGAAGCCCTGGAGATTCTTATTAGTGATTT   ?@<BDDABCCBFDHA9F@E@FHDEBEHI@DEBDAHIII1:D@GB@FHIB?@??DGDHG>CGB==C>;F@@C=C;??E=CBB?;AC<CCCDCCA>ACA35@@   RG:Z:A

I think there are extra column 
SRR8418436.2 2
 ---------------^

I want to know how to do to omit this column.

the fastq data in this file .
[test.zip](https://github.com/bigdatagenomics/adam/files/6621546/test.zip)

**Comment by hxdhan** [comment]
HI , the version as follow:

adam :  0.35.0 (lastest)
picard:  2.25.5 (lastest)

when I check the code , I think picard split SamRecord when change to sam file.

**Comment by heuermh** [comment]
Thanks!  I'll try to replicate

**Comment by hxdhan** [comment]
there are another issue . when I use follow code to get sam file .  I found no head in generate sam file .

`implicit val tFormatter = SAMInFormatter
    implicit val uFormatter = new AnySAMOutFormatter

    fragments
      .toAlignments
      .pipe[Alignment, AlignmentProduct, AlignmentDataset, SAMInFormatter](
        cmd = builder.build(),
        files = builder.getFiles()
      )`

**Comment by heuermh** [comment]
There isn't an extra column in the SAM file, rather the read name is `SRR8418436.2 2`

```
$ cat 36_11.fastq
@SRR8418436.2 2/1
GGAAATTTAAAAAAATACACATGGCCAGGCCCCAGCCCAAATCACTAATAAGAATCTCCAGGGCTTCACCTGTTAGACTGGCAAAAATCCAAAAGTAAACA

$ cat 36_22.fastq
@SRR8418436.2 2/2
CACCAGCAATGTGTAGGAATACCTGTTTCTCCACAAAGTGTTTACTTTTGGATTTTTGCCAGTCTAACAGGTGAAGCCCTGGAGATTCTTATTAGTGATTT

$ adam-submit \
  transformAlignments \
  -single \
  -paired_fastq 36_22.fastq \
  36_11.fastq \
  36.sam

$ cat 36.sam
@HD	VN:1.6	SO:unsorted
@PG	ID:ADAM_1623694505	PN:org.bdgenomics.adam.cli.TransformAlignments	VN:0.35.0	CL:-single -paired_fastq 36_22.fastq 36_11.fastq 36.sam
SRR8418436.2 2	77	*	0	0	*	*	0	0	GGAAATTTAAAAAAATACACATGGCCAGGCCCCAGCCCAAATCACTAATAAGAATCTCCAGGGCTTCACCTGTTAGACTGGCAAAAATCCAAAAGTAAACA	@@@BDA:?FHHHDHGFHBF9A?EGE@FHG<BG@DHGE;;B2=@GIDGDCFHHIBGHIIEEFC8?@B(.;>CA>>>;ACC<<?CCB9?9::>:>@C:@@CC>

$ adam-shell
...
scala> import org.bdgenomics.adam.ds.ADAMContext._
import org.bdgenomics.adam.ds.ADAMContext._

scala> val fragments = sc.loadFastq("36_11.fastq", Option("36_22.fastq"))
fragments: org.bdgenomics.adam.ds.read.AlignmentDataset = RDDBoundAlignmentDataset with 0 reference sequences, 0 read groups, and 0 processing steps

scala> import org.apache.spark.sql.functions._
import org.apache.spark.sql.functions._

scala> fragments.toDF().select(col("readName")).show()
+--------------+
|      readName|
+--------------+
|SRR8418436.2 2|
|SRR8418436.2 2|
+--------------+
```

Here's another example, the read name is `20FUKAAXX100202:1:1:10000:100440`

```
$ head CEUTrio.HiSeq.WGS.b37.NA12878.20.21_1.fastq
@20FUKAAXX100202:1:1:10000:100440/1
CTTTGAAACACTCTTTTTTTTGAATCTGCAAGTGGACATTTGGAGCGCTTTGTATCCTATGGTGGAAAAGGATATATCATCACATAAAAACTAGATAGAAG

$ head CEUTrio.HiSeq.WGS.b37.NA12878.20.21_2.fastq
@20FUKAAXX100202:1:1:10000:100440/2
AAAGGTTAAACTCTGTGAGATGATTGCACACATCACAAATAAGATTGTCAGAATGCTTCTGTCTAGTTTTTTTGTGAAGATATTTCCTTTTACACTATAGG

$ adam-submit \
  transformAlignments \
  -single \
  -paired_fastq CEUTrio.HiSeq.WGS.b37.NA12878.20.21_2.fastq \
  CEUTrio.HiSeq.WGS.b37.NA12878.20.21_1.fastq \
  CEUTrio.HiSeq.WGS.b37.NA12878.20.21.sam

$ head CEUTrio.HiSeq.WGS.b37.NA12878.20.21.sam
@HD	VN:1.6	SO:unsorted
@PG	ID:ADAM_1623693823	PN:org.bdgenomics.adam.cli.TransformAlignments	VN:0.35.0	CL:-single -paired_fastq CEUTrio.HiSeq.WGS.b37.NA12878.20.21_2.fastq CEUTrio.HiSeq.WGS.b37.NA12878.20.21_1.fastq CEUTrio.HiSeq.WGS.b37.NA12878.20.21.sam
20FUKAAXX100202:1:1:10000:100440	77	*	0	0	*	*	0	0	CTTTGAAACACTCTTTTTTTTGAATCTGCAAGTGGACATTTGGAGCGCTTTGTATCCTATGGTGGAAAAGGATATATCATCACATAAAAACTAGATAGAAG	DFDEFGHHDGDGFHFFFCCBDEGHGFHGFGHGEGGGEFGFGGG;GE?FHGGGFGGGGHAGGGCGAGHHGGGED@GCGDGGEGBGFGGEF@AHEFHFFFGFC

$ adam-shell
...
scala> import org.bdgenomics.adam.ds.ADAMContext._
import org.bdgenomics.adam.ds.ADAMContext._

scala> val fragments = sc.loadFastq("CEUTrio.HiSeq.WGS.b37.NA12878.20.21_1.fastq", Option("CEUTrio.HiSeq.WGS.b37.NA12878.20.21_2.fastq"))
fragments: org.bdgenomics.adam.ds.read.AlignmentDataset = RDDBoundAlignmentDataset with 0 reference sequences, 0 read groups, and 0 processing steps

scala> import org.apache.spark.sql.functions._
import org.apache.spark.sql.functions._

scala> fragments.toDF().select(col("readName")).show(numRows = 2, truncate = 80)
+--------------------------------+
|                        readName|
+--------------------------------+
|20FUKAAXX100202:1:1:10000:100440|
|20FUKAAXX100202:1:1:10000:108914|
+--------------------------------+
only showing top 2 rows
```

**Comment by hxdhan** [comment]
when use picard to generate sam file . the read name is not include:  \t 2

when the readname include \t 2 , the same file is malform to handle by another tool to handle sush as arriba extra..
I think it be handle by extra column  cause have space or tab .

**Comment by heuermh** [comment]
Note there is no `\t` (tab) character in the read name, only a space.

**Comment by hxdhan** [comment]
I think picard strip this space and the nuber .
after stip this.  the generate file could be handle by other tools. such as STAR.

**Comment by heuermh** [comment]
Closing as WontFix, see comment https://github.com/bigdatagenomics/adam/pull/2325#issuecomment-904084127
