### ISSUE TITLE
Is it possible to do saveAsSam() parallelly ?

### ISSUE THREAD

**Issue by SidWeng** [bigdatagenomics/adam#2326]
I create a list of AlignmentDataset by loadParquet() with different FilterPredicate and try to save BAM file on HDFS using saveAsSam(). It works if I save the BAM files sequentially:
```
aDs.foreach(i => i.saveAsSam("a hdfs path", asType = Some(SamFormat.BAM), isSorted = true, asSingleFile = true, disableFastConcat = true))
```
but I got FileNotFoundException when I try to use par:
```
aDs.par.foreach(i => i.saveAsSam("a hdfs path", asType = Some(SamFormat.BAM), isSorted = true, asSingleFile = true, disableFastConcat = true))
```
The Exception complains about the specific file `xxx.bam_head` not found, and I'm guessing the reason is it will cause race condition on [line 907 in AlignmentDataset.scala](https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/ds/read/AlignmentDataset.scala#L907) :
```
conf.set("org.bdgenomics.adam.rdd.read.bam_header_path", headPath.toString)
```
Thus, I modify [line 823 in AlignmentDataset.scala](https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/ds/read/AlignmentDataset.scala#L823) from
```
val conf = rdd.context.hadoopConfiguration
```
to
```
val conf = new Configuration(rdd.context.hadoopConfiguration)
```
 However, I got `org.apache.spark.SparkException: Task failed while writing rows` and `java.lang.StackOverflowError`, is there any chance to do saveAsSam() parallelly ?

**Comment by heuermh** [comment]
Yes, headers are really a problem when attempting to write a partitioned file concurrently (SAM, BAM, CRAM, and VCF all included).  Writing to Parquet does not have this problem, but I don't think that helps your use case.

The details are in [https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/util/FileMerger.scala](FileMerger.scala) and [https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/util/ParallelFileMerger.scala](ParallelFileMerger.scala).

That said, what kind of performance improvement are you expecting by writing multiple datasets in parallel?  Writing serially should already saturate the cluster, if the data are partitioned appropriately for the cluster size.

**Comment by SidWeng** [comment]
@heuermh thanks for your reply !

> That said, what kind of performance improvement are you expecting by writing multiple datasets in parallel? Writing serially should already saturate the cluster, if the data are partitioned appropriately for the cluster size.

In my scenario it's possible to have thousands of BAM files to save on HDFS, so I try to save these files as quickly as possible.

Another question is according to [the description of disableFastConcat](https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/ds/read/AlignmentDataset.scala#L793), I shoud set `disableFastConcat` as `true` because `asSingleFile` is `true` and `deferMerging` is `false` in my case.
However, I check [ParallelFileMerger.mergeFiles()](https://github.com/bigdatagenomics/adam/blob/bb0705d5ec9e27943ce0a12151febc771d76952e/adam-core/src/main/scala/org/bdgenomics/adam/util/ParallelFileMerger.scala#L52), it seems ‎ok to use as long as the data is on HDFS, do I misunderstand anything ?

**Comment by heuermh** [comment]
`disableFastConcat = true` is only necessary on Hadoop file systems that don't support the operations used in ParallelFileMerger; we ran into at least one encrypted file system implementation that required this as a fall back.

**Comment by SidWeng** [comment]
@heuermh thanks for your help
