### ISSUE TITLE
Don't flatten optional SAM tags into a string

### ISSUE THREAD

**Issue by iskandr** [bigdatagenomics/adam#240]
When converting from a SAM record to an ADAM record, we flatten the already parsed collection of tags into a string. This incurs a (seemingly significant) memory/performance overhead and leaves the tag info in a less accessible form. It would be preferably to simply store the tags in a Map[String,String]. I think this is also a simpler solution to https://github.com/bigdatagenomics/adam/issues/37, since we don't need to figure out which tags deserve "top-level" inclusion ahead of time, just present them in a uniform manner.

**Comment by calvertj** [comment]
Want me to take this one?

**Comment by karenfeng** [comment]
Yes, thanks.

**Comment by fnothaft** [comment]
+1, that'd be wonderful.

**Comment by calvertj** [comment]
Cool, working on it.

**Comment by calvertj** [comment]
Sorry for the delay, will work on it this weekend.

**Comment by calvertj** [comment]
I'm done shoveling, back in progress.

**Comment by calvertj** [comment]
Hey guys, (@tdanford, @fnothaft) 

From my (limited) understanding of the SAM Format specification ( http://samtools.github.io/hts-specs/SAMv1.pdf ) there can be multiple lines with same tag, does that seem correct to you?  A Map[String,String] could have collisions, I am guessing you don't want to throw an exception if there are collisions?

There are plenty of options:
Map[String,String] (after grouping and concatenating like tag values)
Map[String,List[String]]
List[(String, String)]
...

Also are you sure you don't want to keep the type information that was so nicely parse out?

I am looking at this bit of code in org.bdgenomics.adam.converters.SAMRecordConverter:
https://github.com/bigdatagenomics/adam/blob/cd10066547285becc70aded4e074277aedfa6fc8/adam-core/src/main/scala/org/bdgenomics/adam/converters/SAMRecordConverter.scala#L165

I assume these are the tags I'm looking for.

Thanks and sorry for the delay,

J

**Comment by tdanford** [comment]
I wrote some version of this code back in the day, I remember thinking, "we should probably be keeping the type information around."  It's required at least insofar as we will ever need to go *back* to BAM/SAM format.

**Comment by calvertj** [comment]
@tdanford

oops, I was thinking the SAMRecord was an iterator over the file, not a line.  I guess I should not watch house of cards while looking at code. 

As for what to store it as, are you sure you don't just want to keep the List[Attribute]?

https://github.com/bigdatagenomics/adam/blob/cd10066547285becc70aded4e074277aedfa6fc8/adam-core/src/main/scala/org/bdgenomics/adam/models/Attribute.scala#L31

Finally should I change the attributes in the format or create a samTags or something?
https://github.com/bigdatagenomics/bdg-formats/blob/master/src/main/resources/avro/bdg.avdl#L218

Thanks,

J

**Comment by tdanford** [comment]
Jason, I'm confused by what you mean, when you write

  As for what to store it as, are you sure you don't just want to keep the List[Attribute]?

**Comment by calvertj** [comment]
Currently the List[Attribute] is turned into a tab delimited string:

https://github.com/bigdatagenomics/adam/blob/cd10066547285becc70aded4e074277aedfa6fc8/adam-core/src/main/scala/org/bdgenomics/adam/converters/SAMRecordConverter.scala#L165

At least I think I am looking at the right bit of code.  Is this the "tags" I am looking to update?
I was wondering why not just keep the List[Attribute] instead of a Map[String,String]? Or maybe a Map[String,Attribute], that is all.

J

**Comment by calvertj** [comment]
Well, I am just going to use a Map[String,String] as we won't need a custom record in Avro.  Path of least resistance.  So is something like this ok?
("tagName -> "tagType:TagValue") ?

**Comment by tdanford** [comment]
Jason, I think it sounds fine -- but we'll probably need to see the code :-) 

Why don't you whip something up, and we'll review it in detail there?

**Comment by calvertj** [comment]
Yea, less talk, more action.

**Comment by fnothaft** [comment]
> ("tagName -> "tagType:TagValue") ?

SGTM!

**Comment by tdanford** [comment]
Yeah, that sounds like the right direction -- but again, eager to see code :-)

**Comment by fnothaft** [comment]
Closing as won't fix. See #1080 for most recent discussion.
