### ISSUE TITLE
Add variant effect ontology

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#261]
Suggested by @heuermh, see [here](http://gemini.readthedocs.org/en/latest/content/functional_annotation.html#standardizing-impact-definitions-for-gemini) for examples. This should be added to the VariantAnnotations and variant annotation parser.

**Comment by heuermh** [comment]
See new [VCF annotation standard 'ANN' field specification](http://snpeff.sourceforge.net/VCFannotationformat_v1.0.pdf), from authors of [SnpEff](http://snpeff.sourceforge.net/) and [Ensembl VEP]().

**Comment by fnothaft** [comment]
See new schema in https://github.com/bigdatagenomics/bdg-formats/pull/67.

**Comment by fnothaft** [comment]
Closing as dupe of https://github.com/bigdatagenomics/adam/issues/1044.
