### ISSUE TITLE
Need clear error messages when schema has backward-incompatible change

### ISSUE THREAD

**Issue by jey** [bigdatagenomics/adam#345]
Currently when the schema undergoes a backwards incompatible change, the user will get failing ADAM jobs that die with an exception saying something non-obvious about "avro.GenericRecord". This should instead be detected at load time and reported as an error if the RDD contains any "GenericRecord" instances.

**Comment by calvertj** [comment]
I can't seem to reproduce this with the current 0.15.0 version.  Adam "files" produced with ADAMRDDFunctions.adamSave from an older version (0.14.0) throw a:

parquet.io.ParquetDecodingException: Can not read value at 0 in block 0 ...

when I attempt to collect them after a load with ADAMContext.adamLoad in the current version.

**Comment by heuermh** [comment]
Closing as WontFix
