### ISSUE TITLE
Add coverage for the FlagStat command

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#355]
The ADAM FlagStat transform doesn't currently have a test suite. This transform scans an RDD of reads and collects statistics about the flags in the reads.

**Comment by beaunorgeot** [comment]
We (@ansalaza and I) have a suite that can read in a .adam file and that tests FlagStat output against an expected output. We got the expected output by running the file through ADAM FlagStat. Is this what you were looking for? Are there additional elements that you would like to test against?

**Comment by fnothaft** [comment]
@beaunorgeot that'd be awesome! I think that would be sufficient for now; we can always expand it later.

**Comment by fnothaft** [comment]
Closed by #552, https://github.com/bigdatagenomics/adam/commit/341c5581d7b8e9d893423a9ca61f83c517c817e5.
