### ISSUE TITLE
Remove all the commands in the "CONVERSION OPERATIONS" `CommandGroup`

### ISSUE THREAD

**Issue by laserson** [bigdatagenomics/adam#373]
If we are supporting a `transform` command, shouldn't it cover all of these cases?

**Comment by heuermh** [comment]
@laserson ok to close this issue as WontFix?

**Comment by laserson** [comment]
I'm still not crazy about the naming.  If I understand correctly, `transform` is actually used for performing the GATK operations, is that right?

**Comment by fnothaft** [comment]
Closing as won't fix.
