### ISSUE TITLE
Generalize FASTQ input formats to multiline FASTQ

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#386]
Currently, our FASTQ input formats only support single line FASTQ records. This is _generally_ sufficient for Illumina reads, but is not necessarily sufficient for longer read technologies like PacBio or Oxford Nanopore. To add this support, we need to perform look-ahead parsing when picking splits and reading.

**Comment by fnothaft** [comment]
Closed by #551.

**Comment by cuericlee** [comment]
Dose adam convertor/pasor suppor to readh fastq format directly, it seems I didn't see fastq2adam conversion. but I sam adam2fastq. what is consideration here?

**Comment by fnothaft** [comment]
Hi @cuericlee!

You can convert single FASTQ files or interleaved FASTQ to ADAM using the `transform` command. You may want to see https://github.com/bigdatagenomics/adam/pull/831, which expands the `transform` command to support paired FASTQ.

**Comment by cuericlee** [comment]
@fnothaft and @ryan-williams 
ok, thanks, let me give an try to convert fastq output from illumina instrument to adam with transform function and api on my spark cluster.
