### ISSUE TITLE
Handle no-ops more intelligently when creating MD tags

### ISSUE THREAD

**Issue by kristalcurtis** [bigdatagenomics/adam#392]
Currently, Adam creates very verbose MD tags when it encounters no-ops, e.g., 2G0A0T0G0A2G2A0T0G0T1G0T0C3T0G0A0G0T1G0T0C0A1G0T0C0T0G0A0T0G1A3G0A0C0A0T0C0A0T1G2C0A0G0A0T0G0C0T0G0A0G4C0A0G1C0A2C0A0T0A0T1G0T0G9.

**Comment by fnothaft** [comment]
Closing as won't fix.
