### ISSUE TITLE
Bake off different region join implementations

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#395]
@kozanitis and I were discussing this. Now that we've got 3 proposed region join strategies, we should go ahead and run a few head-to-head tests to evaluate performance. I think the correct approach would be to define a few reasonable test cases, and to then do a one-by-one bakeoff.

Here are a few test cases that I thought of:

* Whole genome BAM vs. windows (2-10kbp windows over the whole genome)
* Whole exome BAM vs. exome panel BED
* WES/WGS BAM vs. targeted sequencing panel (pick "important cancer genes", or something of that sort)
* RNA-seq BAM vs. exons?

I'm sure there are more cases out there; @tdanford and @carlyeks, what cases did you originally have in mind when you implemented region joins?

cc'ing @massie @laserson, would be glad to hear thoughts from any other interested parties. @kozanitis and I will start working to put together the bake-off tests on Thursday.

**Comment by arq5x** [comment]
@laserson has shared an preliminary [attempt](https://github.com/bigdatagenomics/adam/pull/534) at this with me. I am really interested in exploring ways to take advantage of ADAM/Spark to scale up the functionality we have already implemented in [bedtools](https://github.com/arq5x/bedtools2). Can you point me to use cases and/or example commands for converting BED and/or BigWig files to ADAM?

**Comment by laserson** [comment]
@arq5x Check out README here for the data and a few manipulations:
https://github.com/sryza/aas/tree/master/ch10-genomics

Then the scala code for loading and joining is here:
https://github.com/sryza/aas/blob/master/ch10-genomics/src/main/scala/com/cloudera/datascience/genomics/RunTFPrediction.scala

This is from our upcoming book Advanced Analytics with Spark.

**Comment by laserson** [comment]
@arq5x also, the book's code was written before the shuffle join impl I shared with you, so it uses the broadcast join.

**Comment by arq5x** [comment]
Thanks for this.  I am still a bit unclear about the implementation of broadcast and join. Do you have any pictorial and/or verbal descriptions of how they each work?

**Comment by laserson** [comment]
@arq5x check out the impl directly.  @tdanford did a great job commenting it: https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/rdd/RegionJoin.scala#L34

**Comment by arq5x** [comment]
Thanks - I will try to make my way through the code. Part of my confusion is in knowing which functions are distributed, which are serial, etc...

**Comment by laserson** [comment]
@arq5x Yeah, I'd suggest looking at the code from a Scala IDE (like IntelliJ), which should make it easier to tell what type everything has.  Anything that's an RDD or a Broadcast is distributed.  Everything else is local.

**Comment by ryan-williams** [comment]
OOC, what are the "3 proposed region join strategies", @fnothaft? BroadcastRegionJoin, ShuffleRegionJoin, and ____?

**Comment by fnothaft** [comment]
@kozanitis had proposed an interval tree based join in #390, but this didn't wind up merging in.

**Comment by fnothaft** [comment]
Closing as won't fix, as @kozanitis had been most interested in this and has left.
