### ISSUE TITLE
Replace hard-coded sequence utils with an Alphabet model

### ISSUE THREAD

**Issue by tdanford** [bigdatagenomics/adam#410]
As part of the work on Gene models, we introduced the SequenceUtils object (in adam.utils), which is just a hacky container for some simple "complement" operations on DNA sequences themselves.  

This should be replaced by an actual Alphabet model, with support for ambiguity codes, different alphabets, etc.

**Comment by Agent007** [comment]
Has anyone taken a look at https://github.com/bioscala/bioscala/tree/master/src/main/scala/bio/sequence ?

**Comment by fnothaft** [comment]
@Agent007 nice! Thanks for the heads up there; I wasn't aware of that, but it's definitely worth a look.

**Comment by fnothaft** [comment]
Closed by #653.
