### ISSUE TITLE
Create a simplified vocabulary for naming projections.

### ISSUE THREAD

**Issue by tdanford** [bigdatagenomics/adam#419]
Creating Projection objects is actually somewhat annoying -- especially for ``AlignmentRecord``.  We should create "standard projections" for commonly-used schemas, which are named and described in an appropriate way, that can be used and combined rather than simply creating a new custom projection for every use of a Parquet file.

E.g. is there a projection for when you only need the names and metadata about reads? for when you need the full alignment?  For when you do (or don't) care about the mate- (or paired-end-) fields?

**Comment by fnothaft** [comment]
Closing unless we have a concrete proposal.
