### ISSUE TITLE
Create standardized, interpretable exceptions for error reporting

### ISSUE THREAD

**Issue by tdanford** [bigdatagenomics/adam#420]
I think that #297 is indicative of a slightly larger problem -- the way it manifests is that, when you run `partitionAndJoin` with some non-mappable records (i.e. records that can't be turned into a ReferenceRegion), you get a NullPointerException being thrown by an un-intelligible piece of code.

The challenge isn't just to catch this error condition earlier, it's to throw exceptions whose names/messages are interpretable to the end-user.  So, for example, we could have an UnmappedException exception, which is thrown whenever "something that should be mappable, isn't."  

Other ideas for exceptions -- 
- invalid sample identifier
- insufficient read coverage (or data coverage?) 

thoughts?

**Comment by fnothaft** [comment]
Closing as won't fix.
