### ISSUE TITLE
We should be able to filter genotypes that overlap a region

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#422]
Currently, we have a method for filtering reads which overlap a given reference region --> https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/AlignmentRecordRDDFunctions.scala#L57. We should also support this for Genotypes.

**Comment by ZimraanHamid** [comment]
I'll take a shot at this!

**Comment by fnothaft** [comment]
Awesome! Thanks @ZimraanHamid.

**Comment by fnothaft** [comment]
This was resolved in #1051 and others.
