### ISSUE TITLE
Write a quick start guide to running ADAM on EC2

### ISSUE THREAD

**Issue by massie** [bigdatagenomics/adam#43]
There's a Wiki page at https://github.com/massie/adam/wiki/Running-ADAM-on-EC2 with information to get started. It would be great to have someone clean up the guide and submit it as part of the source (e.g. Markdown).

**Comment by ajohi** [comment]
I can not find this document . Is it moved ?

**Comment by fnothaft** [comment]
@ajohi it has moved inside the repository to https://github.com/bigdatagenomics/adam/blob/master/docs/source/40_running_on_EC2.md
