### ISSUE TITLE
Should FASTQ output use reads' "original qualities"?

### ISSUE THREAD

**Issue by ryan-williams** [bigdatagenomics/adam#436]
[`AlignmentRecordConverter.convertToFastq`](https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/converters/AlignmentRecordConverter.scala#L43) currently outputs `getQual` as the FASTQ qualities; should it instead output `getOrigQual`? I'm not super familiar with the difference between read qualities and "original qualities" but I am having a hard time imagining that "original qualities" would not be the thing that was originally found in the FASTQ data the reads originated from.

I have this change ready, lmk if it seems reasonable.

**Comment by fnothaft** [comment]
I think this was resolved by https://github.com/bigdatagenomics/adam/commit/322c32f478da173a0b682b76d289ea0b173842eb.
