### ISSUE TITLE
Throw error when loading RDD of "Nothing" type

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#441]
If a type parameter isn't passed to the `org.bdgenomics.adam.rdd.ADAMContext.adamLoad` function, ADAM/Spark/Parquet will proceed to silently load an RDD of `Nothing` type. Things will then get weird when you try to access records in the RDD. This bug was reported on the [mailing list](https://groups.google.com/forum/#!topic/adam-developers/U6A1WCacTSw).

**Comment by calvertj** [comment]
Complete

**Comment by laserson** [comment]
Fixed by 782ee08a62a13ed650199fdbdcf84d7b31207577
