### ISSUE TITLE
Add S3 based Parquet directory loader

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#463]
Tagging @tdanford @carlyeks 

The current AvroParquetRDD loads just a single partition of a Parquet file from S3. If you have an indexed RDD, you can load a whole directory. We should add code to AvroParquetRDD so you can load a whole directory at once.

**Comment by heuermh** [comment]
Can this issue be closed?  I lost the thread in the jump to the utils project, was the relevant code in https://github.com/bigdatagenomics/utils/pull/10?

**Comment by fnothaft** [comment]
Yes, I think so. @tdanford are you OK with deleting the topic branch for this work?

**Comment by fnothaft** [comment]
Closing as won't fix.
