### ISSUE TITLE
Original qualities are parsed out, but left in attribute fields

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#483]
Not sure whether to call this a bug or not... When we convert from BAM, we parse the original qualities field out into the ADAM format, but we don't remove this from the attributes tag string. I have a suspicion that we do the same thing for all tags (e.g., OP, OC, MD)... For files with OC for example, this leads to a 25% penalty in size on disk.

**Comment by fnothaft** [comment]
@ibracadabra95 will be tackling this.

**Comment by Ibracadabra05** [comment]
Roger that.
