### ISSUE TITLE
ReferenceRegion shouldn't extend Ordered

### ISSUE THREAD

**Issue by tdanford** [bigdatagenomics/adam#511]
Currently, ReferenceRegion extends Ordered (everything here also applies, mutatis mutandis, to ReferenceRegionWithOrientation).  

This is a problem semantically, as according to Scala's docs (http://www.scala-lang.org/api/current/index.html#scala.math.Ordered) Ordered should only be used for types that have "a single, natural ordering" -- while we certainly can (and will) want to sort ReferenceRegions in multiple different ways.

Second, it has become a problem concretely as well: in defining some natural operations on RDDs of ReferenceRegions, I'm coming across a "diverging implicit expansion" error (http://stackoverflow.com/questions/4883906/what-is-a-diverging-implicit-expansion-error) that seems to be related to using Ordered on ReferenceRegions and subclasses of ReferenceRegion.

The solution I'm proposing to this is threefold: 
1. removed Ordered from the superclasses of ReferenceRegion, 
2. move the compareTo method in ReferenceRegion into the compare method of a ReferenceRegionOrdering, which will extend the Ordering trait (the correct trait we should be using when there is more than one ordering on a type), and 
3. provide an implicit Ordering in a new object, ReferenceRegionContext, that can be imported by classes that need the Ordering available.

**Comment by fnothaft** [comment]
Resolved since at least #624.
