### ISSUE TITLE
Need a RegionRDDFunctions class

### ISSUE THREAD

**Issue by tdanford** [bigdatagenomics/adam#512]
I want a RegionRDDFunctions class, which wraps an RDD of ReferenceRegions, and provides "common operations" on the regions within the RDD.  The common operations I'd like to see are: 

* join by overlap: join with another RDD of regions, the output of the join being pairs of regions (one from the wrapped RDD, one from the other RDD) that overlap
* join by range: similar to join by overlap, except that regions need to be within a particular 'range' of each other (where the range is a distance measured in bases).
* filter by overlap: filters the regions of the wrapped RDD, keeping only those regions that overlap _at least one_ region of a second RDD of regions
* filter by range: similar to the filter by overlap, except that we substitute (as we did with joins) 'within X bp' for 'overlap'
* group by overlap: basically, does a join by overlap followed by a groupBy
* group by range: same as above
* window counts: calculate fixed windows of a given size across the genome, and count how many regions from the input RDD overlap each window

Any other suggestions?

**Comment by heuermh** [comment]
I believe this issue should be marked as closed by #517.

**Comment by fnothaft** [comment]
Agreed. Closed by #517.
