### ISSUE TITLE
scala 2.11

### ISSUE THREAD

**Issue by antonkulaga** [bigdatagenomics/adam#536]
I see that Spark 1.20 supports scala 2.11, it would be great if adam would also move to it.

**Comment by ryan-williams** [comment]
So, did #664/#678 actually solve this, @fnothaft? It seems like they hard-coded `2.10` in everywhere, but I wasn't paying very close attention…

**Comment by fnothaft** [comment]
@ryan-williams check out the fun that is going on in https://github.com/bigdatagenomics/adam/blob/master/scripts/release/release.sh. ;)

I'm not _proud_ of what I did, but it works... I'll update the jenkins job in a sec so that we get SNAPSHOT artifacts for both Scala versions.

**Comment by ryan-williams** [comment]
ah yea I remember hearing about this magic! cool, thanks!

**Comment by fnothaft** [comment]
np! I wouldn't call it _magic_, but it does get the job done.
