### ISSUE TITLE
Create an ADAM Python API

### ISSUE THREAD

**Issue by laserson** [bigdatagenomics/adam#538]

**Comment by milos-popovic** [comment]
@laserson Hi, may I ask how is this project progressing? I've looked at https://github.com/laserson/adam/tree/ADAM-538-python, but it only has one commit and has been inactive for some time now. I was interested if the development has moved elsewhere, or it's on hold currently.

**Comment by fnothaft** [comment]
@milos-popovic one thing that might be easiest to do is to use the ADAM core to ETL data in to Parquet, and to then load data up using the Spark Dataframes API which is supported in Scala/Java/Python/R.

**Comment by milos-popovic** [comment]
@fnothaft Thanks for the quick reply, and sorry for the late one on my side. I have started using the Dataframes API for querying the ADAM parquet files. As for the PyADAM, is it still planned for development?

**Comment by laserson** [comment]
This is definitely still planned.  As you mentioned, using the dataframes API is the best workaround at the moment, except you don't get access to the region-join impls in ADAM.  This will definitely be the primary focus of getting the Python API up-and-running.

**Comment by milos-popovic** [comment]
@laserson That's good to know, though I'm not in a huge need for region-joins currently and DataFrame API is quite sufficient. I'll still be on the lookout for the project.

**Comment by nyetsche** [comment]
This if far from complete, but thanks to `py4j` already being included by `pyspark`, it's possible to interface with the ADAM code. Here's how:

```
# Get a list of the ADAM jars, it's okay to ignore the testing ones. Convert that list to a CLASSPATH style with : as the separator
$ export CLASSPATH=$(find $ADAM_HOME -name '*SNAPSHOT.jar' | tr '\n' ':')
# start pyspark
$ pyspark
[...]
SparkContext available as sc, HiveContext available as sqlContext.
>>> 
# Grab a copy of the JVM from the sparkcontext
>>> j = sc._jvm
# Grab a copy of the ADAM context through the Java API. NB: pass sc._jsc in as the argument, not sc which is a python object
>>> q = j.org.bdgenomics.adam.apis.java.JavaADAMContext(sc._jsc)
# Run ADAMContext methods
>>> a = q.loadAlignments("/tmp/small.adam")
```

Unfortunately I haven't found a good way to get Python to introspect the Java objects, so you'd need to cross-reference with the Java/Scala definitions.
