### ISSUE TITLE
adam-submit goes in a infinite loop messages of "INFO Client:Application report for application_"

### ISSUE THREAD

**Issue by tushu1232** [bigdatagenomics/adam#561]
15/02/02 23:18:04 INFO Client: Application report for application_1422512484476_0007 (state: ACCEPTED)
15/02/02 23:18:05 INFO Client: Application report for application_1422512484476_0007 (state: ACCEPTED)
15/02/02 23:18:06 INFO Client: Application report for application_1422512484476_0007 (state: ACCEPTED)
15/02/02 23:18:07 INFO Client: Application report for application_1422512484476_0007 (state: ACCEPTED)
15/02/02 23:18:08 INFO Client: Application report for application_1422512484476_0007 (state: ACCEPTED)
15/02/02 23:18:09 INFO Client: Application report for application_1422512484476_0007 (state: ACCEPTED)
<continuous display of these messages.>

It is a single node cluster

**Comment by massie** [comment]
Can you provide more information, e.g.?

* What version of ADAM?
* What was the command-line used to start the job?
* What version of Hadoop are you running? 
* Are you using Mesos or YARN?
* etc

**Comment by tushu1232** [comment]
Hello Matt,

  *   What version of ADAM?
0.15.1
Pulled from github yesterday so I suppose 0.15.*

  *   What was the command-line used to start the job?
The adam-submit script is in the attached file

  *   What version of Hadoop are you running?
spark-assembly-1.2.0-cdh5.3.0-hadoop2.5.0-cdh5.3.0.jar

  *   Are you using Mesos or YARN
Using YARN


[cloudera@quickstart ~]$ adam-submit
/home/cloudera/Downloads/adam/bin/adam-submit: line 71: /usr//bin/utils.sh: No such file or directory
/home/cloudera/Downloads/adam/bin/adam-submit: line 73: gatherSparkSubmitOpts: command not found
15/02/03 01:02:03 INFO RMProxy: Connecting to ResourceManager at quickstart.cloudera/127.0.0.1:8032<http://127.0.0.1:8032>
15/02/03 01:02:03 INFO Client: Requesting a new application from cluster with 1 NodeManagers
15/02/03 01:02:03 INFO Client: Verifying our application has not requested more than the maximum memory capability of the cluster (65536 MB per container)
15/02/03 01:02:03 INFO Client: Will allocate AM container, with 4480 MB memory including 384 MB overhead
15/02/03 01:02:03 INFO Client: Setting up container launch context for our AM
15/02/03 01:02:03 INFO Client: Preparing resources for our AM container
15/02/03 01:02:04 INFO Client: Uploading resource file:/usr/lib/spark/lib/spark-assembly-1.2.0-cdh5.3.0-hadoop2.5.0-cdh5.3.0.jar -> hdfs://quickstart.cloudera:8020/user/cloudera/.sparkStaging/application_1422783648837_0001/spark-assembly-1.2.0-cdh5.3.0-hadoop2.5.0-cdh5.3.0.jar
15/02/03 01:02:05 INFO Client: Uploading resource file:/home/cloudera/Downloads/adam/adam-cli/target/appassembler/repo/org/bdgenomics/adam/adam-cli/0.15.1-SNAPSHOT/adam-cli-0.15.1-SNAPSHOT.jar -> hdfs://quickstart.cloudera:8020/user/cloudera/.sparkStaging/application_1422783648837_0001/adam-cli-0.15.1-SNAPSHOT.jar
15/02/03 01:02:05 INFO Client: Setting up the launch environment for our AM container
15/02/03 01:02:05 INFO SecurityManager: Changing view acls to: cloudera
15/02/03 01:02:05 INFO SecurityManager: Changing modify acls to: cloudera
15/02/03 01:02:05 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(cloudera); users with modify permissions: Set(cloudera)
15/02/03 01:02:05 INFO Client: Submitting application 1 to ResourceManager
15/02/03 01:02:05 INFO YarnClientImpl: Submitted application application_1422783648837_0001
15/02/03 01:02:06 INFO Client: Application report for application_1422783648837_0001 (state: ACCEPTED)
15/02/03 01:02:06 INFO Client:
     client token: N/A
     diagnostics: N/A
     ApplicationMaster host: N/A
     ApplicationMaster RPC port: -1
     queue: root.cloudera
     start time: 1422954125777
     final status: UNDEFINED
     tracking URL: http://quickstart.cloudera:8088/proxy/application_1422783648837_0001/
     user: cloudera
15/02/03 01:02:07 INFO Client: Application report for application_1422783648837_0001 (state: ACCEPTED)
15/02/03 01:02:08 INFO Client: Application report for application_1422783648837_0001 (state: ACCEPTED)
15/02/03 01:02:09 INFO Client: Application report for application_1422783648837_0001 (state: ACCEPTED)
15/02/03 01:02:10 INFO Client: Application report for application_1422783648837_0001 (state: ACCEPTED)
Goes on infinitely till cntrl+c is hit

[cloudera@quickstart ~]$

**Comment by tushu1232** [comment]
Adam-submit

From: Tushar Pathare
Sent: Tuesday, February 03, 2015 12:40 PM
To: 'bigdatagenomics/adam'; bigdatagenomics/adam
Subject: RE: [adam] adam-submit goes in a infinite loop messages of "INFO Client:Application report for application_" (#561)

Hello Matt,

  *   What version of ADAM?
0.15.1
Pulled from github yesterday so I suppose 0.15.*

  *   What was the command-line used to start the job?
The adam-submit script is in the attached file

  *   What version of Hadoop are you running?
spark-assembly-1.2.0-cdh5.3.0-hadoop2.5.0-cdh5.3.0.jar

  *   Are you using Mesos or YARN
Using YARN


[cloudera@quickstart ~]$ adam-submit
/home/cloudera/Downloads/adam/bin/adam-submit: line 71: /usr//bin/utils.sh: No such file or directory
/home/cloudera/Downloads/adam/bin/adam-submit: line 73: gatherSparkSubmitOpts: command not found
15/02/03 01:02:03 INFO RMProxy: Connecting to ResourceManager at quickstart.cloudera/127.0.0.1:8032<http://127.0.0.1:8032>
15/02/03 01:02:03 INFO Client: Requesting a new application from cluster with 1 NodeManagers
15/02/03 01:02:03 INFO Client: Verifying our application has not requested more than the maximum memory capability of the cluster (65536 MB per container)
15/02/03 01:02:03 INFO Client: Will allocate AM container, with 4480 MB memory including 384 MB overhead
15/02/03 01:02:03 INFO Client: Setting up container launch context for our AM
15/02/03 01:02:03 INFO Client: Preparing resources for our AM container
15/02/03 01:02:04 INFO Client: Uploading resource file:/usr/lib/spark/lib/spark-assembly-1.2.0-cdh5.3.0-hadoop2.5.0-cdh5.3.0.jar -> hdfs://quickstart.cloudera:8020/user/cloudera/.sparkStaging/application_1422783648837_0001/spark-assembly-1.2.0-cdh5.3.0-hadoop2.5.0-cdh5.3.0.jar
15/02/03 01:02:05 INFO Client: Uploading resource file:/home/cloudera/Downloads/adam/adam-cli/target/appassembler/repo/org/bdgenomics/adam/adam-cli/0.15.1-SNAPSHOT/adam-cli-0.15.1-SNAPSHOT.jar -> hdfs://quickstart.cloudera:8020/user/cloudera/.sparkStaging/application_1422783648837_0001/adam-cli-0.15.1-SNAPSHOT.jar
15/02/03 01:02:05 INFO Client: Setting up the launch environment for our AM container
15/02/03 01:02:05 INFO SecurityManager: Changing view acls to: cloudera
15/02/03 01:02:05 INFO SecurityManager: Changing modify acls to: cloudera
15/02/03 01:02:05 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(cloudera); users with modify permissions: Set(cloudera)
15/02/03 01:02:05 INFO Client: Submitting application 1 to ResourceManager
15/02/03 01:02:05 INFO YarnClientImpl: Submitted application application_1422783648837_0001
15/02/03 01:02:06 INFO Client: Application report for application_1422783648837_0001 (state: ACCEPTED)
15/02/03 01:02:06 INFO Client:
     client token: N/A
     diagnostics: N/A
     ApplicationMaster host: N/A
     ApplicationMaster RPC port: -1
     queue: root.cloudera
     start time: 1422954125777
     final status: UNDEFINED
     tracking URL: http://quickstart.cloudera:8088/proxy/application_1422783648837_0001/
     user: cloudera
15/02/03 01:02:07 INFO Client: Application report for application_1422783648837_0001 (state: ACCEPTED)
15/02/03 01:02:08 INFO Client: Application report for application_1422783648837_0001 (state: ACCEPTED)
15/02/03 01:02:09 INFO Client: Application report for application_1422783648837_0001 (state: ACCEPTED)
15/02/03 01:02:10 INFO Client: Application report for application_1422783648837_0001 (state: ACCEPTED)
Goes on infinitely till cntrl+c is hit

[cloudera@quickstart ~]$

**Comment by massie** [comment]
I think the first two lines of output after running `adam-submit` give clues to what might be going on.

```
/home/cloudera/Downloads/adam/bin/adam-submit: line 71: /usr//bin/utils.sh: No such file or directory
/home/cloudera/Downloads/adam/bin/adam-submit: line 73: gatherSparkSubmitOpts: command not found
```

The `adam-submit` script is unable to find `bin/utils.sh`. If you look inside the `adam-submit` script, you will see the source of the problem is at lines 71 to 73, i.e.

```
source "$SPARK_HOME"/bin/utils.sh
SUBMIT_USAGE_FUNCTION=usage
gatherSparkSubmitOpts $NEW_OPTIONS
```

It appears that you don't have an environment variable, `SPARK_HOME`, set which points to your installation of Apache Spark. Once you have `SPARK_HOME` set, things should work.

Let us know if that's the problem or you need more help.

You can also find us online [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/bigdatagenomics/adam?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by heuermh** [comment]
ok to close?
