### ISSUE TITLE
Replace contig length maps with sequence dictionary

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#572]
I was stumbling across this with a few of our partitioner implementations. In the [two genomic partitioners](https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicPartitioners.scala), we pass a `seqLengths: Map[String, Int]` parameter. Shouldn't we just pass a `SequenceDictionary`? The `SequenceDictionary` already contains that information.

**Comment by laserson** [comment]
+1

**Comment by tdanford** [comment]
+1

**Comment by heuermh** [comment]
Closing as WontFix
