### ISSUE TITLE
Do reference partitioners restrict a partition to contain keys from a single contig?

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#573]
I wasn't sure about this and couldn't tell 100% for sure from looking at the code. When the [two reference partitioners](https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicPartitioners.scala) map keys to a partition, do they _ensure_ that a partition only contains keys from a _single_ reference contig?

This is relevant to my interests because I've got code that currently assumes that after a:

```
rdd.keyBy(ReferencePosition(_))
  .repartitionAndSortWithinPartitions(new GenomicPositionPartitioner(...))
```

The `_.pos` of all keys will be monotonically increasing (i.e., I'll _never_ wrap from the end of one contig to the start of the next contig). I don't think it's a _big_ deal either way (i.e., it would be easy to make my code handle wrapping), but it isn't documented in the partitioners file and it does impact whether my code will work or not.

**Comment by laserson** [comment]
Looks to me like a single partition can have multiple contigs.  I believe `GenomicRegionPartitioner` wil not though.
