### ISSUE TITLE
Remove wrapping by Option where throwing an exception is preferable

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#574]
This is pretty closely related to #297, #420, #421. There are a few places where we're wrapping by an option where we should really be throwing an exception if we would return `None`. The ones that stand out are:

* `ReferencePosition*` and `ReferenceRegion*`: If you provide an unmapped read/contig/genotype/X, you get a `None`.
* `RichAlignmentRecord`: Similar to the above...

Currently, I don't think we're optimizing for the _common case_. In my world, if you're asking for the position of an object, you have already checked to make sure that the object is mapped. If I'm doing variant calling, I'm going to filter out all unmapped reads first`*`. `ReferenceRegion`'s `apply(ar: AlignmentRecord)` returns an `Option[ReferenceRegion]`. This is bad in the common case, because I'm allocating an extra object (the `Option`), and then I have to unpack the `ReferenceRegion` from the option. _If_ the `Option` is a `None` anyways, `None.get` throws an exception _that has no useful debug info_.

This isn't to say that having a method that goes `AlignmentRecord => Option[ReferenceRegion]` isn't useful; IIRC, we need something like this for duplicate marking. My point is mostly that:

1. By default, we should assume that the common case is that the user is _providing good input_.
2. When the user provides _bad_ input, we should throw a detailed exception.

Evidently, I'm just in the mood to stir the pot tonight! I'd love to hear thoughts on this.

`*`: This assumes that I'm not going to do something like try to rescue unmapped reads. However, I believe that most unmapped read rescue algorithms rely on the mate read in the fragment being mapped, so the unmapped-ness of the read is irrelevant anyways.

**Comment by laserson** [comment]
+1
