### ISSUE TITLE
Upgrade to newer bdg-utils library

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#581]
The current bdg-utils version we're pointing at is built for Spark 1.1.0. A Spark method signature changed from 1.1.0 to 1.2.0, which leads to errors with the metrics.

**Comment by heuermh** [comment]
Can this issue be closed?  The bdg-utils dependency version is the most recent version 0.2.2 as of commit a70b4ca12299a9639275671cb20f7887c63ecb09.

**Comment by fnothaft** [comment]
Yes, it can. Thanks for pinging @heuermh!
