### ISSUE TITLE
Move the 'comparisons' code into a separate repository.

### ISSUE THREAD

**Issue by tdanford** [bigdatagenomics/adam#595]
As part of our attempt to slim down the core ``adam`` module into its minimal set of classes, and also as preparation for re-writing some of the Picard-style metrics (this is relevant to the NCI Cloud Pilot project), we should move out all the core code and commands which compute read- and variant-level metrics from the adam-core module into a separate module and repository. 

This repository (qc-metrics) has already been created.  This issue is for deleting the code (in org.bdgenomics.adam.metrics), the ComparisonTraversalEngine class, all their test suites, and the two commands (FindReads and CompareADAM) which depend on them.  

All of this will be re-created in the qc-metrics repository.

**Comment by fnothaft** [comment]
+1

**Comment by fnothaft** [comment]
Will you move the variant concordance work into [qc-metrics](https://www.github.com/bigdatagenomics/qc-metrics) as well?

**Comment by tdanford** [comment]
Where is that?

**Comment by fnothaft** [comment]
The big ones that I'm aware of are:

* https://github.com/bigdatagenomics/adam/blob/master/adam-cli/src/main/scala/org/bdgenomics/adam/cli/GenotypeConcordance.scala
* https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/rdd/variation/VariationRDDFunctions.scala

**Comment by tdanford** [comment]
Yeah, I'll move those.  One sec.  (I'm building up a corresponding branch in qc-metrics as I go, of course.)

**Comment by fnothaft** [comment]
Sounds awesome; looking forward to it!

**Comment by tdanford** [comment]
While I'm working on this (and I've got kid duty today, so it's intermittent) can you open up an issue or two, for any other major chunks of code like this that you think need to be moved to another repo too?

**Comment by fnothaft** [comment]
YGI, will do after brunch.

**Comment by tdanford** [comment]
Thx.
