### ISSUE TITLE
Migrate correction package into a downstream repository

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#597]
I've created a downstream repository ([corretto](https://github.com/bigdatagenomics/corretto)) for read error correction based utils. We should move the `org.bdgenomics.adam.rdd.read.correction` package there.

**Comment by fnothaft** [comment]
This will also likely lead to the elimination of `org.bdgenomics.adam.algorithms.prefixtrie`.

**Comment by tdanford** [comment]
+1
