### ISSUE TITLE
Migrate preprocessing stages out of ADAM

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#598]
I propose migrating the duplicate marker, BQSR engine, and indel realigner out of ADAM. I would suggest migrating them into [avocado](https://www.github.com/bigdatagenomics/avocado); @massie had also suggested migrating them into a repository or project submodule dedicated to pre-processing stages.

**Comment by fnothaft** [comment]
I suggest migrating them into avocado so that we'll have a single project that goes from reads->variant calls, but am open to suggestions.

**Comment by tdanford** [comment]
I vote for avocado, but I'm fine with either one. 

(Note, in the branch in avocado I have for mutect, I've also included other pre-processing steps.  It's convenient, and it'd be nice if avocado included "necessary pre-processing steps" too.)  

I think the only exception to this _might_ be the mark duplicates implementation -- I believe that that's a pre-processing step for some ChIP-seq (i.e. non-variant-calling) pipelines too.

**Comment by laserson** [comment]
I vote avocado for now as well.  And either Avocado will grow into other applications/uses, or we can restructure in the future as well.

**Comment by fnothaft** [comment]
I'm going to close this. I think that with recent changes to refactor the RDD package and to privatize code, this effort would now be unnecessary.
