### ISSUE TITLE
Fix record oriented shuffle

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#599]
Due to our shuffle being record oriented, we experience an approximately 8-10x increase in data volume when we shuffle. This is because our data is stored on disk in a columnar representation, but is shuffled in a row oriented format.

**Comment by tdanford** [comment]
So what's the proposed fix?

**Comment by fnothaft** [comment]
TBD?

**Comment by tdanford** [comment]
Gotcha.

**Comment by ryan-williams** [comment]
FTR: presumably @massie's [SPARK-7263](https://issues.apache.org/jira/browse/SPARK-7263) is our best hope here?
