### ISSUE TITLE
Consolidate join functionality via a trait

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#600]
This was discussed in #517. Instead of layering the functionality via an additional `RegionRDDFunctions` layer, @laserson proposed layering this on top of the various region join implementations via a trait.

It might also make sense to implement some sort of cardinality estimation to select a join strategy, but that should probably be follow on work.

**Comment by tdanford** [comment]
Agreed the cardinality stuff should be follow-on.
