### ISSUE TITLE
Consolidate ReferenceRegion, Position, etc.

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#601]
We had discussed this a bit on another thread; this winds up being a consolidation of #511, #517, #592, Here's what I propose:

1. Eliminate `ReferencePosition`. A `ReferencePosition` is just a special case of a `ReferenceRegion` (region with width = 1). For the cost of 1 `Long` field, we could eliminate a lot of duplicated code.
2. Eliminate the `*WithOrientation` models. We have a `Strand` enum: https://github.com/bigdatagenomics/bdg-formats/blob/master/src/main/resources/avro/bdg.avdl#L720.
3. Move `ReferenceRegion` to Avro. This will allow us to consolidate fields in `AlignmentRecord`, `Variant`, and `NucleotideContigFragment`. I think we'd keep the `org.bdgenomics.adam.models.ReferenceRegion` object, and consolidate an `apply` method, as well as the `overlaps`, `isAdjacent`, etc methods there.
4. As proposed in #511, add an `Ordering` for `ReferenceRegion`.

**Comment by tdanford** [comment]
+1 on the first two points, and the fourth.  Need to think about the third?

**Comment by tdanford** [comment]
Will this really allow us to consolidate AlignmentRecord, Variant, etc?  

Wouldn't the ideal be that those (generated) classes all inherit from a common ReferenceRegion superclass?  Is that possible with Avro?  

(Isn't this what sparked our discussion of Thrift on the call a week or two ago?)

**Comment by fnothaft** [comment]
I don't think it'd be ideal to have them inherit from a common class, because they all have different implementations. E.g., variants have a single required mapping. Reads (in the fragment model, which I prefer) have multiple optional mappings. Contigs have a single optional mapping.

**Comment by fnothaft** [comment]
I'll open a PR against bdg-formats showing what I'm talking about.

**Comment by tdanford** [comment]
That'd be great.

**Comment by laserson** [comment]
I agree with @tdanford.  Bullet 3 seems like a more complex issue, which I'm more ok to punt on at the moment.  I agree that there are advantages to having a non-Avro `ReferenceRegion`, so would it be confusing to *also* have an Avro `ReferenceRegion`?

**Comment by tdanford** [comment]
Frank, can you rewrite the issue description above to use a number list rather than bullets? :-)

**Comment by fnothaft** [comment]
> Frank, can you rewrite the issue description above to use a number list rather than bullets? :-)

Fixed!

**Comment by fnothaft** [comment]
Closed via #624.
