### ISSUE TITLE
Remove and generalize plugin code

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#602]
CCing @tdanford @heuermh for comments here.

I would like to strip the plugin code out of ADAM, and move it to a downstream repository, where we'd generalize it a bit further. Specifically, I'd like to have better support for injecting arguments, I'd like to allow plugins to be able to take more than 1 input RDD (e.g., for BQSR and INDEL realignment, where we'd want `RDD[AlignmentRecord], RDD[Variant] => RDD[AlignmentRecord]`), and I'd like to be able to string multiple plugin stages together into a pipeline.

This would also allow us to strip the cruddy "workflow" engine out of avocado.

I've got a few ideas for this that I'm playing around with. I'll ping here once those are a bit further along.

**Comment by tdanford** [comment]
I think @heuermh had the original requirement here...

**Comment by heuermh** [comment]
+1

Those requirements sound good to me.  We're still not ADAM-ing in anger yet, so using avocado to drive this refactor is probably a good idea.  What works for variant calling should also work for us.

The main requirement is that it should be easy to build, deploy, and use third party code along with ADAM-provided tools on an ADAM+Spark cluster.

**Comment by tdanford** [comment]
+1 for me too

**Comment by heuermh** [comment]
What do you think of the approach in https://github.com/heuermh/adam-commands for avocado?

It allows extension by ```ADAMCommand``` (or subclasses such as ```BDGSparkCommand```) instead of ```ADAMPlugin```, reuse of ```ADAMMain``` without code duplication, and may eliminate the need for avocado-specific shell scripts.

**Comment by fnothaft** [comment]
> What do you think of the approach in https://github.com/heuermh/adam-commands for avocado?
>
> It allows extension by ADAMCommand (or subclasses such as BDGSparkCommand) instead of ADAMPlugin, reuse of ADAMMain without code duplication, and may eliminate the need for avocado-specific shell scripts.

Not really interested. `Avocado` doesn't dupe `ADAMMain` and has special case code in the `avocado-submit` script...
