### ISSUE TITLE
Move command structure to bdg-utils?

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#603]
The command infrastructure is useful for much more than ADAM, and isn't really specific to genomics. For example, I myself use it in avocado, PacMin, and a few non-genomics projects. I'd like to move it to bdg-utils. At the same point in time, I think we could roll the build information work (see [here](https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/util/BuildInformation.scala) and [here](https://github.com/bigdatagenomics/adam/blob/master/adam-cli/src/main/scala/org/bdgenomics/adam/cli/BuildInformation.scala)) to the main command (e.g., as a command line argument, `-v`/`--version`).

This is similar to how we pulled `SparkFunSuite` out of ADAM. It's really useful code, but for projects where I don't need to bring `ADAM` in as a dependency (e.g., the non-omics ones referred to earlier), I'd really prefer not to pull it in.

**Comment by tdanford** [comment]
As an alternative, move the command structure further _up_ (or down, depending on your orientation) the food chain.  I ended up replicating a subset of ``ADAMMain`` as a class called ``QCMain`` in the qc-metrics repository.  

Maybe all the support classes (e.g. ``ADAMCommandCompanion``) can go in bdg-utils, and all the actual Main classes and commands can go in downstream repos?

**Comment by fnothaft** [comment]
@tdanford 

> Maybe all the support classes (e.g. ADAMCommandCompanion) can go in bdg-utils, and all the actual Main classes and commands can go in downstream repos?

That'd be my preference as well.

**Comment by tdanford** [comment]
+1.

**Comment by fnothaft** [comment]
@tdanford I've opened a PR upstream: https://github.com/bigdatagenomics/bdg-utils/pull/30. I'll open a PR against ADAM tomorrow showing what these changes would look like.

**Comment by laserson** [comment]
+1 to factoring out the common stuff

**Comment by fnothaft** [comment]
This was closed by #678.
