### ISSUE TITLE
Remove bdg-utils-parquet

### ISSUE THREAD

**Issue by tomwhite** [bigdatagenomics/adam#634]
Most of the Parquet code in bdg-utils-parquet is unused as far as I can tell, so we should remove it to remove confusion about what it's for. If changes are needed to Parquet then I would encourage them to be made in the Parquet project itself. However, I don't think any Parquet changes are actually required at this point (please correct me if I'm wrong).

The two uses I found in ADAM are ParquetLister and the org.bdgenomics.utils.parquet.io package.

ParquetLister is only used from two CLI tests, so I would suggest simplifying it and moving it to the test package (here's a commit showing how: https://github.com/bigdatagenomics/adam/commit/a78ac65a9ff7b6ee8b4bc046930a3196a67b21ee). I would expect production code to use a ParquetReader or ParquetInputFormat directly.

The org.bdgenomics.utils.parquet.io package doesn't actually contain any Parquet code. ByteAccess is a general purpose IO class used by TwoBitFile in ADAM. Byte access and its associated classes could either move into org.bdgenomics.adam.io in ADAM (I know it was moved from there a few months ago), or into a new bdg-utils-io module in a org.bdgenomics.utils.io package. Any thoughts on this?

Once these changes have been made bdg-utils-parquet can be removed.

**Comment by fnothaft** [comment]
@tomwhite I'm going to close this, as I believe we've purged this. Please reopen if I am in error.
