### ISSUE TITLE
About args.coalesce

### ISSUE THREAD

**Issue by simplelive** [bigdatagenomics/adam#655]
I want to set args.coalesce=1，can i modify [if (args.coalesce > 1)] to [if (args.coalesce > 0)] ?

64     if (args.coalesce > 1) { 
65       adamVariants = adamVariants.coalesce(args.coalesce, true) 
66     } 

https://github.com/bigdatagenomics/adam/blob/master/adam-cli/src/main/scala/org/bdgenomics/adam/cli/Vcf2ADAM.scala

**Comment by fnothaft** [comment]
+1, good catch. If you can put together a PR to fix, that'd be great!

**Comment by simplelive** [comment]
https://github.com/bigdatagenomics/adam/pull/656

**Comment by fnothaft** [comment]
Closed by #656.
