### ISSUE TITLE
Move from utils-parquet to utils-io.

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#657]
Since https://github.com/bigdatagenomics/utils/pull/33 and #645 have merged, we should cut over from `org.bdgenomics.utils.parquet` to `org.bdgenomics.utils.io`.

**Comment by tomwhite** [comment]
@fnothaft I think we need a release of bdg-utils (0.1.3) to do this, don't we?

**Comment by fnothaft** [comment]
Ah! Yes, good call. I'm a bit swamped today and tomorrow but will cut utils/0.1.3 on Wednesday.

**Comment by fnothaft** [comment]
I just cut utils/0.2.0, which will hit in Maven Central tomorrow. I'll open a PR tomorrow AM to fix this and unblock #654.

**Comment by fnothaft** [comment]
This was closed by #678.
