### ISSUE TITLE
xAssembler cannot be build using mvn

### ISSUE THREAD

**Issue by Mussadiq123** [bigdatagenomics/adam#658]
Here is the error message.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] xASSEMBLEx: an ADAM/GraphX based assembler ......... SUCCESS [ 11.413 s]
[INFO] xASSEMBLEx-core: assembly libraries using GraphX ... FAILURE [  7.806 s]
[INFO] xASSEMBLEx-cli: an ADAM/GraphX based assembler ..... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.943 s
[INFO] Finished at: 2015-04-27T00:04:03-04:00
[INFO] Final Memory: 18M/93M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project xASSEMBLEx-core: Could not resolve dependencies for project org.bdgenomics.xASSEMBLEx:xASSEMBLEx-core:jar:0.0.1: The following artifacts could not be resolved: org.bdgenomics.adam:adam-core:jar:0.12.1-SNAPSHOT, org.bdgenomics.adam:adam-core:jar:tests:0.12.1-SNAPSHOT: Could not find artifact org.bdgenomics.adam:adam-core:jar:0.12.1-SNAPSHOT in Sonatype (http://oss.sonatype.org/content/repositories/snapshots/) ->

**Comment by fnothaft** [comment]
Hi @Mussadiq123

xASSEMBLEx was some test/demo code I put together and hasn't been updated in a while. It is several releases of ADAM behind, hence the build failure. Are you interested in using ADAM for de novo assembly?

**Comment by Mussadiq123** [comment]
I see. I thought we can use it for genome assembly

**Comment by Mussadiq123** [comment]
Yes i'm interested

**Comment by fnothaft** [comment]
It needs a bit more work before it can be used for genome assembly. I won't be able to work on it for at least the next two weeks, but I could do a bit of work to clean xASSEMBLEx up in two weeks to a months time.

**Comment by Mussadiq123** [comment]
That will be awesome. Thanks. What strategy will be best if the size of data is greater the amount of available memory?
