### ISSUE TITLE
ADAM scripts should handle missing bin/utils.sh in Spark 1.4 and later

### ISSUE THREAD

**Issue by tomwhite** [bigdatagenomics/adam#659]
The ADAM scripts use Spark's bin/utils.sh, but this has been removed in [SPARK-4924](https://issues.apache.org/jira/browse/SPARK-4924), which will be in Spark 1.4.

The scripts should check to see if bin/utils.sh is present, and if not, use the new way of invoking spark-submit that doesn't need the script.

**Comment by laserson** [comment]
This is a good opportunity to revamp how the adam-submit command works a bit.  Marcelo from the Spark team suggested we explicitly enforce separation of Spark vs ADAM flags.

**Comment by heuermh** [comment]
@laserson I was thinking of taking this on, feel free to bring me up to speed :)

**Comment by laserson** [comment]
Go ahead, and happy to review.  The only issue was that initially, we tried to make `adam-submit` act like `spark-submit`, so you could mix and match Spark and ADAM options, IIRC.  This was done using the `gatherSparkSubmitOpts` function in `bin/utils.sh`.  But this was probably a bad idea, as Spark changed the way they process their options quite a bit, which made it hard for us even before this change.  I have not been following how Spark has changed `spark-submit`, but we should probably simply have our own method that's consistent and easy to deal with, and map it to the correct `spark-submit` call.  For example, Marcelo V. suggested one option as simply separating Spark options from ADAM options with `--`, and having the Spark options first.

**Comment by ryan-williams** [comment]
I don't have much state on this, but IIRC Spark's `--conf spark.foo.bar=baz`-style parameters get ignored if the key doesn't start with "spark.".

Could we encourage use of `--conf adam.foo.bar=baz` params, for a consistent feel when used alongside Spark params, but with easy distinguishability?

**Comment by fnothaft** [comment]
@ryan-williams that sounds reasonable to me.

**Comment by laserson** [comment]
@heuermh have you started working on this btw?

**Comment by heuermh** [comment]
Still in research mode at this point.

**Comment by laserson** [comment]
I'm pinging @vanzin on this.

**Comment by laserson** [comment]
@vanzin reminded me of #660, which is probably what we should implement.

**Comment by heuermh** [comment]
Close as fixed by #754?
