### ISSUE TITLE
Refactor adam-submit to make user separate Spark and ADAM opts

### ISSUE THREAD

**Issue by laserson** [bigdatagenomics/adam#660]
Currently the `spark-submit` command reaches into the "internals" of the Spark CLI option parsing functions, which is precarious because it changes occasionally.  Both @vanzin and @srowen suggested requiring the user to manually separate the Spark and ADAM commands, making it easier for us to parse the command line.  Any thoughts on this?

**Comment by fnothaft** [comment]
+1, I think @tomwhite raised a similar point in #659. Anything that would improve stability across Spark releases sounds wise to me.

**Comment by ryan-williams** [comment]
@laserson did you mean `adam-submit` when you said `spark-submit` above?

**Comment by heuermh** [comment]
Close as fixed by #754?

**Comment by fnothaft** [comment]
@heuermh +1
