### ISSUE TITLE
Kill `job` argument to ADAMSparkCommand.run?

### ISSUE THREAD

**Issue by ryan-williams** [bigdatagenomics/adam#662]
[The second arg here](https://github.com/bigdatagenomics/adam/blob/492fb3b04fc1ebe279e8aaa95f7b290cef911f27/adam-cli/src/main/scala/org/bdgenomics/adam/cli/ADAMCommand.scala#L46), `job: Job`, is never used in any ADAM command afaict.

Some tests seem to pass a value in, as if some dependency-injection is happening, but I can't see how that value would ever be used in the current world.

Am I missing something?

**Comment by ryan-williams** [comment]
(woops, submitted too early, finished the description above and added a link)

**Comment by ryan-williams** [comment]
on second look, the tests I was looking at, e.g. [`FlattenSuite`](https://github.com/bigdatagenomics/adam/blob/492fb3b04fc1ebe279e8aaa95f7b290cef911f27/adam-cli/src/test/scala/org/bdgenomics/adam/cli/FlattenSuite.scala#L58), seem to just be passing in a dummy job to satisfy the API as well.

**Comment by laserson** [comment]
+1.  Get rid of stuff we don't need.

**Comment by fnothaft** [comment]
So with #603, the CLI classes are moving to [utils](https://github.com/bigdatagenomics/utils/pull/30). I'm opening a PR to resolve #603 (should be ready in an hour). I think removing `Job` is OK.

**Comment by ryan-williams** [comment]
OK, I have a PR close to ready here but will hold off for #603 if you think that's better sequencing @fnothaft, lmk!

**Comment by fnothaft** [comment]
@ryan-williams if you want to open the PR against utils, that's probably the easiest way to go.
