### ISSUE TITLE
include adam-cli in jars to send to Spark?

### ISSUE THREAD

**Issue by ryan-williams** [bigdatagenomics/adam#663]
[This comment in `compute-adam-jars.sh`](https://github.com/bigdatagenomics/adam/blob/492fb3b04fc1ebe279e8aaa95f7b290cef911f27/bin/compute-adam-jars.sh#L25-L26) implies that we intentionally leave the `adam-cli` JAR off of the classpath for Spark jobs/shells.

I was stymied today for a while because I was working from an `adam-shell` and, among other things, wanted to run a `FlagStat` on a BAM in a way that was faithful to the way it gets run normally / via `adam-submit`, e.g. `FlagStat(Array(filename)).run(sc, job)`.

Is it important that CLI code not be made available to `adam-shell` sessions? Can/Should we remove this trimming of the `adam-cli` jar?

**Comment by fnothaft** [comment]
Hah, drat! Yes, I'd agree that it makes sense _not_ to trim the _adam-cli_ jar. @laserson?

**Comment by fnothaft** [comment]
Hah, drat! Yes, I'd agree that it makes sense _not_ to trim the `adam-cli` jar. @laserson?

**Comment by ryan-williams** [comment]
yea, thinking on this more I became confused about how the CLI is available to e.g. `adam-submit`; well, seems like [we add it back in manually](https://github.com/bigdatagenomics/adam/blob/492fb3b04fc1ebe279e8aaa95f7b290cef911f27/bin/adam-submit#L90) after it's [been excluded from the `compute-adam-jars` calculation](https://github.com/bigdatagenomics/adam/blob/492fb3b04fc1ebe279e8aaa95f7b290cef911f27/bin/adam-submit#L23-L24). TIL!

That would seem to support adding it back in.

**Comment by laserson** [comment]
hmm, my laziness tells me there should be some reason that I explicitly excluded the CLI jar, or else I wouldn't've done it.  But try adding it back in and see if it works.

**Comment by ryan-williams** [comment]
seems to be working for me locally, I'll send a PR shortly
