### ISSUE TITLE
spark 1.3.1 upgarde to hortonworks HDP 2.2.4.2-2?

### ISSUE THREAD

**Issue by cusvenus09** [bigdatagenomics/adam#675]
I am trying to upgarde spark from 1.2.1 to 1.3.1 from spark and integrate with YARN. I have installed HDP 2.2 using ambari.

Does anyone have experience integrating the spark 1.3.1 with YARN on HDP 2.2 platform?

Error: I am getting is as below:

WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

**Comment by massie** [comment]
You can ignore that warning. http://stackoverflow.com/questions/19943766/hadoop-unable-to-load-native-hadoop-library-for-your-platform-error-on-centos

**Comment by cusvenus09** [comment]
Thanks massie. However I want to choose the appropriate version of spark binaries which can work with Hortonworks HDP.

![image](https://cloud.githubusercontent.com/assets/12537009/7740572/a6966ae0-ff28-11e4-9b60-571bf8f047eb.png)

Do you know which pre-built suits for HDP 2.2.4.2-2 version?

**Comment by fnothaft** [comment]
Closing as out of scope.
