### ISSUE TITLE
adamParquetSave has a menacing false error message about *.adam extension

### ISSUE THREAD

**Issue by laserson** [bigdatagenomics/adam#681]
ADAM no longer enforces the `.adam` extension on files.

**Comment by heuermh** [comment]
I don't see any messages about ```.adam``` extensions, can this be closed?

**Comment by laserson** [comment]
Haven't used ADAM in a bit, but I'll reopen/refile if I see it again in the future.

**Comment by fnothaft** [comment]
Closing as resolved.
