### ISSUE TITLE
Nit: unnecessary check in ShuffleRegionJoin

### ISSUE THREAD

**Issue by ryan-williams** [bigdatagenomics/adam#683]
IIUC, [this `nextLeftRegion.start > prevLeftRegion.start` clause](https://github.com/bigdatagenomics/adam/blob/9f0f41a75a550d85dc98cd2299d79e18b576bbf6/adam-core/src/main/scala/org/bdgenomics/adam/rdd/ShuffleRegionJoin.scala#L258) will always be `true`, since `leftIter`/`left` are [assumed to be in sorted order](https://github.com/bigdatagenomics/adam/blob/9f0f41a75a550d85dc98cd2299d79e18b576bbf6/adam-core/src/main/scala/org/bdgenomics/adam/rdd/ShuffleRegionJoin.scala#L210); I presume this "sorted order" refers to their `start` coordinates, and afaict that's what is meant by "sorts by ReferenceRegion" (and implemented) [here](https://github.com/bigdatagenomics/adam/blob/9f0f41a75a550d85dc98cd2299d79e18b576bbf6/adam-core/src/main/scala/org/bdgenomics/adam/rdd/ShuffleRegionJoin.scala#L100-L108).

**Comment by laserson** [comment]
Strictly speaking, the clause will not be always true, if the next region has the same start coordinate as the previous one.  Your change now always executes `pruneCache`, which is probably negligibly less efficient.  Also, just double-checking, but your change requires half-open intervals, which I believe they are IIRC (right?).

**Comment by ryan-williams** [comment]
Ah, ok maybe that's my bad then @laserson, I'll look at this again and maybe send an undo shortly

**Comment by ryan-williams** [comment]
#706 undoes that part of #683 @laserson, thanks for checking on this, sorry for the mistake!
