### ISSUE TITLE
Support parsing an RDD[Feature] from a Picard `.interval_list` file

### ISSUE THREAD

**Issue by ryan-williams** [bigdatagenomics/adam#685]
AFAICT ADAM can currently [load GTF, BED, NarrowPeak, and Parquet files as `RDD[Feature]`s](https://github.com/bigdatagenomics/adam/blob/9f0f41a75a550d85dc98cd2299d79e18b576bbf6/adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala#L358-L378).

I have some Picard `.interval_list` files ([example](https://gist.github.com/ryan-williams/5b4aba85c20e29de8f7a); [docs](http://gatkforums.broadinstitute.org/discussion/1204/what-input-files-does-the-gatk-accept)) I'd like to read in.

Let me know if this is already possible, otherwise I'll see about writing a parser.

**Comment by fnothaft** [comment]
Ah, yeah, I had to deal with some of these recently too... I was a bit rushed at the time, so I hacked a bit together (https://github.com/fnothaft/fig/blob/master/src/main/scala/net/fnothaft/fig/models/ReferencePromoter.scala#L28). It doesn't load _exactly_ to `Feature`, but there might be something you can cannibalize from the code. I've been meaning to refactor it but haven't had the time yet.

**Comment by fnothaft** [comment]
Closed by https://github.com/bigdatagenomics/adam/commit/35fbbb6a13ae5e8db142bec473e758fde729b3b2.
