### ISSUE TITLE
Remove no-SequenceDictionary API from ShuffleRegionJoin

### ISSUE THREAD

**Issue by ryan-williams** [bigdatagenomics/adam#697]
As discussed on #693, this seems like a dangerous API that confers very little benefit/convenience; [the singleton `sd` instance](https://github.com/bigdatagenomics/adam/blob/2b5c8e959dd5c7a321dfb8d97b9c7b6b08a0eef6/adam-core/src/main/scala/org/bdgenomics/adam/rdd/ShuffleRegionJoin.scala#L32) is also kind of gross and unnecessary.

We should make/let callers compute the `SequenceDictionary`.

**Comment by fnothaft** [comment]
Cutting over from #693. Paging @tdanford @laserson for comment.

> Partially answering my own question, you mean we should use ADAMSpecificRecordSequenceDictionaryRDDAggregator to basically get the SequenceDictionary-relevant fields out of whichever object we are joining, by ~reflection?

Ignore what I was saying earlier ;). I was commenting without looking at the code and thought the join method signature was different. If the signature was what I thought it was, then it'd have made sense.

> The use case strawman: "I have this RegionJoin that could be a ShuffleRegionJoin or a BroadcastRegionJoin and I don't know or care which one it is" doesn't seem to be that substantiated yet (please correct me if I'm wrong, I basically only paged in all of this stuff Saturday :) ).

At least from my perspective, that's not the motivation; arguably, it's _part of_ the motivation, but not the main motivation. The original motivation of the `RegionJoin` trait was to describe a _join engine_. Once you've got a join engine, you can then define other algorithms that use the join engine. E.g., you can have a region overlap join, region equi-join, region proximity join, region multi-join, etc., all of which use the central engine.

That being said, I agree that the `RegionJoin` trait doesn't really do what we want. If you want to remove the trait, I think that'd make sense. I've got an idea for a new, better abstraction. In the next few days, I'll try to open a PR that builds on top of #698 with a new proposed abstraction.

**Comment by ryan-williams** [comment]
OK, I think the desire for a *region-join engine* makes sense in the context of various derivative styles of region-join one might want to do, cf. what #517 was getting at IIUC?

Backing up a step: my issue here is with the API that allows you to accidentally do a broken region-join with no SD having been set.

We could keep `RegionJoin` and change `ShuffleRegionJoin` to a class that takes a `SequenceDictionary` and `partitionSize` as ctor args, for example. Maybe that would solve my issue while taking less of a step away from the vision of the generalized `RegionJoin` abstraction?

**Comment by ryan-williams** [comment]
I'll test out a PR that does this, maybe on #698.

**Comment by ryan-williams** [comment]
^^ done

**Comment by fnothaft** [comment]
> OK, I think the desire for a region-join engine makes sense in the context of various derivative styles of region-join one might want to do, cf. what #517 was getting at IIUC?

Exactly!

> Backing up a step: my issue here is with the API that allows you to accidentally do a broken region-join with no SD having been set.

A valid issue...

> We could keep RegionJoin and change ShuffleRegionJoin to a class that takes a SequenceDictionary and partitionSize as ctor args, for example. Maybe that would solve my issue while taking less of a step away from the vision of the generalized RegionJoin abstraction?

This seems like a step in the correct direction. I do think we need to enhance the `RegionJoin` trait, but I think that's a bit of a step beyond this PR. I would be +1 to merging #698 as is, and then opening a later PR to further enhance the `RegionJoin` trait.

**Comment by ryan-williams** [comment]
Great, I feel good about this outcome as well.

**Comment by fnothaft** [comment]
Yeah, I think it's the right way to go! I'm going to leave this open for a day, in case @tdanford or @laserson want to comment (and because I'm cutting the 0.17.0 release).

**Comment by fnothaft** [comment]
BTW, can you rebase?

**Comment by laserson** [comment]
+1.  Looks cleaner this way.

**Comment by ryan-williams** [comment]
rebased!

**Comment by tdanford** [comment]
@fnothaft I know I'm a little late to this discussion -- but I agree wholeheartedly with this: "The original motivation of the RegionJoin trait was to describe a join engine. Once you've got a join engine, you can then define other algorithms that use the join engine."  That was the original intent, at least from my and @carlyeks's perspective, if I can be so bold as to speak for him.  

Agreed that RegionJoin as it had evolved didn't do what we wanted, and happy to see the changes.
