### ISSUE TITLE
Upgrade to htsjdk 1.133

### ISSUE THREAD

**Issue by ryan-williams** [bigdatagenomics/adam#699]
It [just came out](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.github.samtools%22%20AND%20a%3A%22htsjdk%22), might as well…

**Comment by fnothaft** [comment]
Resolved by https://github.com/bigdatagenomics/adam/commit/1adc0db7700c4d9d435fcda35e6306ef97d2c098.
