### ISSUE TITLE
Update recommended Maven PermGen settings?

### ISSUE THREAD

**Issue by ryan-williams** [bigdatagenomics/adam#707]
@ipurusho recently ran into PermGen issues ([gist](https://gist.github.com/ipurusho/b1a0a74832a340679cb9)) trying to build ADAM on a clean checkout, with [the recommended `MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=128m"`](https://github.com/bigdatagenomics/adam/blob/4aadaf4e67ffc34f8b9c4580dd555bc2fc976059/README.md#installation).

I noticed that I have `MAVEN_OPTS=-Xmx512m -XX:MaxPermSize=256m` in my `.bashrc`; should we bump the recommended size up?

**Comment by fnothaft** [comment]
I think that makes sense. FWIW, I run with even large memory settings:

```
fnothaft$ echo $MAVEN_OPTS
-Xmx2g -XX:MaxPermSize=1g
```

**Comment by laserson** [comment]
+1.  I have also had to increase the memory.

**Comment by fnothaft** [comment]
Closed via https://github.com/bigdatagenomics/adam/commit/a94b9c98e314eb1d424859b504b76527df73a97c.
