### ISSUE TITLE
Support writing RDD[Feature] to various file formats

### ISSUE THREAD

**Issue by ryan-williams** [bigdatagenomics/adam#710]
- [ ] GTF
- [ ] BED
- [ ] .interval_list (cf. #703)
- [ ] NarrowPeak

I'm imagining methods in `FeatureRDDFunctions` analogous to the {Sam,Bam,Adam,Fastq} methods in `AlignmentRecordRDDFunctions`.

**Comment by laserson** [comment]
+1, though this may run into some model incompatibilities.

**Comment by fnothaft** [comment]
Do we want this to be automagical or explicit or both?

BTW, I didn't realize you could do subfeatures with the checkboxes. Nifty!

**Comment by ryan-williams** [comment]
I like the place we netted out at with "reads" files/formats: expose a method that infers format from file format and delegates to other exposed format-specific methods, so that the caller can choose to specify format or not.

**Comment by fnothaft** [comment]
I think that sounds good too. Let's have that be the default approach moving forward.

**Comment by fnothaft** [comment]
Closed by https://github.com/bigdatagenomics/adam/commit/8abb47ad2447bbc0376f9b5052e2e029bdf6b604.
