### ISSUE TITLE
Remove no longer revelant files from scripts directory

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#723]
From a quick review, the following files in the ```scripts``` directory can/should be removed:

https://github.com/bigdatagenomics/adam/blob/master/scripts/create-thirdparty-repo.sh
https://github.com/bigdatagenomics/adam/blob/master/scripts/contextutil-converter.sh
https://github.com/bigdatagenomics/adam/blob/master/scripts/adam-console.sh
https://github.com/bigdatagenomics/adam/blob/master/scripts/scala-console.scala
https://github.com/bigdatagenomics/adam/blob/master/scripts/jenkins-test

**Comment by fnothaft** [comment]
`jenkins-test` is used by @AmplabJenkins, all the others look good to remove.

**Comment by heuermh** [comment]
Some of the references might need to be updated then (Spark 1.1.0, Hadoop 2.3), e.g.
https://github.com/bigdatagenomics/adam/blob/master/scripts/jenkins-test#L30
https://github.com/bigdatagenomics/adam/blob/master/scripts/jenkins-test#L34

**Comment by fnothaft** [comment]
+1 to that.

**Comment by massie** [comment]
@fnothaft I checked the ADAM Jenkins configuration and I don't see `jenkins-test` being used. It's just a `mvn clean package`. Where is it used?

**Comment by fnothaft** [comment]
@massie `jenkins-test` runs in an execute shell stage after the `mvn clean package`.

**Comment by massie** [comment]
<img width="370" alt="screen shot 2015-07-08 at 4 13 18 pm" src="https://cloud.githubusercontent.com/assets/19554/8584534/5e6ce322-258c-11e5-9f30-9a482ebb326b.png">

Aha! I missed it inside the if (2.10) clause at the end. Does that mean that we only run the `jerkins-test` for 2.10 and not 2.11?

**Comment by fnothaft** [comment]
Correct; Spark does not provide pre-built packages for Scala 2.11 (they do provide maven artifacts for 2.11 though).

**Comment by heuermh** [comment]
Closed by #724
