### ISSUE TITLE
MDTag deletions are incorrect for reads with N CIGAR operators

### ISSUE THREAD

**Issue by arahuja** [bigdatagenomics/adam#726]
The current `MdTag` constructor is 
```
def apply(mdTagInput: String, referenceStart: Long): MDTag
```
however, without the CIGAR, this will place mismatches/deletions at the wrong positions if the CIGAR contains `N` operators (as in an RNA read)

example:
```
sequence: CCAGCGATGAAGCCGCCCAGTTCAATACAACAAGTGAGTTTGACTCATCA
mdTag: 28^A22
cigar: 15M_2816N_13M1D22M
```

To handle this, it seems the MDTag should process the CIGAR as well?  I can add this in, but wanted to see if this was the correct approach or whether this case should be handled separately?

**Comment by fnothaft** [comment]
@arahuja I think you're right. Good catch!

**Comment by fnothaft** [comment]
Closed by https://github.com/bigdatagenomics/adam/commit/68f5b4a158049dea33513d7bce94828ff40ff993.
