### ISSUE TITLE
Update MdTag.getReference for CIGAR N

### ISSUE THREAD

**Issue by arahuja** [bigdatagenomics/adam#742]
Building off of #727 `MdTag.getReference` will throw an exception when operating on RNA reads with CIGAR `N`.

``` scala
          if (cigarElement.getOperator.consumesReferenceBases) {
            throw new IllegalArgumentException("Cannot handle operator: " + cigarElement.getOperator)
          }
```

It's not clear what the _right_ thing to do here though as at best with the MdTag you could fill the reference in with `N` bases, but there wouldn't be anyway of knowing what the reference base actually was (without looking at the reference)

**Comment by fnothaft** [comment]
You could additionally change `MdTag.getReference` to return an array of strings. Padding with `N` seems perfectly reasonable to me, although it is a bit of an overload for the `N` base. Semantically, I tend to think of the `N` base as a reference gap, or a misread base. If we are concerned about that, we could use `*` instead.

What exactly is the use case for this? Most of the time, the skip operator for an RNA-seq read will be covering a spliced-out intron, or an alternatively-spliced-out exon, right? If that is the case, then I wouldn't generally expect getting the _exact_ reference sequence back to be of much concern, which would speak for the `N`/`*` solution.

**Comment by arahuja** [comment]
I don't have a use-case for this now, so I'm up not updating it.  It was more that if anything processing RNA tries to call this function it might unexpectedly throw an exception __even__ if you want to know the reference base where there is a read base (not overlapping the `N`, but before or after)

**Comment by heuermh** [comment]
Closing as WontFix
