### ISSUE TITLE
Update ADAM formula in homebrew-science

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#747]
The ADAM formula in homebrew-science is still at version 0.13.0
https://github.com/Homebrew/homebrew-science/blob/master/adam.rb

The current version of Spark available from homebrew is 1.4.1, which won't work with ADAM version 0.17.0 due to https://github.com/bigdatagenomics/adam/issues/659.

Depending on [apache-spark121](https://github.com/Homebrew/homebrew-versions/blob/master/apache-spark121.rb) or [apache-spark131](https://github.com/Homebrew/homebrew-versions/pull/930) from homebrew-versions may be a workaround.

**Comment by laserson** [comment]
Good call.  Do we have a release checklist?  Perhaps we could add homebrew-science to it?

**Comment by heuermh** [comment]
There is this doc, which could be expanded on
https://github.com/bigdatagenomics/adam/blob/master/scripts/release/README

**Comment by fnothaft** [comment]
Actually, would it be possible to script the update to homebrew-science? The update is just a Github PR. My general preference is to script the entirety of doing a release.

**Comment by heuermh** [comment]
I think we want to pick up #754 so that we're compatible with apache-spark on homebrew (currently 1.4.1).  Thus I suggest we hold off on creating a new formula until the next ADAM release (0.18.0 presumably).

**Comment by fnothaft** [comment]
@heuermh SGTM

**Comment by heuermh** [comment]
Pull request here https://github.com/Homebrew/homebrew-science/pull/2738

**Comment by heuermh** [comment]
Fixed upstream

**Comment by fnothaft** [comment]
+1 nice!
