### ISSUE TITLE
Explain or remove references to `adam` shell alias in README

### ISSUE THREAD

**Issue by ryan-williams** [bigdatagenomics/adam#759]
Seen [here](https://github.com/bigdatagenomics/adam/blob/1cf8ebb0c39f924086448ed881e3be0c1639d5da/README.md#more-than-k-mer-counting); it's also not in the code-block that it seems like it's supposed to be in.

Should it be `adam-submit` instead of `adam`?

**Comment by fnothaft** [comment]
> Should it be `adam-submit` instead of `adam`?

I believe that you are correct.

**Comment by ryan-williams** [comment]
Fixed by #763, TIL a way that github doesn't interpret multiple issues as closed by a single PR :)
