### ISSUE TITLE
Clean up README intro bullet points?

### ISSUE THREAD

**Issue by ryan-williams** [bigdatagenomics/adam#761]
The opening blob of bullet points in the README seems a little overwhelming to me.

![](http://cl.ly/image/1M0Y131v2j0R/Screen%20Shot%202015-08-07%20at%205.49.14%20PM.png)

Any interest in trying to make it clearer / more punch-ful? Two ideas for doing so:

- [ ] A Gitter badge instead of the link to gitter
- [x] Hyperlinking some of the text instead of putting full URLs in each bullet?
- [ ] Does Jenkins do build-status badges?

For example:

* [Follow our Twitter account](https://twitter.com/bigdatagenomics/).
* [Chat with ADAM developers in Gitter](https://gitter.im/bigdatagenomics/adam).
* [Join our mailing list](http://bdgenomics.org/mail).
* [Checkout the current build status](https://amplab.cs.berkeley.edu/jenkins/view/Big%20Data%20Genomics/).
* [Download official releases](https://github.com/bigdatagenomics/adam/releases).
* [View our software artifacts on Maven Central](http://search.maven.org/#search%7Cga%7C1%7Corg.bdgenomics) ([…including snapshots](https://oss.sonatype.org/index.html#nexus-search;quick~bdgenomics)).
* [Look at our CHANGES file](https://github.com/bigdatagenomics/adam/blob/master/CHANGES.md).

This could be put under a "Quick Links" sub-header, possibly lower down the page, too.

…just $0.02. (NB: [this gist](https://gist.github.com/ryan-williams/c680ae907f8b422e53b4) has the markdown for the above so that we don't have to type it again if we decide to do this :) )

**Comment by fnothaft** [comment]
+1. Could you PR the gist?

**Comment by fnothaft** [comment]
As for @AmplabJenkins, this exists: https://wiki.jenkins-ci.org/display/JENKINS/Embeddable+Build+Status+Plugin

@massie @shaneknapp would you all be OK with installing this?

**Comment by heuermh** [comment]
+1 to doc changes and Jenkins status badge

**Comment by ryan-williams** [comment]
cool, I dropped this on my way out Friday afternoon but will resume now

**Comment by ryan-williams** [comment]
I don't care that much about the Gitter and/or Jenkins badges so I'm going to close this as fixed by #763. lmk if you want me to re-open.
