### ISSUE TITLE
Unquoted subshell result, incorrect exit code in compute-adam-jars.sh

### ISSUE THREAD

**Issue by ryan-williams** [bigdatagenomics/adam#772]
On a clean repo:

```sh
$ bin/compute-adam-jars.sh
You need to build ADAM before running this program
$ echo $?
0
```

That "You need to build…" [should have been preceded by another `echo`](https://github.com/bigdatagenomics/adam/blob/6cade81d97eccfbad4b9630a4c7673ff3f27973e/bin/compute-adam-classpath.sh#L36-L37); also: exit code `0`?

[This is the culprit](https://github.com/bigdatagenomics/adam/blob/6cade81d97eccfbad4b9630a4c7673ff3f27973e/bin/compute-adam-jars.sh#L23): unquoted sub-shell call.

**Comment by fnothaft** [comment]
Resolved by https://github.com/bigdatagenomics/adam/commit/e7bb9670fff41286f6198219b3ab41a2d1823a13.
