### ISSUE TITLE
BQSR fails on ambiguous nucleotides

### ISSUE THREAD

**Issue by almussel** [bigdatagenomics/adam#775]
BQSR fails with scala.MatchError on nucleotide designations other then A, C, T, G, or N (other possibilities: http://www.ncbi.nlm.nih.gov/staff/tao/tools/tool_lettercode.html).

Is this something that should be supported? If not, should ambiguous nucleotides all be converted to N?

**Comment by fnothaft** [comment]
Ah... so, IIRC, the general rationale here was that "newer" sequencers don't normally use the full range of IUPAC codes.

I think it'd be a straightforward change. We could either match the remaining IUPAC codes to `N`, as suggested, or modify https://github.com/bigdatagenomics/adam/blob/35fbbb6a13ae5e8db142bec473e758fde729b3b2/adam-core/src/main/scala/org/bdgenomics/adam/rdd/read/recalibration/DinucCovariate.scala to use all IUPAC codes.

**Comment by fnothaft** [comment]
Closed by https://github.com/bigdatagenomics/adam/commit/207eebaf3dbf6f01e5b8398b2af388ee70c862aa.
