### ISSUE TITLE
loadAlignments does not properly convert "TYPE=B" tags

### ISSUE THREAD

**Issue by jfeala** [bigdatagenomics/adam#785]
The SAM specification allows numeric array tags (TYPE=B), which are not often used but are created by the STAR RNA-seq aligner.

I thought I resolves this with https://github.com/bigdatagenomics/adam/pull/782, but the problem is a bit more complicated. The code I fixed (https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/util/AttributeUtils.scala#L96) is not actually used by `AdamContext.loadBam`.

Instead, the problem is that `htsjdk.samtools.SAMRecord.SAMTagAndValue` correctly parses the tag string, but there is a problem casting the Java object to an array at https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/util/AttributeUtils.scala#L38 and it throws the following exception:

```
java.lang.ClassCastException: [I cannot be cast to [Ljava.lang.Byte;
	at org.bdgenomics.adam.util.AttributeUtils$.convertSAMTagAndValue(AttributeUtils.scala:38)
	at org.bdgenomics.adam.converters.SAMRecordConverter$$anonfun$convert$2.apply(SAMRecordConverter.scala:178)
	at org.bdgenomics.adam.converters.SAMRecordConverter$$anonfun$convert$2.apply(SAMRecordConverter.scala:174)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at org.bdgenomics.adam.converters.SAMRecordConverter.convert(SAMRecordConverter.scala:173)
	at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadBam$1.apply(ADAMContext.scala:268)
```

I tried to fix it myself, but I'm not a Scala programmer, and casting a Java Object into a parameterized type was sending me down a StackOverflow rabbit hole. Here is an example alignment (it's the jM and jI tags that are causing the problem):
```
C404RANXX150222:1:1210:7660:76662	163	chr1	4259695	255	21S55M	=	4259874	246	TGGGTTGAGATCAGGCCCTCAATCTCCTCGATGGTATGGACGATGAACATGTCCTGGAGGTCCTCCATGGCGCTCT	BB//BF<//<<FFB<FFF//<FFF/FFF//////</</BFFFFF/B/FBF/FFF//FFF//</F/<<B<B<<//<B	NH:i:1	HI:i:1	AS:i:100	nM:i:10	NM:i:3	MD:Z:19T15C14A4	jM:B:c,-1	jI:B:i,-1
```
As a temporary fix, the file can be loaded if the jI and jM tags are removed, but STAR is becoming more and more popular as an RNA-Seq aligner so people might start running into this more often.

**Comment by fnothaft** [comment]
Closed by https://github.com/bigdatagenomics/adam/commit/633fdf9d0073417e6f2f42ea54ee29447a9f3dd2.

**Comment by ryan-williams** [comment]
Per @jfeala's last email, we may still not be doing this completely correctly; I didn't add any logic around the `cCsSiIf` subtypes of `B`

**Comment by jfeala** [comment]
quick update on the tags issue -- I tracked down the samtools code for converting tags to objects. It's htsjdk.samtools.TextTagCodec, with methods `encode` and `decode`. Here's what I see for all of the data type options for B tags:

```
scala> import htsjdk.samtools.TextTagCodec
scala> val tagCodec = new TextTagCodec()

scala> tagCodec.decode("XY:A:-").getValue().getClass.getCanonicalName
res0: String = java.lang.Character

scala> tagCodec.decode("XY:Z:ABC123").getValue().getClass.getCanonicalName
res1: String = java.lang.String

scala> tagCodec.decode("XY:B:c,1").getValue().getClass.getCanonicalName
res2: String = byte[]

scala> tagCodec.decode("XY:B:s,1").getValue().getClass.getCanonicalName
res3: String = short[]

scala> tagCodec.decode("XY:B:i,1").getValue().getClass.getCanonicalName
res4: String = int[]

scala> tagCodec.decode("XY:B:f,1").getValue().getClass.getCanonicalName
res5: String = float[]

scala> tagCodec.decode("XY:B:C,1").getValue().getClass.getCanonicalName
res6: String = htsjdk.samtools.TagValueAndUnsignedArrayFlag

scala> tagCodec.decode("XY:B:I,1").getValue().getClass.getCanonicalName
res7: String = htsjdk.samtools.TagValueAndUnsignedArrayFlag

scala> tagCodec.decode("XY:B:S,1").getValue().getClass.getCanonicalName
res8: String = htsjdk.samtools.TagValueAndUnsignedArrayFlag

```

**Comment by jfeala** [comment]
It looks like [TagValueAndUnsignedArrayFlag](https://github.com/samtools/htsjdk/blob/master/src/java/htsjdk/samtools/TagValueAndUnsignedArrayFlag.java) is a simple wrapper for unsigned arrays (subtypes [CIS]), and stores the array object in `value`:
```
scala> tagCodec.decode("XY:B:S,1").getValue().asInstanceOf[TagValueAndUnsignedArrayFlag].value.getClass.getCanonicalName
res32: String = short[]
```
So it looks like it will be possible to infer all of these types from the tag value object. I think I can get started on this but will need a close review of the PR to catch any rookie mistakes
