### ISSUE TITLE
Add FASTA export

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#793]
This was suggested on #741 and would be useful for downstream projects (e.g., [ananas](https://github.com/fnothaft/ananas)).

**Comment by heuermh** [comment]
To clarify, this is for writing the sequences from an ```RDD[AlignmentRecord]``` out as FASTA format?  Seems easy enough, perhaps I should tackle it.  Any suggestions to the format of the description line?

**Comment by ryan-williams** [comment]
I assumed this would be `RDD[NucleotideContigFragment]` → `.fa` file.. then the contig names would be all you'd have to write.

**Comment by ryan-williams** [comment]
Update: `NucleotideContigFragment` [also contains a `description` field](https://github.com/bigdatagenomics/bdg-formats/blob/f5ce5daa58682c530da6e83a865959c604220c7d/src/main/resources/avro/bdg.avdl#L333)!

**Comment by ryan-williams** [comment]
But yea if you want to tackle this that would be great @heuermh

**Comment by heuermh** [comment]
Got it, thanks

**Comment by fnothaft** [comment]
Agreed; it'd be great for you to take this on @heuermh! It might also be good to write out the sequence dictionary while you do this, since those are popular to carry around.

There are a few nuances around how to actually do this, since genome assemblies and assembled contigs will have different dataset characteristics. E.g., with a finished assembly like hg19, it'd be OK to write each contig as a single partition file. With _unfinished_ assembled contigs, you probably would have too many contigs to want to write each as a partition.

**Comment by ryan-williams** [comment]
> It might also be good to write out the sequence dictionary while you do this

If he's writing a `.fa` file, where would the `SequenceDictionary` go?

**Comment by fnothaft** [comment]
@ryan-williams You could either write a `SequenceDictionary` per partition (as an accompanying file) or write a single `SequenceDictionary` for all files. I think the former is more correct. This would not be an ADAM `SequenceDictionary` but a Picard/SAMtools `*.dict`.

**Comment by heuermh** [comment]
I've created a pull request for a new ```adam2fasta``` command in #816.

Some possible points for conversation:
 - I haven't done anything with ```SequenceDictionary``` as mentioned above
 - I'm keying sequences by ```contig.contigName``` rather than ```ReferenceRegion```
 - A ```reduceByKey``` depends on the sort order from an earlier ```sortBy```, and I'm not sure that is ok
 - I'm performing a ```coalesce(1)``` before writing instead of using partitioning as mentioned above
