### ISSUE TITLE
RNAME and RNEXT fields jumbled on transform BAM->ADAM->BAM

### ISSUE THREAD

**Issue by almussel** [bigdatagenomics/adam#795]
About ~10% of reads on the test BAM file I'm using transport the RNAME field to RNEXT on transforming to ADAM and back.

Ex:

ORIGINAL:
PROD103_713:1:1:11748:99410     69      chr20   26271737        0       *       =       26271737        0  ...

TRANSFORMED:
PROD103_713:1:1:11748:99410      69      *       0       0       *       chr20   26271737   0  ...

**Comment by ryan-williams** [comment]
Weird! How small of a BAM can you repro this on? Or if you want to point me at the BAM you're using I can try it as well.

**Comment by almussel** [comment]
Okay, so I discovered taht something is funky with the BAM file I'm using (The fields contradict each other). I will see if I can reproduce the issue on a properly formatted BAM.

**Comment by heuermh** [comment]
@almussel Can this issue be closed?

**Comment by fnothaft** [comment]
I believe we did resolve this. Closing.
