### ISSUE TITLE
Use same sort order as Samtools

### ISSUE THREAD

**Issue by almussel** [bigdatagenomics/adam#796]
ADAM sorts by reference purely lexicographically, which puts unmapped reads at the beginning and mixes up chromosome order. Samtools sorts using the reference order specified in the header puts unmapped reads at the end. There are also some other subtleties that I don't know the specifics of.

**Comment by fnothaft** [comment]
Just to connect the tickets, fixing this would fix one of the three issues in #794.

**Comment by fnothaft** [comment]
Closed by #1045.
