### ISSUE TITLE
Allow alphabets to canonicalize strings

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#797]
The `Alphabet` class that was added in https://github.com/bigdatagenomics/adam/commit/6ce4ef7c3c23580b1f083642a5c679ff86f59da5 (resolved #410) allows alphabets to reverse complement a string. If you can reverse complement a string, than you can give a string a canonical representation (the canonical representation is the lexicographically "earlier" string out of the original string and it's reverse complement). This is useful for various assembly/reference-free algorithms.

**Comment by fnothaft** [comment]
@heuermh and I think we will need to drop Alphabet in favor of a future bdg-formats release.

**Comment by heuermh** [comment]
Closing as WontFix
