### ISSUE TITLE
ReferenceRegion joins fail on clusters

### ISSUE THREAD

**Issue by arahuja** [bigdatagenomics/adam#817]
Tried out some simple code for `BroadcastRegionJoin` and saw some odd issues:

```scala
val features = sc.parallelize(Seq(
  Feature
  .newBuilder
  .setStart(14642).setEnd(14882)
  .setContig(Contig.newBuilder.setContigName("1").build)
  .build
)).keyBy(ReferenceRegion(_))

val bigRegions = sc.parallelize(Seq(
  Feature
  .newBuilder
  .setStart(14000).setEnd(14700)
  .setContig(Contig.newBuilder.setContigName("1").build)
  .build
)).keyBy(ReferenceRegion(_))


import org.bdgenomics.adam.rdd.BroadcastRegionJoin

val joined = BroadcastRegionJoin.partitionAndJoin(features, bigRegions)
println(joined.count())
```

Inside the `BroadcastRegionJoin` there are two keyeds RDDs created `smallerKeyed` and `largerKeyed` when testing a simple join those (which do have the correct `ReferenceRegion` of `ReferenceRegion(1,14642,14882,Independent)` - that is also empty.

This seems to have to do with the hashcode of `ReferenceRegion` and containing an enum.
See: http://dev.bizo.com/2014/02/beware-enums-in-spark.html and https://issues.apache.org/jira/browse/SPARK-3847

For example, using the RDDs above, when keyed:

```scala
largerKeyed.collect().foreach(kv => println(kv._1))
largerKeyed.map(_._1.hashCode).collect().foreach(println)
```
 gives

```
ReferenceRegion(1,14642,14882,Independent)
357733957
```

and 

```scala
smallerKeyed.collect().foreach(kv => println(kv._1))
smallerKeyed.map(_._1.hashCode).collect().foreach(println)
```

gives

```
ReferenceRegion(1,14642,14882,Independent)
748344672
```

**Comment by laserson** [comment]
Wow, that's not good.  Where does the `enum` come into the code?  Could fixing this be as easy as overriding the `hashCode` method?

**Comment by arahuja** [comment]
> Where does the enum come into the code
`ReferenceRegion` has a `orientation` as an enum

> Could fixing this be as easy as overriding the hashCode method?
I believe so - testing it now

**Comment by fnothaft** [comment]
Fascinating. This is a [fairly recent regression](https://github.com/bigdatagenomics/adam/commit/9a318ba40527ad660dd7637d8a7d5536adf14c7e). Good catch...

**Comment by fnothaft** [comment]
Closed by https://github.com/bigdatagenomics/adam/commit/c4b23e0be0898b1c662f5a08dd7fe9b8236f1775.

**Comment by arahuja** [comment]
For some reason didn't close on Github? I can close this but wasn't sure if there was an update in the protocol/how the merge scripts are supposed to close this?

**Comment by fnothaft** [comment]
Sorry, my bad. Still working on the merge scripts...
