### ISSUE TITLE
Use Adam File with Hive

### ISSUE THREAD

**Issue by walz1** [bigdatagenomics/adam#820]
Hi everyone,
I´m really new in the field of Hadoop / Hive / Spark so I need some help:

I`ve opened the adam-submit shell and used the vcf2adam command to convert a vcf file to an adam formatted one. After that I got a folder within some .parquet data sets. 
Now I try to import them into a HIVE table on my Hadoop cluster to query them. The import data command works fine but when I try to run a SELECT * FROM parquet_table; I get different errors.

Do you have any Ideas?

**Comment by fnothaft** [comment]
Closing as need more info to reproduce.
