### ISSUE TITLE
BroadcastRegionJoin fails with unmapped reads

### ISSUE THREAD

**Issue by arahuja** [bigdatagenomics/adam#821]
This is obvious in hindsight as `AlignmentRecord` -> `ReferenceRegion` gives a `NullPointerException` on unmapped reads.

I opened to the issue to discuss what everyone think the best solution.  Things I've thought of are:
1. Do nothing, assume users will only do this with mapped reads, maybe throw a better warning (as obvious as it is now, I was not clear why this was failing for a while)
2. Filter unmapped reads for users before they perform the join
3. Join unmapped regions with some `Unmapped` region-like placeholder?

2 seems the most reasonable?

**Comment by ryan-williams** [comment]
> This is obvious in hindsight as AlignmentRecord -> ReferenceRegion gives a NullPointerException on unmapped reads.

BRJ doesn't do `AlignmentRecord` -> `ReferenceRegion` conversions though, does it?

**Comment by arahuja** [comment]
No I guess technically not, it's take things keyed by `ReferenceRegion` so perhaps `AlignmentRecord -> ReferenceRegion` should fail with a better error? But I could also imagine BRJ doing this automatically and filtering the unmapped reads.

**Comment by laserson** [comment]
I vote for #1.  I'd prefer the join impl not do additional operations that may not be obvious.

**Comment by fnothaft** [comment]
This is resolved by pending PR #1324. Closing in favor of the main ShuffleRegionJoin ticket #1216.
