### ISSUE TITLE
adam build failure

### ISSUE THREAD

**Issue by sbvarre** [bigdatagenomics/adam#825]
Hello All,

The adam build

 fails with the following error message:

" Plugin pl.project13.maven:git-commit-id-plugin:2.1.15 or one of its dependencies could not be resolved: Failed to read artifact descriptor for pl.project13.maven:git-commit-id-plugin:jar:2.1.15: Could not transfer artifact pl.project13.maven:git-commit-id-plugin:pom:2.1.15 from/to central (https://repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:443 [repo.maven.apache.org/23.235.47.215] failed: Connection timed out -> [Help 1]"

![adam build error](https://cloud.githubusercontent.com/assets/8506259/9966596/a52ccd38-5df2-11e5-8bf2-9e4805a6170a.JPG)
Any suggestions will be greatly appreciated.
Thanks,
Bharath

**Comment by heuermh** [comment]
Can you try accessing https://repo.maven.apache.org/maven2 directly?  Perhaps there was a network problem.

**Comment by sbvarre** [comment]
I tried accessing maven2 and it works, but during the build it somehow fails.
