### ISSUE TITLE
Fix "Long can't equal null" warnings

### ISSUE THREAD

**Issue by ryan-williams** [bigdatagenomics/adam#826]
cf. https://github.com/bigdatagenomics/adam/commit/c4b23e0be0898b1c662f5a08dd7fe9b8236f1775#commitcomment-13318008

**Comment by ryan-williams** [comment]
Feels like we can just drop the checks and the default `0` value?

**Comment by fnothaft** [comment]
I think the reason we need the checks for `null` is that we use the `ReferencePosition` with `null`s to handle unmapped reads during sort (and possibly markdups).

**Comment by ryan-williams** [comment]
but how could we even instantiate a `ReferenceRegion` with `null` for e.g. `start`?

```
scala> case class A(l: Long)
defined class A

scala> A(null)
<console>:13: error: an expression of type Null is ineligible for implicit conversion
       A(null)
         ^
```

**Comment by fnothaft** [comment]
@ryan-williams I think you're right and I was mistaken. I looked back through the code and couldn't find a constructor with nulls.
