### ISSUE TITLE
Gracefully handle missing Spark- and Hadoop-versions in jenkins-test; document how to set them.

### ISSUE THREAD

**Issue by sbvarre** [bigdatagenomics/adam#827]
I tried running the Jenkins test (./scripts/jenkins-test) and I get the following message which I am not sure how to interpret.

![jenkins test](https://cloud.githubusercontent.com/assets/8506259/10058173/f298bb7c-61f8-11e5-9794-40b9bf145c10.JPG)

The reactor summary shows that the jars are built fine.But it still doesn't recognize the Hadoop version and the Spark version.

Any help/suggestions are greatly appreciated.

Thanks.
Bharath

**Comment by ryan-williams** [comment]
it is expecting the $HADOOP_VERSION env var to be set to one of those three
values.
<https://github.com/bigdatagenomics/adam/blob/master/scripts/jenkins-test#L29-L38>

Presumably something in the jenkins config sets those things when it's
doing its testing matrix over all supported {Spark, Hadoop} versions.

I never run jenkins-test locally, fwiw. I just run `mvn test`, and let
jenkins do the heavy lifting on PRs; it's ok to submit PRs where jenkins
fails many times before it ultimately passes. People will often hold off on
looking at them until the tests pass.

**Comment by fnothaft** [comment]
> Presumably something in the jenkins config sets those things when it's doing its testing matrix over all supported {Spark, Hadoop} versions.

Correct!

**Comment by sbvarre** [comment]
Thank you Ryan and Frank. I was just trying to follow the instructions to see if It would fetch the mouse chromosome, encode it to ADAM reads and pileups, run flagstat, etc.

**Comment by ryan-williams** [comment]
We should probably:

- [ ] have a better error message in `jenkins-test` when versions are not set
- [ ] clarify how/what they should be set to in the README / other docs

**Comment by heuermh** [comment]
I started converting ```jenkins-test``` into a nextflow pipeline as a demonstration and found that it calls
```
"$ADAM" reads2ref "$READS" "$PILEUPS"
```
which doesn't exist as an ADAM command.  Was ```reads2ref``` removed or renamed, or perhaps turned into a ```transform``` option?
