### ISSUE TITLE
Normalize AlignmentRecord.recordGroup* fields onto a separate record type

### ISSUE THREAD

**Issue by ryan-williams** [bigdatagenomics/adam#828]
cf. [a long discussion @fnothaft and I had in gitter](https://gitter.im/bigdatagenomics/adam?at=56041bd4a0ecf0e07a8e94e0), the [recordGroup* fields](https://github.com/bigdatagenomics/bdg-formats/blob/55cc2282f2beed03b8f85667a41244dbc5f1e8f0/src/main/resources/avro/bdg.avdl#L235-L246) should maybe be outsourced to their own record, and joined with ARs on the recordGroupName field.

**Comment by fnothaft** [comment]
Resolved by #906.
