### ISSUE TITLE
Building Adam on OS X 10.10.5 with Java 1.8

### ISSUE THREAD

**Issue by dbl001** [bigdatagenomics/adam#835]
Hi,

I recently downgraded Adam to version 1.6 because of a problem with  the method: adamLoad().
<console>:20: error: value adamLoad is not a member of org.apache.spark.SparkContext

```
git clone -b adam-parent-0.16.0 https://github.com/bigdatagenomics/adam.git
```
Now, I'm having problems building adam with Java 1.8:
```
$ java -version
java version "1.8.0_05"
Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.5-b02, mixed mode)
David-Laxers-MacBook-Pro:adam davidlaxer$ mvn -version
Apache Maven 3.2.1 (ea8b2b07643dbb1b84b6d16e1f08391b666bc1e9; 2014-02-14T09:37:52-08:00)
Maven home: /Users/davidlaxer/Downloads/apache-maven-3.2.1
Java version: 1.8.0_05, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.5", arch: "x86_64", family: "mac"
```
1. Can Adam 1.6 be built with Java 1.8?
2. What's the replacement for the adamLoad() method in the current version of adam?

**Comment by fnothaft** [comment]
Hi @dbl001 !

What sort of data are you trying to load? (e.g., read, variant, etc) We changed `adamLoad` to specific functions per each datatype (this made type checks cleaner), e.g., [`loadAlignments` for reads](https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala#L581), [`loadGenotypes` for genotypes](https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala#L555), [`loadVariants` for variants](https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala#L568), [`loadSequence` for contigs](https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala#L540), etc.

I'm not sure about 0.16.0, but I do know that the current ToT can be used with Java 1.8. IIRC, we added Java 8 support in ADAM 0.17.0.

**Comment by dbl001** [comment]
Hi,

Thanks for the quick response!

I’m working through Chapter 10 of ‘Advanced Analytics with Spark’.
The data was /users/davidlaxer/genomics/HG00103.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522.bam,
which I converted with ‘adam’ to parquet format in HDFS.

Don’t know if you can see the screen snapshot below:

**Comment by dbl001** [comment]
Spark 1.5
Hadoop 3.0 Snapshot
Maven 3.2.1
Java 1.8

**Comment by fnothaft** [comment]
Hmmm, the snapshot didn't come across. Can you try again? If not, you can feel free to email it to me and I will take a look (probably tomorrow).

**Comment by fnothaft** [comment]
Closing as resolved/no additional follow up.
