### ISSUE TITLE
Explicitly validate user args passed to transform

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#841]
Comes out of discussion on #831 and https://github.com/ryan-williams/adam/pull/1. With the "Swiss Army Knife" nature of `transform`, there are a fair number of possibly conflicting ways that arguments can be passed. We should more explicitly validate the arguments passed.

**Comment by heuermh** [comment]
Was this addressed in #1081?

**Comment by fnothaft** [comment]
No, it wasn't.

**Comment by fnothaft** [comment]
Closing as won't fix.
