### ISSUE TITLE
Improve parallelism during FASTA output

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#842]
We should be able to increase the parallelism of ADAM->FASTA transformation introduced in #816 by using `repartitionAndSortWithinPartitions` and streaming data through, instead of using a `groupBy`.

**Comment by heuermh** [comment]
I don't see any explicit ```groupBy``` or ```groupByKey```s in the code path for ADAM &rarr; FASTA, although I could be missing something.  There is a ```reduceByKey``` here

https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/rdd/contig/NucleotideContigFragmentRDDFunctions.scala#L102

**Comment by fnothaft** [comment]
Upon reflection, I don't think this is actually important. Closing.
