### ISSUE TITLE
Parquet logger has reawaken from its slumber

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#851]
After years (a year and a half? two years?) of quiet, the logging inside of Parquet has reawaken and is spamming all of our logs.

This is because when we [upgraded to Parquet 1.7.0](https://github.com/bigdatagenomics/adam/commit/a70b4ca12299a9639275671cb20f7887c63ecb09), the root package of Parquet changed from `parquet` to `org.apache.parquet` and we didn't update [this line](https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/util/ParquetLogger.scala#L25) in the `ParquetLogger` utility.

**Comment by laserson** [comment]
lol
