### ISSUE TITLE
Ensure Java API is up-to-date with Scala API

### ISSUE THREAD

**Issue by laserson** [bigdatagenomics/adam#855]
We can try to co-opt the Spark machinery for this: `JavaAPICompletenessChecker`.

**Comment by fnothaft** [comment]
Shall we try to get this in 0.19.0? Ping @laserson @heuermh

**Comment by heuermh** [comment]
Progress was made in pull request #1051 but I've since run into issue #1092.

**Comment by fnothaft** [comment]
This is resolved by WIP PRs #1387 and #1397. Closing in favor of.
