### ISSUE TITLE
adam-submit fails with no Spark installation

### ISSUE THREAD

**Issue by laserson** [bigdatagenomics/adam#857]
If I don't set `SPARK_HOME` and I don't have `spark-submit` on my `PATH`, then `adam-submit` errors out early:

```
$ bin/adam-submit 
Using ADAM_MAIN=org.bdgenomics.adam.cli.ADAMMain
```

I believe it's because the subshell call to `which spark-submit` returns an error code and `adam-submit` calls `set -e`.

**Comment by laserson** [comment]
cc @heuermh

**Comment by heuermh** [comment]
I thought you were the bash expert?  ;)
I can confirm this happens on HEAD.

**Comment by heuermh** [comment]
After further investigation it doesn't appear to be caused by anything I added recently.  Commenting out ```set -e``` does the trick, what is that for?
