### ISSUE TITLE
move_to_scala_2.11 and maven-javadoc-plugin

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#863]
The script we use to [build Scala 2.11](https://github.com/bigdatagenomics/adam/blob/master/scripts/move_to_scala_2.11.sh) blindly overwrites the [maven-javadoc-plugin](https://github.com/bigdatagenomics/adam/blob/master/pom.xml#L78) version to a version that doesn't exist.

As an aside, @AmplabJenkins should be catching this. Why isn't that failing our builds? Find out later on the news at 11.

**Comment by heuermh** [comment]
I use more explicit sed replacements and ```${scala.artifact.suffix}``` everywhere here
https://github.com/heuermh/adam-plugins/blob/master/scripts/move_to_scala_2.11.sh

**Comment by heuermh** [comment]
Does this mean that the javadocs for the Scala 2.11 release of version 0.18.0 are broken?

**Comment by heuermh** [comment]
Wasn't sure before but can confirm that this breaks the ```release.sh``` script.  Had to manually fix this during the 0.18.2 release.
