### ISSUE TITLE
Coalesce option should not force shuffle if reducing partition count

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#864]
In several of the CLI commands, we have a `-coalesce` option that allows the user to choose the number of output partitions. We run `coalesce(_, true)` which forces a shuffle. Instead, we should check whether or not the `coalesce` will increase or decrease the partition count. If it will decrease the partition count, we shouldn't pass the `true` flag unless the user wants to force a shuffle.

**Comment by ryan-williams** [comment]
Sounds like a good change. OOC do you know what happens if you call `.coalesce(_, false)` with a higher number of partitions?

**Comment by fnothaft** [comment]
@ryan-williams Ah, yes! If you do `.coalesce(_, false)` with a higher number of partitions, it won't change the number of partitions.

**Comment by heuermh** [comment]
for what it's worth, ```adam2fasta``` uses an additional option for ```-shuffle```
[ADAM2Fasta.scala#L32](https://github.com/bigdatagenomics/adam/blob/master/adam-cli/src/main/scala/org/bdgenomics/adam/cli/ADAM2Fasta.scala#L32)
[ADAM2Fasta.scala#L58](https://github.com/bigdatagenomics/adam/blob/master/adam-cli/src/main/scala/org/bdgenomics/adam/cli/ADAM2Fasta.scala#L58)
