### ISSUE TITLE
Format of release tag changed between 0.17.1 and 0.18.0 releases

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#868]
Compare ```adam-parent-2.11_0.18.0``` to ```adam-parent_2.11-0.17.1```, the dash and underscore traded places.

The artifactId is ```<artifactId>adam-parent_2.11</artifactId>```, so I believe the earlier one is slightly more correct.

**Comment by fnothaft** [comment]
Reverting back to the old format SGTM.
