### ISSUE TITLE
how to set Spark variables 

### ISSUE THREAD

**Issue by jerryivanhoe** [bigdatagenomics/adam#874]
Dear all,
I'm facing the issue that a conversion from VCF to ADAM is really slow. Chromosome 1 of Human Genome took 51709.791472 s to finish. From the logs I see that "only" 2 cores are working:
15/10/29 00:17:13 INFO scheduler.TaskSetManager: Starting task 445.0 in stage 0.0 (TID 481, ip-172-31-17-200.eu-west-1.compute.internal, RACK_LOCAL, 4760 bytes)
15/10/29 00:17:13 INFO scheduler.TaskSetManager: Finished task 430.0 in stage 0.0 (TID 479) in 199395 ms on ip-172-31-17-200.eu-west-1.compute.internal (480/490)
15/10/29 00:17:50 INFO scheduler.TaskSetManager: Starting task 447.0 in stage 0.0 (TID 482, ip-172-31-17-201.eu-west-1.compute.internal, RACK_LOCAL, 4760 bytes)
15/10/29 00:17:50 INFO scheduler.TaskSetManager: Finished task 441.0 in stage 0.0 (TID 480) in 216611 ms on ip-172-31-17-201.eu-west-1.compute.internal (481/490)
15/10/29 00:20:31 INFO scheduler.TaskSetManager: Starting task 451.0 in stage 0.0 (TID 483, ip-172-31-17-200.eu-west-1.compute.internal, RACK_LOCAL, 4760 bytes)
from "native" Spark I know that i can set some parametes manually on start: 
e.g. spark-submit --deploy-mode cluster --master yarn --num-executors 5 --executor-cores 5 --executor-memory 20g 
Will it work to modify /home/hadoop/.versions/spark-1.3.1.f/conf/spark-defaults.conf
in the case, that Spark is started by ADAM ? Or is there another way to set the number of executors and cores ?
Thanks for all your patience in advance.
Greetings
-Jerry

**Comment by laserson** [comment]
If you're working on EMR, you probably have to set the variables in a
particular way.  I'd check out the EMR Spark docs to see how to control the
number of executors etc.

**Comment by jerryivanhoe** [comment]
Hi Uri, with AWS Elastic MapReduce  the full power can be enebaled by using the "-x" Option with Spark. (s. https://aws.amazon.com/de/blogs/aws/new-apache-spark-on-amazon-emr/)
An AWS technician had a look at the source (adam-adam-parent-2.11_0.18.0/bin/) and thinks that arguments can be passed to spark . Would be great to know howw this can be done.
Anyway: my customer can now process the files with much higher speed. Have a nice weekend !
Jerry

**Comment by laserson** [comment]
Great!  Should we mark this issue as "closed"?

**Comment by jerryivanhoe** [comment]
Hi Uri, yes - this one is solved and hopefully it helps other when running into the same issue.
Thanks again for being so patient and for all your support !
