### ISSUE TITLE
How to count genotypes with a 10 node Spark/Adam cluster faster than with BCFTools on a single machine?

### ISSUE THREAD

**Issue by NeillGibson** [bigdatagenomics/adam#879]
Hi, 

How can I count genotypes in a Adam Genotype parquet file, using a Spark and Adam cluster, faster than doing the same thing  with a BCF file and BCFTools on a single machine?

I am looking into Spark/Adam as a potential back end for a scalable Variant and Genotype store. 

As a baseline for performance I used BCFTools to decompress, inflate and count variant/genotype records from the Chr_22 1000 genomes BCF file.
This took 5m7s with a single thread on a single machine. Chr_22 is just a small part of the full 1000 genomes Variant/Genotype data set, which of course includes the other chromosomes. 

My expectation was that with a small Spark and Adam cluster this could be done at least an order of magnitude faster. Say below a minute. 

To my surprise the best result I can get with a 10 node Spark/Adam cluster is slower than my single machine BCFTools baseline, and that is with using at least 10 times as much resources.
The best results I could get with Spark and Adam is 8m8s. This doesn't even take in to account that I really would like to count (query) variants for which a expensive groupByKey (variant id/pos) is needed. 

Am I mistaken to look in to Spark and Adam as potential (future) scalable back end for storing and querying Variants and Genotypes?
Should I look into related technology for setting up a scalable variant and genotype store? For instance SparkSQL or Impala, or something completely else? 
Is in memory caching (of compressed Variant&Genotype data?) needed to get good (interactive) query performance?  And would that be possible for the 1000 genomes vcf file which is raw 1TB over all chromosomes? z

Or did I just make some mistakes with the commands somewhere?
My time to count genotypes looks slower than from the performance results mentioned here
http://bdgenomics.org/blog/2015/02/02/scalable-genomes-clustering-with-adam-and-spark/ 
Count chr22 genotypes (from HDFS):    10 min (2nodes)       1.4 min(20nodes) 

The exact code used to start up a Spark and Adam cluster and do the performance comparison with BCF tools is here:
https://github.com/NeillGibson/SparkAdamTest/blob/master/SparkAdamTest.sh

Any comments and insights would be much appreciated.

Best Regards,

Neill Gibson

**Comment by heuermh** [comment]
Thank you for documenting your use case, will take a look.

**Comment by NeillGibson** [comment]
Thank you!

**Comment by NeillGibson** [comment]
Hi Michael I had some time to look at the comments and test the changes.  For readability I split the results I found in multiple comment here:

**Comment by NeillGibson** [comment]
The following paths are the same:

./s3cmd-master/s3cmd

/home/ec2-user/s3cmd-master/s3cmd

The default user in the eggo cluster is ec2-user. After log in to the cluster the working directory is /home/ec2-user/

**Comment by NeillGibson** [comment]
I tried another vcf2adam conversion and count with your suggested changes. 

hadoop fs -mkdir  /user/ec2-user/test_18_11_2015
zcat /home/ec2-user/1kg/ALL.chr22.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz | hadoop fs -D dfs.block.size=134217728 -put - /user/ec2-user/1kg/test_18_11_2015/chr22.vcf

./adam-submit --master yarn-client --driver-memory 8g --num-executors 11 --executor-cores 4 --executor-memory 12531875840 -- vcf2adam -parquet_compression_codec SNAPPY -coalesce 10 /user/ec2-user/1kg/test_18_11_2015/chr22.vcf /user/ec2-user/1kg/test_18_11_2015/chr22.adam

15/11/18 05:03:51 INFO Vcf2ADAM: Overall Duration: 34 mins 7 secs

This 34 minutes is almost twice as long as the 18 minutes that the conversion took without the coalesce 10 parameter.
But we don't care much about this time. 
The coalesce to 10 parts seems to have worked. 
The parquet files are now almost 128 MB each. 

105.7	/user/ec2-user/1kg/test_18_11_2015/chr22.adam/part-r-00000.snappy.parquet
119.1	/user/ec2-user/1kg/test_18_11_2015/chr22.adam/part-r-00001.snappy.parquet
93.7	/user/ec2-user/1kg/test_18_11_2015/chr22.adam/part-r-00002.snappy.parquet
100.2	/user/ec2-user/1kg/test_18_11_2015/chr22.adam/part-r-00003.snappy.parquet
104.5	/user/ec2-user/1kg/test_18_11_2015/chr22.adam/part-r-00004.snappy.parquet
106.6	/user/ec2-user/1kg/test_18_11_2015/chr22.adam/part-r-00005.snappy.parquet
105.5	/user/ec2-user/1kg/test_18_11_2015/chr22.adam/part-r-00006.snappy.parquet
70.8	/user/ec2-user/1kg/test_18_11_2015/chr22.adam/part-r-00007.snappy.parquet
58.4	/user/ec2-user/1kg/test_18_11_2015/chr22.adam/part-r-00008.snappy.parquet
117.4	/user/ec2-user/1kg/test_18_11_2015/chr22.adam/part-r-00009.snappy.parquet

Next I started again the adam shell and performed a count. 

./adam-shell --master yarn-client --driver-memory 8g --num-executors 11 --executor-cores 4 --executor-memory 12531875840

# Import the AdamContext and the avro schemas
import org.bdgenomics.adam.rdd.ADAMContext
import org.bdgenomics.formats.avro._
# Create the AdamContext
val ac = new ADAMContext(sc)

val genotypes = ac.loadGenotypes("/user/ec2-user/1kg/test_18_11_2015/chr22.adam")
genotypes.count

15/11/18 05:46:12 INFO DAGScheduler: Job 0 finished: count at <console>:30, took 1175.70034 s
So the new count takes 19 minutes, which is more than double the time it took without the coalecse parameter. 
This maybe has to do with that the number of parallelism is now limited to 10 chunks, so only 10 cpu (out of the 40) of the cluster are used.

**Comment by NeillGibson** [comment]
I also tried the projection. 
```
import org.bdgenomics.adam.rdd.ADAMContext
import org.bdgenomics.formats.avro._
import org.bdgenomics.adam.projections.Projection
import org.bdgenomics.adam.projections.GenotypeField._

val ac = new ADAMContext(sc)

val projection = Some(Projection(variant, alleles))

val genotypes = ac.loadGenotypes("/user/ec2-user/1kg/test_18_11_2015/chr22.adam", projection)
genotypes.count

15/11/18 06:11:18 INFO DAGScheduler: Stage 0 (count at <console>:36) finished in 684.361 s
```
With the projection the count takes 11.5 minutes. 
Still slower than the count without the coalesce parameter. 
And still slower than decompressing and serializing the variants and genotypes with bcftools view, which takes just 5 minutes on a single cpu.

**Comment by fnothaft** [comment]
Using the chr22.vcf from 1kg, count times on 5 16-core nodes are:

* Using RDD API ~4.5min
* Using Dataset API <10sec

Marking this as closed.
