### ISSUE TITLE
Work With ADAM fasta2adam in a distributed mode

### ISSUE THREAD

**Issue by guerai** [bigdatagenomics/adam#881]
Hello,
I'm beginner in genomic area but I'm studing K-mer sequence and I'm using spark on Hadoop, I want to test ADAM performance on my cluster. As First I want to convert my FASTA test files in adam files using fasta2adam.
I'm using adam-submit command:
adam-submit --conf spark.yarn.jar ${SPARK_HOME}/spark-1.5.0-bin-hadoop2.4/lib/spark-assembly-1.5.0-hadoop2.4.0.jar --master yarn-cluster  --driver-memory 4g --num-executors 15 --executor-cores 2 --executor-memory 4g fasta2adam  INPUT_FILE OUTPUT_FILE 

but command does not start on cluster but as single node
could someone help me
thanks for our time
Best regards

**Comment by heuermh** [comment]
I'm not sure why ```${SPARK_HOME}/spark-1.5.0-bin-hadoop2.4/lib/spark-assembly-1.5.0-hadoop2.4.0.jar``` is there, might that be mistakenly interpreted to be the application jar?

https://spark.apache.org/docs/1.5.1/submitting-applications.html#launching-applications-with-spark-submit

**Comment by guerai** [comment]
Sorry it was a misprint. I want to execute fasta2adam conversion on my test cluster and I'm using this command
adam-submit --master yarn-cluster --driver-memory 4g --num-executors 15 --executor-cores 2 --executor-memory 4g fasta2adam INPUT_FILE OUTPUT_FILE
the cluster works well with hadoop and spark but not using adam-submit
Thanks for your time

**Comment by heuermh** [comment]
You might try
```bash
adam-submit \
  --master yarn-cluster \
  --driver-memory 4g \
  --num-executors 15 \
  --executor-cores 2 \
  --executor-memory 4g \
  -- \
  fasta2adam INPUT_FILE OUTPUT_FILE
```
Note the ```--``` separating the Spark and ADAM options.  This feature was [added recently](https://github.com/bigdatagenomics/adam/commit/a11af962dadb8e0d700b8f85678c334a0db1e822) and may not be very obvious from documentation (e.g. I don't see it mentioned anywhere in the current version of [README.md](https://github.com/bigdatagenomics/adam/blob/master/README.md)).

**Comment by guerai** [comment]
Thanks for you answer now my job start on my cluster I have all executors that I have been set in command line I'm trying to convert my file thanks for your help. I'll update about my progress
best regards

**Comment by guerai** [comment]
Thanks with your help I was able to confevert  a fasta file type in an adam file, but when I try to count kmers

adam-submit   --master yarn-cluster   --driver-memory 4g   --num-executors 15   --executor-cores 2   --executor-memory 4g --  count_kmers  hdfs://INPUTFILE hdfs://OUTPUTFILE 20

I receive always the same error:
User class threw exception: org.apache.hadoop.mapred.FileAlreadyExistsException: Output directory hdfs://OUTPUTFILE already exists 

also if I change it every executions.
It happen if I use the as input file the entire directory of transformed file that contains all part-** sub files and also if I use as input the merged single file created with  hadoop fs -getmerge
I'm finding other solution to solve it.

**Comment by fnothaft** [comment]
Closing as resolved/not an ADAM bug.
