### ISSUE TITLE
R language package for Adam

### ISSUE THREAD

**Issue by chanwit** [bigdatagenomics/adam#882]
Hi,

I've successfully created a simple R package `AdamR` similar to `SparkR` in the Spark project.
It's been working greatly enough for me to do `countKmers` and turn its result into a local R dataset.

How could I contribute this package? Does it fit into this project?

**Comment by heuermh** [comment]
Very cool!

Easiest would be a pull request against this repo and then everyone could evaluate where it best fits.

If you would like to contribute to [bigdatagenomics](https://github.com/bigdatagenomics/) repositories, and haven't yet, you may want to fill out a [contributor license agreement](http://bdgenomics.org/cla/).

**Comment by fnothaft** [comment]
Just pinged @chanwit; he's working on licensing with his institution. We'll watch this ticket!
