### ISSUE TITLE
Add Spark version 1.5.x to Jenkins build matrix

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#889]
Might also want to add Hadoop 2.7.x (currently at 2.7.1) and bump 2.6.x to the most recent (currently at 2.6.2), although I'm not sure of the rationale behind the specific Hadoop versions chosen.

**Comment by heuermh** [comment]
@fnothaft might you be able to let me know how to do this?  Looks like build configuration changes will require a Jenkins login.

**Comment by fnothaft** [comment]
@heuermh will follow up offline.

**Comment by heuermh** [comment]
Thank you @fnothaft, I have what I need and will look into this tomorrow.

**Comment by heuermh** [comment]
Worked for me here
https://amplab.cs.berkeley.edu/jenkins/job/ADAM/1364/

I'll trigger a rebuild on a pull request to confirm the ADAM-prb project also works.

**Comment by fnothaft** [comment]
Looks like [ADAM-prb](https://github.com/bigdatagenomics/adam/pull/888#issuecomment-162057105) is good as well! Thanks @heuermh!
