### ISSUE TITLE
error in vcf2adam

### ISSUE THREAD

**Issue by dnaase** [bigdatagenomics/adam#899]
When I try to convert vcf to adam, no matter output gzipped or not.

adam-submit vcf2adam test.vcf test_vcf.adam -parquet_compression_codec GZIP

 It always gives the following warnings. 

Dec 22, 2015 2:28:27 PM WARNING: org.apache.parquet.hadoop.ParquetOutputCommitter: could not write summary file for test_vcf.adam
org.apache.parquet.io.ParquetEncodingException: test_vcf.adam/part-r-00000.gz.parquet invalid: all the files must be contained in the root test_vcf.adam

Also, when i load in test_vcf.adam adam-shell. it always give error:

java.lang.IllegalArgumentException: unknown VCF format, cannot create RecordReader: file:test_vcf.adam/part-r-00000.gz.parquet

I am using the newest adam-0.18.2 with spark-1.5.1-hadoop-2.4 in java 8 environment

**Comment by heuermh** [comment]
Hello!  I haven't been able to reproduce those exact warnings.  Is the file ```test_vcf.adam/part-r-00000.gz.parquet``` empty?

Guessing at your input data, note that VCF files representing dbSNP may not include any genotypes, only variants, so you may wish to use the ```-only_variants``` flag in your ```vcf2adam``` step.  E.g.
```none
$ head dbsnp_138.hg19.vcf
##fileformat=VCFv4.1
...
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
chrM    64      rs3883917       C       T       .       .       ASP;CAF=[0.9373,0.06268];COMMON=1;OTHERKG;R5;RS=3883917;RSPOS=64;SAO=0;SSR=0;VC=SNV;VP=0x050000020005000002000100;WGT=1;dbSNPBuildID=108

$ adam-submit -- vcf2adam -only_variants dbsnp_138.hg19.vcf dbsnp_138.hg19.adam
$ adam-submit -- print dbsnp_138.hg19.adam -o dbsnp_138.hg19.out
$ head dbsnp_138.hg19.out
{"variantErrorProbability": null, "contig": {"contigName": "chrY", "contigLength": null, "contigMD5": null, "referenceURL": null, "assembly": null, "species": null, "referenceIndex": null}, "start": 1412328, "end": 1412329, "referenceAllele": "G", "alternateAllele": "A", "svAllele": null, "isSomatic": false}
{"variantErrorProbability": null, "contig": {"contigName": "chrY", "contigLength": null, "contigMD5": null, "referenceURL": null, "assembly": null, "species": null, "referenceIndex": null}, "start": 1412353, "end": 1412356, "referenceAllele": "TCA", "alternateAllele": "TT", "svAllele": null, "isSomatic": false}
```

**Comment by dnaase** [comment]
Thanks a lot! I figure it out when i tried anno2adam!

**Comment by heuermh** [comment]
Great!  May I close this issue?
