### ISSUE TITLE
Fix the -list_comparisons argument in CompareAdam

### ISSUE THREAD

**Issue by tdanford** [bigdatagenomics/adam#90]
It's suboptimal that there's no way to get a list of comparisons, without also specifying inputs, e.g.

$ adam compare -list_comparisons

Prints the usage help with 'Argument "INPUT1" is required'. ...

Can we figure out a way to have an optional -list_comparisons flag, without requiring the INPUT{1,2} arguments as well?

**Comment by jvivian** [comment]
I'll be taking a crack at this over the weekend.

**Comment by fnothaft** [comment]
w00t! Thanks for taking a crack, @jvivian!

**Comment by jvivian** [comment]
Apologies for taking so long on this -- submitted a pull request.

**Comment by fnothaft** [comment]
Resolved by #560 via https://github.com/bigdatagenomics/adam/commit/1956ac9dc990b4e551e4764fc833bcf50ee8e720.
