### ISSUE TITLE
secondOfPair and firstOfPair flag is missing in the newest 0.18 adam transformed results from BAM

### ISSUE THREAD

**Issue by dnaase** [bigdatagenomics/adam#903]
Hi, i found that when i use the most recent 0.18 adam to transform bam file to adam, the secondOfPair and firstOfPair is missing, while the same bam file which i transformed use 0.17 adam, the secondOfPair and firstOfPair flag is still there.

**Comment by fnothaft** [comment]
Hi @dnaase! We removed the `firstOfPair` and `secondOfPair` fields in https://github.com/bigdatagenomics/bdg-formats/pull/52. These fields are replaced by `readInFragment` (see https://github.com/bigdatagenomics/bdg-formats/pull/66). The goal of this change was to support sequencing technologies that generate more than 2 reads from a single fragment (e.g., Complete Genomics). `readInFragment == 0` is the same as `firstOfPair`, while `readInFragment == 1` is the same as `secondOfPair`. Let me know if you've got any more questions!
