### ISSUE TITLE
Clean up RDD method names

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#910]
We've got a lot of methods in the `*RDDFunctions` classes whose names are `adamSomething` (e.g., `adamSortReads` or `adamSAMSave`. I'd like to eliminate the use of `ADAM` as a prefix, since it's somewhat redundant.

**Comment by heuermh** [comment]
+1

**Comment by fnothaft** [comment]
Closed by https://github.com/bigdatagenomics/adam/commit/70eaa70835c11fb81445a22a7b1752d831c66bd3.
