### ISSUE TITLE
Customize adam-main cli from configuration file

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#918]

**Comment by fnothaft** [comment]
@heuermh what exactly where your thoughts on this? Like, the user would provide a manifest with classnames that would be populated into adam-main? Some sort of dependency injection system? For now, I think we should punt on this as out of scope.

**Comment by heuermh** [comment]
We already have dependency injection, someone said this during a meeting or call so I added an enhancement request for it.  Fine to bump until later.

**Comment by fnothaft** [comment]
SGTM!

**Comment by fnothaft** [comment]
We haven't had another request for this in the last 9 months. @heuermh please reopen if you think we should support it.
