### ISSUE TITLE
Autogen field names in projection package

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#941]
@jpdna has identified a bug whose root cause has to do with a default field being used when a field is projected out using Parquet's projection feature and our `org.bdgenomics.adam.projection` package. The TL;DR on the bug (@jpdna can you open an issue for this and link the issue to this issue?) is that the `firstOfPair`/`secondOfPair` fields changed to `readInFragment` but the [AlignmentRecordField](https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/projections/AlignmentRecordField.scala) enum didn't get changed, so the projection didn't get fixed. To not have this problem come up in the future, we should autogenerate the enums from the avro schemas from bdg-formats.

**Comment by heuermh** [comment]
Adding unit tests for projection field classes in #1144.   I was hoping these could be a template for any auto-generated code, but unfortunately the tests don't fail unless the manually written assertions fail.  There apparently isn't any runtime checking by Parquet.

**Comment by fnothaft** [comment]
This can be resolved using the codegen from #1391.

**Comment by fnothaft** [comment]
I will take this once #1391 merges.
