### ISSUE TITLE
.rgdict and .seqdict files are not placed in the adam directory

### ISSUE THREAD

**Issue by jpdna** [bigdatagenomics/adam#945]
This may not be a bug, but I wanted to check that it is intentional that the .adam.rgdict and .adam.seqdict when creating .adam files with  transform  appear in the filesystem directory structure as siblings to the parquet .adam directory.
If these cannot go in the parquet .adam directory, could they at instead go into a .adam.dicts directory to keep the dir structure a little cleaner?

**Comment by heuermh** [comment]
Note there are also ```.{name}.adam.rgdict.crc``` and ```.{name}.adam.seqdict.crc``` files.

**Comment by heuermh** [comment]
The more I think about this, the more I think they should go in the ```.adam``` directory.  I'm always bothered by other tools' handling of extra files (e.g. bowtie indices, picard sequence dictionaries, etc.), sometimes using command line arguments, sometimes using file base names, sometimes with certain file extensions, sometimes not.

Can we just hide these in the ```.adam``` directory and never have the user refer to them?

**Comment by heuermh** [comment]
Bummer about all the linked dead commits, guess if you add fixes ... to the commit message, it stays on the linked issue page even if the commit has been rebased and force pushed out of existence.
