### ISSUE TITLE
Flagstat results still don't match samtools flagstat

### ISSUE THREAD

**Issue by jpdna** [bigdatagenomics/adam#946]
Even after commit #943 fixed the main problem with counting of read_1 and read_2 there is still a difference between adam and samtools in counting total number of pairs.  I'm examining the samtools code for flagstat to make sure we apply the same same filters.

**Comment by jpdna** [comment]
at least part of this problem is due to samtools filtering out reads with the 0x800 flag set while ADAM does not.  However, trying to add this logic ran into another problem that it appears that within FlagStat.scala the p.getSupplementaryAlignment flag is providing incorrect results, as 
`samtools view -f 0x800  /jp5t/data/AshkenazimTrio/HG002.mate_pair.sorted.chr22.bam`
says there are 39225 reads with 0x800 set and ADAM seems to think there are 0.
I'm investigating whether the parquet file is correct.  I tried already to add `AlignmentRecordField.supplementaryAlignment`  to the flagstat and adamcontext projections but answer still incorrect.

**Comment by jpdna** [comment]
I think I have solved this, pull request coming later today

**Comment by heuermh** [comment]
Fixed via caa60d6ef36c8682e9e706bdf2ef1a02484cfd6a

**Comment by ryan-williams** [comment]
Two related questions:

* are any of these changes such that we don't actually agree with what `samtools` counts, but are mimicking it for concordance's sake?
* are there things that `samtools` doesn't output that we'd like to?

What I'm getting at is: should we have a flag that outputs a version that we like, and another flag (or more likely the default) that is char-for-char identical to `samtools`, as a sanity check?

**Comment by ryan-williams** [comment]
FTR, I just ran an ADAM flagstat from 0.19.0 against a v1.3 samtools; [this gist](https://gist.github.com/ryan-williams/45cc16d4c62f05643be95f3b4a40f672) has each output and the diff:

```
< 8021767 + 0 primary duplicates
< 7984598 + 0 primary duplicates - both read and mate mapped
< 37169 + 0 primary duplicates - only read mapped
< 44210 + 0 primary duplicates - cross chromosome
< 0 + 0 secondary duplicates
< 0 + 0 secondary duplicates - both read and mate mapped
< 0 + 0 secondary duplicates - only read mapped
< 0 + 0 secondary duplicates - cross chromosome
---
> 0 + 0 secondary
> 199776 + 0 supplementary
> 8021767 + 0 duplicates
14c9
< 53968350 + 0 properly paired (98.30%:0.00%)
---
> 53968350 + 0 properly paired (98.66% : N/A)
16c11
< 79540 + 0 singletons (0.14%:0.00%)
---
> 79540 + 0 singletons (0.15% : N/A)
```

The only line that ADAM doesn't include (in spirit if not char for char) is the "199776 + 0 supplementary", which seems probably insignificant?

The slightly off percentages also seem to be of minimal concern since the raw numbers for those lines concord.
