### ISSUE TITLE
NoSuchMethodError due to kryo minor-version mismatch

### ISSUE THREAD

**Issue by ryan-williams** [bigdatagenomics/adam#955]
Not sure we want to or should do anything about this, but documenting it fwiw.

I have some code that depends on adam-core_2.10-0.18.2, and from that [picks up a dependency on Kryo 2.24](https://github.com/bigdatagenomics/adam/blob/adam-parent_2.10-0.18.2/pom.xml#L302). Meanwhile, spark-core 1.6.0 [depends on Chill 0.5.0](https://github.com/apache/spark/blob/v1.6.0/pom.xml#L149) which [depends on Kryo 2.21](https://github.com/twitter/chill/blob/0.5.0/project/Build.scala#L13).

My code calls [Input.total](https://github.com/EsotericSoftware/kryo/blob/kryo-2.24.0/src/com/esotericsoftware/kryo/io/Input.java#L94) which is a `long` in Kryo 2.24 but [an `int` in Kryo 2.21](https://github.com/EsotericSoftware/kryo/blob/kryo-2.21/src/com/esotericsoftware/kryo/io/Input.java#L88), so I get a NoSuchMethodError because my code was compiled against 2.24 but picks up Spark's 2.21 at runtime.

I'm going to look into whether this can be mitigated by one of these "user classpath first" options that I've seen discussed around Spark-land.

**Comment by heuermh** [comment]
At a quick glance it doesn't appear we declare a runtime or compile time dependency on kyro, even though we define a version for it in the ```<dependencyManagement>``` section.  Maybe adding a runtime scope to your pom or to say adam-cli would override the Spark runtime dependency version?

**Comment by fnothaft** [comment]
> Maybe adding a runtime scope to your pom or to say adam-cli would override the Spark runtime dependency version?

IIRC, it does, but you need to muck around with classpaths in Spark submit, or something of that sort. It's a bit ugly of a bug. I ran into this or something similar on a pre-1.6 custom build.

**Comment by heuermh** [comment]
Is there anything actionable on this for the 0.20.0 release?

**Comment by fnothaft** [comment]
I don't think there's anything actionable for this on 0.23.0. I'm going to close this as won't fix. @ryan-williams please reopen if you think I am in error.
