### ISSUE TITLE
Issue with version 18.0.2 

### ISSUE THREAD

**Issue by ankushreddy** [bigdatagenomics/adam#957]
Hi am actually using a SNAP to align the fastq files using a single chromosome reference fasta file.
After this process when I try to use the transform command from adam to convert it from sam to parquet (adam) format after stage 0.0 tasks there are no new tasks getting started and cli is in stable state 
![image](https://cloud.githubusercontent.com/assets/15848115/13268728/5d9d5264-da41-11e5-9e78-bbc66b0e862f.png)
 it is standing there for hours.
Could you please look into this issue.

**Comment by fnothaft** [comment]
Hi @ankushreddy, this issue doesn't contain sufficient information to reproduce your issue. If possible, can you send us:

* Command line used for alignment
* Contig used for alignment
* FASTQ input
* Command line used for ADAM transform
* Spark/Hadoop versions
* Cluster scheduling mode (e.g., YARN, standalone, etc)

**Comment by heuermh** [comment]
@ankushreddy is this still an issue for you?

**Comment by ankushreddy** [comment]
@heuermh it got resolved Thanks.
