### ISSUE TITLE
Remove code workarounds necessary for Spark 1.2.1/Hadoop 1.0.x support

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#959]

**Comment by fnothaft** [comment]
@heuermh what is needed to resolve this? Did https://github.com/bigdatagenomics/adam/pull/989 resolve this?

**Comment by heuermh** [comment]
This means remove the parts of the code where we e.g. use reflection because of old Spark 1.x support.

**Comment by fnothaft** [comment]
Merged as https://github.com/bigdatagenomics/adam/commit/072f97df75f075d4c298624b84842f8abdb0eeed. Thanks @heuermh!
