### ISSUE TITLE
BAM output in ADAM appears to be corrupt

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#962]
Crosslinking to https://github.com/BD2KGenomics/toil-scripts/issues/117.

**Comment by fnothaft** [comment]
No dice on reading the per-partition BAM file:

```
~/adam$ samtools view part-r-00000
[E::hts_hopen] fail to open file 'part-r-00000' 
[E::hts_open_format] fail to open file 'part-r-00000' 
samtools view: failed to open "part-r-00000" for reading: Success
```

I don't think we write the BAM header with each partition, which might be scoobying this test. Let me change that and retry...

**Comment by fnothaft** [comment]
OK, same thing if I write the BAM header as part of each partition. IDK...?

Time to go all stone ages and `toLocalIterator` this up...

**Comment by fnothaft** [comment]
OK, have a WIP patch I am testing now at https://github.com/fnothaft/adam/tree/single-bam-localiter-ehf. So far, seems to work. Ugly as sin, but I'll clean it up later.

**Comment by fnothaft** [comment]
The patch works but the performance is terrible because `SAMRecordWritable` seems to fall back on Java serialization. I'm working on a new patch... TBD.

**Comment by fnothaft** [comment]
OK, got a working fix! PR is on the way shortly...

**Comment by jpdna** [comment]
Can this issue be closed?

**Comment by fnothaft** [comment]
No, the open PR still needs a fix.
