### ISSUE TITLE
Allow lowercase letters in jar/version names

### ISSUE THREAD

**Issue by ryan-williams** [bigdatagenomics/adam#974]
I sometimes build ADAM assembly JARs with the abbreviated git sha as the maven version; currently `adam-{shell,submit}` check for JARs with only numbers and uppercase letters, so they miss these.

**Comment by heuermh** [comment]
Fixed via 34f6dc21d551382b2ea135ff19703196b6a2cd1d

**Comment by heuermh** [comment]
Sorry for reopening this, I remembered a reason why ```a-z``` wasn't allowed, it pulls in the -javadoc jar
```bash
$ ./bin/adam-submit vcf2adam adam-core/src/test/resources/small.vcf small.adam
Found multiple ADAM cli assembly jars in /Users/xxx/working/adam/adam-cli/target:
adam-cli_2.10-0.19.1-SNAPSHOT-javadoc.jar
adam-cli_2.10-0.19.1-SNAPSHOT.jar
Please remove all but one jar.
```

**Comment by ryan-williams** [comment]
hrm that's annoying. my versions only use `a-f` so we could very hackily rely on the `j` and `o` in `-javadoc.jar` but that doesn't sound great.

should we encode our assumptions about jar basenames more explicity?

**Comment by heuermh** [comment]
I remember at one point there was a ```^[-javadoc]``` in the regex.  :)

Have at a new method to find the assembly jar; I don't like the current one.  The only interesting requirement is that the assembly jar is found in ```repo``` when running from a binary distribution and ```adam-cli/target``` when built from source.

**Comment by fnothaft** [comment]
Resolved by https://github.com/bigdatagenomics/adam/commit/4955aee8ff759f8e619c18a3f5c2352e9265da28.
