### ISSUE TITLE
Explore if SeqDict data can be factored out more aggressively

### ISSUE THREAD

**Issue by jpdna** [bigdatagenomics/adam#983]
Hoping to get feedback/discussion on  below:

There remains a substantial chunk of repeating Contig/SequenceRecord metadata that we are carrying around within `AlignmentRecord` RDDs  that I am curious if we can factor out more aggressively in the same way that we did for the `RecordGroupMetadata`.

Both `RecordGroup` and `SequneceDictionary` data have been factored out into separate dictionary files that we write alongside the main ADAM AlignmentRecord parquet files.  For the `RecordGroup` only the `recordGroupName` [remains](https://github.com/bigdatagenomics/bdg-formats/blob/master/src/main/resources/avro/bdg.avdl#L258)  in the `AligimentRecord`.  I understand this to have been done to reduce the size of the AlignmentRecord which gets created in memory and goes through shuffle - as we lose the Parquet dictionary encoding once we read it into an RDD.

The situation looks different though for SequenceDictionary and how Contig and mateContig continue to exist in their entirety in  `AlignmentRecord`.
Both `contig` and `mateContig` continue to exist in every `AlignmentRecord` each with their redundant fields that can be pretty large - especially the url.
```
  name: String,
    length: Long,
    url: Option[String],
    md5: Option[String],
    refseq: Option[String],
    genbank: Option[String],
    assembly: Option[String],
    species: Option[String]
```
, when these instead could be represented just as well in `AlignmentRecord` with only by a `sequenceRecordName` which links out to the `SequenceDictionary`.   Or do I misunderstand?

I'm curious to know if there is a reason why we are not normalizing this Contig and mateContig data in the same way was we do for the `RecordGroup`.

Also curious why the RecordGroupMetadata gets an entry in [bdg.avdl](https://github.com/bigdatagenomics/bdg-formats/blob/master/src/main/resources/avro/bdg.avdl#L67)
while SequenceRecord for the SequeneDictionary  does not.

**Comment by fnothaft** [comment]
> when these instead could be represented just as well in AlignmentRecord with only by a sequenceRecordName which links out to the SequenceDictionary.

I would +1 that change. (And, that same change for all other records, e.g., Genotype, Variant, etc).

> I'm curious to know if there is a reason why we are not normalizing this Contig and mateContig data in the same way was we do for the RecordGroup.

I don't remember entirely why I prioritized the `RecordGroup` data over the `Contig` data, but I think it was something along the lines of only having the time to change one, and the `RecordGroup` data being "heavier".

> Also curious why the RecordGroupMetadata gets an entry in bdg.avdl
> while SequenceRecord for the SequeneDictionary does not.

I think `Contig` and `SequenceRecord` are pretty similar.

**Comment by jpdna** [comment]
Super - I will work on a PR for doing that.

**Comment by heuermh** [comment]
I'm still not entirely happy with the separate SequenceDictionary/RecordGroupDictionary stuff in our API; for some context expand the comments in closed PR #906.

A lot of our API is based on ```RDD[SomeADAMType]``` + implict methods whereas the methods that use SequenceDictionary/RecordGroupDictionary return ```AlignmentRDD``` which is close to but not exactly the same thing.  Or more precisely, it is the same thing but sometimes the Scala compiler can't figure it out.

**Comment by heuermh** [comment]
@jpdna close this via #988, or do you think there are remaining issues?

**Comment by jpdna** [comment]
There are potential  remaining issues that contig could also be potentially factored out in same way from Variant and Feature

**Comment by fnothaft** [comment]
+1 to keep this open, for the same reason that @jpdna suggested.

**Comment by fnothaft** [comment]
Closed by https://github.com/bigdatagenomics/adam/commit/8abb47ad2447bbc0376f9b5052e2e029bdf6b604 and https://github.com/bigdatagenomics/adam/pull/1015.
