### ISSUE TITLE
Add homebrew guidelines to release checklist or automate PR generation

### ISSUE THREAD

**Issue by laserson** [bigdatagenomics/adam#987]
I think we have a few issues re: updating the homebrew version.

**Comment by heuermh** [comment]
I've been doing this manually and haven't run into any problems other than sometimes the release version will build and the HEAD will fail, but I suppose that's the nature of a HEAD build.  Do you have any specifics in mind?

**Comment by laserson** [comment]
Does this reflect our current release process?

https://github.com/bigdatagenomics/adam/tree/master/scripts/release

If so, we should add a note to also update homebrew

**Comment by fnothaft** [comment]
That's pretty close, yeah.

**Comment by heuermh** [comment]
The README could use an update with this, link fix, and also #936
