### ISSUE TITLE
Contig to ContigName Change not reflected in AlignmentRecordField

### ISSUE THREAD

**Issue by erictu** [bigdatagenomics/adam#991]
With the change in #988, contig was not changed to contigName in AlignmentRecordField. 

This means when loading data, all usages of `AlignmentRecordField.contig` don't filter correctly, even though no exception is thrown.

**Comment by jpdna** [comment]
https://github.com/bigdatagenomics/mango/issues/144

**Comment by jpdna** [comment]
@erictu  can you have a look at:
https://github.com/bigdatagenomics/adam/pull/992
to see if it address the bug you found.

**Comment by heuermh** [comment]
Fixed by #992
