### ISSUE TITLE
All file-based input methods should support running on directories, compressed files, and wildcards

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#993]
Following up on a frequently asked question via irc, would it make sense to follow Spark's lead:

> All of Spark’s file-based input methods, including ```textFile```, support running on directories, compressed files, and wildcards as well. For example, you can use ```textFile("/my/directory")```, ```textFile("/my/directory/*.txt")```, and ```textFile("/my/directory/*.gz")```.

https://spark.apache.org/docs/latest/programming-guide.html#using-the-shell

Wildcard globs are supported in a few places (e.g. ```vcf2adam```, perhaps others), and compressed files are supported where Hadoop-BAM supports them.  I've never tried using a directory.

**Comment by fnothaft** [comment]
Yeah, I would +1 that.

**Comment by heuermh** [comment]
The only place I think this might fall down is on paired FASTQ files, or maybe we can rely on convention for that.

**Comment by fnothaft** [comment]
FASTQ makes me sad, but paired FASTQ makes me sadder.

**Comment by laserson** [comment]
+1 on supporting this
