### ISSUE TITLE
Has the project realized alignment reads to reference genome algorithm ?

### ISSUE THREAD

**Issue by xubo245** [bigdatagenomics/adam#996]
Hello everyone:
      Excuse me,Has the project realized alignment reads to reference genome algorithm in thebigdatagenomics/adam?such as BWA-SW、SNAP algorithm. I remember SNAP algorithm coding by C++.

Thanks
jack xu
@huitseeker @hammer @jey @massie @heuermh

**Comment by fnothaft** [comment]
Hi @xubo245! See some work-in-progress at https://github.com/bigdatagenomics/snappea.

**Comment by fnothaft** [comment]
Closing this, as it won't be done in ADAM core.
