### ISSUE TITLE
Refactor SequenceDictionary to use Contig instead of SequenceRecord

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/adam#997]
In discussion with @tdanford around `RDD[Feature]`s we thought it might be worthwhile to refactor SequenceDictionary to use Contig from bdg-formats instead of SequenceRecord.

I also suggested renaming Contig to Reference and adding a new schema class ReferenceSet, per GA4GH (https://github.com/ga4gh/schemas/blob/master/src/main/resources/avro/references.avdl#L17 and https://github.com/ga4gh/schemas/blob/master/src/main/resources/avro/references.avdl#L79, respectively).  I'm not suggesting using those schema classes wholesale, just the names.  I'm not that keen on the name ReferenceSet either, but calling it Assembly was problematic.

**Comment by fnothaft** [comment]
Closing this, as https://github.com/bigdatagenomics/bdg-formats/issues/43 seems like a better solution.
